jupyter-book/mystmd

fixtures/directives.admonitions.md
src/directives/admonition.ts
src/directives/figure.ts
src/directives/index.ts
src/directives/options.ts
src/directives/types.ts
src/index.ts
src/math.ts
src/roles/default.ts
src/roles/generic.ts
src/roles/html.ts
src/roles/index.ts
src/roles/math.ts
src/roles/references.ts
src/roles/types.ts

Allows better extension points for new directives, and is clearer what information is coming in from where.
This follows the same language conventions as RST. See for example https://docutils.sourceforge.io/docs/ref/rst/directives.html#admonitions

✨  NEW: Options and Argument typing in directives

---

fixtures/directives.math.md
index.html
src/blocks.ts
src/directives/admonition.ts
src/directives/default.ts
src/directives/figure.ts
src/directives/index.ts
src/directives/math.ts
src/directives/options.ts
src/directives/types.ts
src/directives/utils.ts
src/roles/index.ts
tests/fixtures.spec.ts

Now supports *not* parsing the internals of a directive, which is helpful for things like `math` directives.
Supported by the `skipParsing` option on the directive.

✨ NEW: Fence directives

---

fixtures/directives.math.md
src/directives/figure.ts
src/directives/index.ts
src/directives/math.ts
src/directives/types.ts
src/roles/references.ts
src/state.ts

This falls back to and uses `name` internally for references. The `math` directive picks up on labels and uses that as the target name.
Also adds an `autoNumber` to the directives, which is on for figures.

🐛 FIX: Name/label internal confusion

---

src/index.ts
src/myst.ts

The default `{ MyST }` export wasn't working with rollup.

🐛 BUG: Fix exports

---

src/mdast/tokensToMyst.ts
src/mdast/transforms.ts

Ensure that the caption transforms are always run. The caption must have a single paragraph child.

✨  NEW: Captions have paragraphs

---

src/mdast/state.ts
src/mdast/transforms.ts
tests/transforms/addenumerators.spec.ts
tests/transforms/addenumerators.yml

~Enumerator value is still saved on the state for reference resolution etc. but now it may be left off the target node.~
3 options to disable heading, figure, and equation enumeration. If enumeration is disabled, numbered references will not be resolved.

Add option to not update enumerator values when counting targets

---

src/mdast/transforms.ts
tests/transforms/converthtml.spec.ts
tests/transforms/converthtml.yml

This pr only affects the `convertHtmlToMdast` transform. Markdown documents may have small html snippets inside them, e.g.:
```
Here is a break<br />in the middle of a paragraph.
```
When we convert these snippets to mdast, however, they are treated as full html documents, in which `html-util-to-mdast` strips leading/trailing `<br />` breaks. https://github.com/syntax-tree/hast-util-to-mdast/blob/50eda792602f44a6576226a4c14143c5fafb0c63/lib/all.js#L26-L44
This PR adds an option to `keepBreaks` which bypasses the underlying break behavior and directly translates `<br />` to a mdast `break` node. By default, `keepBreaks` is true.

🧱 Handle html breaks within markdown text

---

src/mdast/transforms.ts

I was running into all sorts of bugs when I was running this on the jupyter-book documentation, this is one of them. I couldn't trace it down, but this seems to be equivalent.

Move from node to index lookup

---

package-lock.json
package.json
src/myst.ts
tests/colonFences.spec.ts

This bumps `markdown-it-docutils` to v0.1.5 and adds a sanity test.
See #54

Parse colon fences

---

packages/tsconfig/base.json

This fixes typescript build errors in downstream packages.

👩‍🔬 Update lib in tsconfig

---

.changeset/shaggy-peaches-thank.md
packages/jtex/src/jtex.ts

This allows external sessions to override the API_URL of the jtex session, previously a new session would be provided for each time a `jtex` instance was created.

🐛 Incorrect session URL used in jtex

---

packages/citation-js-utils/package.json
packages/jtex/package.json
packages/mystjs/README.md
packages/mystjs/docs/Makefile
packages/mystjs/package.json

This fixes a downstream packaging issue with mystjs to allow it to work in an easier way with jest.

Include a bundle for mystjs that works with jest

---

.changeset/breezy-candles-pull.md
docs/creating-pdf-documents.md
docs/external-references.md
packages/myst-cli/src/process/mdast.ts
packages/myst-transforms/docs/_toc.yml
packages/myst-transforms/docs/index.md
packages/myst-transforms/docs/links.md
packages/myst-transforms/src/links/github.spec.ts
packages/myst-transforms/src/links/github.ts
packages/myst-transforms/src/links/index.ts

Extends the links transformers to recognize github file links.
This is a start of github integration in the themes, and was motivated by being able to pull in typescript documentation where these links are generated automatically. This specific integration doesn't require authentication, and is not rate-limited -- github issues and PRs will likely require authentication, and server-side, run-time components.

Add github code-file link previews

---

.changeset/fast-goats-tie.md
packages/myst-cli/src/process/notebook.ts
packages/myst-cli/src/transforms/citations.ts
packages/myst-cli/src/transforms/dois.ts
packages/myst-cli/src/transforms/images.ts
packages/myst-cli/src/transforms/include.ts
packages/myst-cli/src/transforms/links.ts
packages/myst-cli/src/transforms/mdast.ts
packages/myst-cli/src/transforms/outputs.ts
packages/mystjs/src/index.ts
packages/mystjs/tests/linkify.spec.ts
packages/mystjs/tests/myst.spec.ts

This removes the unist exports from mystjs, these were included to get around CJS/ESM issues in jest primarily, and there are better ways to do that!

📦 Deprecate unified exports from mystjs

---

.changeset/late-singers-cross.md
packages/myst-cli/src/config.ts

This was causing errors in the site config when the project points to the same file, it was `''` rather than `'.'`

🐛 Relative paths should be '.' if the same

---

packages/mystjs/README.md
packages/mystjs/index.html
packages/mystjs/myst.ts
packages/mystjs/package.json

This brings back the very simple mystjs demo:
It was broken because we changed from rollup to esbuild, now that is back!

🔙 Bring back myst.min.js for unpackage

---

.changeset/old-pants-nail.md
packages/jtex/docs/template-yml.md
packages/jtex/src/cli/check.ts
packages/jtex/src/download.ts
packages/jtex/src/jtex.ts
packages/jtex/src/validators.ts
packages/jtex/tests/download.spec.ts

Addresses #84 
Files defined in the `template.yml` may now be nested in arbitrary subfolders.
- `template.tex` must still be at the top level of the template directory
- Any other files may be defined with relative unix-style paths
- Folders and wildcard patters are still not allowed in `files`
Example:
```
jtex: v1
...
files:
- template.tex
- logos/logo.png
- styles/myst.sty
```

🗃 Allow template.yml#files to be nested

---

.changeset/twelve-wombats-hear.md
packages/intersphinx/src/intersphinx.ts
packages/myst-cli-utils/src/index.ts
packages/myst-cli-utils/src/isUrl.ts
packages/myst-cli/src/process/citations.ts
packages/myst-cli/src/process/intersphinx.ts
packages/myst-cli/src/project/load.ts
packages/myst-cli/src/transforms/images.ts
packages/myst-cli/src/utils/index.ts
packages/myst-cli/src/utils/isUrl.ts

Centralize, improve and re-use this utility.

🖇 Move isUrl utility to `myst-cli-utils`

---

package-lock.json
packages/myst-cli/package.json
packages/myst-frontmatter/package.json
packages/myst-transforms/package.json

This improves doi-lookups from a number of sources, and changes the `validate` logic slightly to be more sensible.
Diff:
https://github.com/curvenote/doi-utils/compare/v1.0.4...v1.0.6

🆙 Upgrade doi-utils

---

.changeset/giant-gifts-raise.md
packages/myst-cli/src/process/myst/directives.ts

This is currently a hack in the directives folder, which needs a lot of love, but adds some basic compatibility for working with Quarto documents.

📒 Support basic callouts that use `*.qmd` syntax

---

.changeset/angry-maps-clean.md
docs/dropdowns-cards-and-tabs.md
packages/myst-cli/src/process/myst/directives.ts
packages/myst-spec-ext/src/types.ts

This is tracking some improvements made to tabs and adds the `selected` property to allow you to open a tag to a certain area. The UI is shown here:
https://curvenote.github.io/theme-base/?path=/story/components-tabs--semi-synced-tabs
I have also moved the `spec-ext` type definition to the appropriate place for now.

🗂 Document tab behaviour

---

.changeset/cold-yaks-fail.md
packages/myst-cli/src/store/types.ts
packages/myst-cli/src/utils/addWarningForFile.ts
packages/myst-cli/src/utils/logMessagesFromVFile.ts

This improves the format and error capture (e.g. node position).
Previously the entire message was red, this dims and indents the "note" and "see also" information for a log message.

☢️ Improve warning formatting

---

packages/myst-cli/src/build/site/start.ts
packages/myst-cli/src/session/session.ts
packages/myst-cli/src/session/types.ts
packages/myst-transforms/src/caption.ts

This fixes a downstream compatibility bug, `reload` was already being used!

🐛 Change reloadConfigs --> reload

---

packages/myst-cli/src/build/tex/single.ts

This fixes up inline DOI citations for tex/pdf exports. It is using the `cache.$citationRenderers` to write the bibtex, instead of just copying existing bibtex files (inline DOIs did not have existing bibtex files).
It's still a little klugey: we are using `renderer.cite._graph.find((item) => type === '@biblatex/text').data` (i.e. the raw text input data), rather than rebuilding the bibtex item based on structured citation data found directly on `renderer.cite`.

✍️ Write bibtex from citation renderers in tex export

---

.changeset/thirty-spies-yawn.md
packages/myst-frontmatter/src/frontmatter/validators.ts
packages/myst-frontmatter/tests/exports.yml

Exports could previously defined as:
```yaml
export: pdf
```
But not:
```yaml
export:
- pdf
- docx
```
This fixes up and allows the second case!

📑 Define exports as a single string

---

.changeset/breezy-otters-trade.md
.changeset/tender-stingrays-learn.md
packages/jtex/src/cli/check.ts

This now shows an error on yaml validation to the console rather than eating it! Also allows `myst: v1` to be defined in the template.

🐛 Show yaml errors for jtex and allow `myst: v1`

---

.changeset/forty-pillows-retire.md
.changeset/ninety-ducks-reflect.md
.changeset/young-spies-hunt.md
package-lock.json
packages/myst-cli/package.json
packages/myst-cli/src/build/tex/single.ts
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/process/myst/directives.ts
packages/myst-cli/src/process/notebook.ts
packages/myst-cli/src/transforms/code.spec.ts
packages/myst-cli/src/transforms/code.ts
packages/myst-cli/src/transforms/embed.ts
packages/myst-cli/src/transforms/images.ts
packages/myst-cli/src/transforms/index.ts
packages/myst-transforms/src/basic.ts
packages/myst-transforms/src/blocks.ts
packages/myst-transforms/src/enumerate.ts
packages/myst-transforms/src/frontmatter.spec.ts
packages/myst-transforms/src/frontmatter.ts

- Pull `metadata` from notebook cells onto blocks
- Pull metadata defined in `code` nodes onto blocks
- Use labels in that metadata to add block-level targets
- Add `embed` directive which pulls labeled nodes directly into the page

🛏 Embed notebook cells in a page

---

.changeset/fair-ravens-grab.md
docs/_toc.yml
docs/installing.md
docs/interactive-notebooks.ipynb
docs/quickstart-myst-documents.md
docs/quickstart-myst-markdown.md
docs/quickstart-myst-websites.md
docs/quickstart.md
packages/myst-cli/src/cli/clirun.ts
packages/myst-cli/src/cli/index.ts
packages/myst-cli/src/cli/init.ts
packages/myst-cli/src/process/site.ts

📖 Improve the quickstart tutorials

---

.changeset/few-beers-shop.md
.changeset/sweet-colts-vanish.md
packages/myst-cli/src/build/docx/single.ts
packages/myst-cli/src/build/tex/single.ts
packages/myst-cli/src/build/utils/getSingleFileContent.ts
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/process/site.ts
packages/myst-cli/src/transforms/images.ts
packages/myst-cli/src/transforms/outputs.ts
packages/myst-to-docx/src/schema.ts
packages/myst-to-tex/src/container.spec.ts
packages/myst-to-tex/src/container.ts
packages/myst-to-tex/src/index.ts

#143 added the ability to embed output images and other blocks from one page into another with `embed`, `image`, or `figure` directives. However, for static PDF/docx exports, we were only processing a single page, so references to content on other pages did not resolve.
Now, we process all files in a project even for single page exports. While `crossReference` links still don't work (since the target page doesn't exist), `embed` content now works (since it is pulled from the target page onto the exported page).
Furthermore, notebook `outputs`, which previously only worked in a web context, are now converted to static `images` or `code` for rendering in a static document. Rich HTML outputs still are not supported, but simple image/text outputs are.

📤 Support embeded cross references and output images/text in file exports

---

.changeset/friendly-dodos-think.md
.changeset/stupid-steaks-perform.md
packages/myst-cli/src/build/tex/single.spec.ts
packages/myst-cli/src/build/tex/single.ts
packages/myst-to-docx/src/schema.ts
packages/myst-to-tex/src/index.ts

This addresses #161 - When using the `include` directive, a new node of `type: include` is added to the document AST. However, this node type was simply ignored by `myst-to-tex` and `myst-to-docx`, so it's children disappeared 😱
This PR simply tells `myst-to-tex` and `myst-to-docx` to render the children of `include` nodes.

📄 Render include node children during tex/docx export

---

packages/myst-cli/src/build/utils/getSingleFileContent.ts

Since we are now loading the whole project for single file exports, there are problems if no `project` config exists in a `myst.yml`:
With the change in this PR, there is a warning about no `project` but it still exports:

📤 Implicitly initialize project to resolve single file export cross references

---

.changeset/mighty-olives-tie.md
packages/myst-frontmatter/src/frontmatter/types.ts
packages/myst-frontmatter/src/frontmatter/validators.ts

Support for validation to match the new types. subtitle and short_title are now available for the project and site.

🐛 Validate subtitle & short_title on project/site

---

.changeset/wicked-mayflies-drum.md
packages/myst-cli/src/build/site/watch.ts
packages/myst-cli/src/process/site.ts
packages/myst-cli/src/project/load.ts

During site build, the project structure was never reloaded. This means changes to `_toc.yml` were not picked up, nor were new `bib` files.
This PR causes project to be reloaded in these two cases so changes to `_toc.yml` are reflected in the site structure and new `bib` files are consumed.
Resolves #157

💥 Reload project on toc change, new bib files

---

.changeset/dull-kings-boil.md
.changeset/eighty-mugs-care.md
package-lock.json
packages/myst-cli/package.json
packages/myst-cli/src/build/utils/getSingleFileContent.ts
packages/myst-cli/src/process/file.ts
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/process/notebook.ts
packages/myst-cli/src/process/site.ts
packages/myst-cli/src/transforms/dois.ts
packages/myst-cli/src/transforms/outputs.ts

- Text output now shows up in pdf/word exports
- To get to this, we are now able to pass `maxCharacters` down to `nbtx` - for exports, we set this to `0`, so all outputs, no matter the size are temporarily minified to a separate file. Web outputs still keep the default `maxCharacters` to prevent excessive loading of tiny little minified files...
- Small tweak to doi counting so logs are slightly better during async loading...

📤 Get text output working in exports

---

.changeset/wet-seas-battle.md
packages/myst-transforms/src/html.ts

This PR upstreams the functionality implemented here to be default in `myst-transforms`: https://github.com/executablebooks/jupyterlab-mystjs/pull/36

💬 Add comment to default html-to-mdast handlers

---

.changeset/bright-buckets-kneel.md
.changeset/funny-actors-carry.md
.changeset/loud-paws-learn.md
.changeset/tasty-mugs-love.md
.changeset/thirty-cherries-brake.md
docs/admonitions.md
docs/blocks.md
docs/code.md
docs/diagrams.md
docs/dropdowns-cards-and-tabs.md
docs/typography.md
packages/markdown-it-myst/src/directives.ts
packages/markdown-it-myst/tests/directives.spec.ts
packages/myst-directives/src/admonition.ts
packages/myst-directives/src/figure.ts
packages/myst-spec-ext/src/types.ts
packages/myst-transforms/src/admonitions.spec.ts
packages/myst-transforms/src/admonitions.ts
packages/myst-transforms/src/basic.ts
packages/myst-transforms/src/index.ts

This improves the documentation around the admonitions and adds explicit support for github and quarto-style admonitions.
Slightly nicer explainer I think:
Both of these work, but not yet in the demo (needs a release!)

Improve admonitions to support GitHub and Quarto

---

.changeset/hip-kids-collect.md
packages/markdown-it-myst/src/roles.ts
packages/markdown-it-myst/tests/roles.spec.ts

Should be a small change, allowing whitespace around role names: `{ my_role }` - but it does change regex, which always feels a little risky.

◻️ Allow whitespace around role name inside brackets

---

.changeset/sharp-cars-develop.md
packages/myst-cli/src/transforms/images.ts
packages/myst-cli/src/utils/imagemagick.ts
packages/myst-cli/src/utils/inkscape.ts

Currently this only converts EPS -> PNG. Other conversion requires inkscape which has a CLI bug loading EPS files: https://gitlab.com/inkscape/inkscape/-/issues/3524
There is a bunch of commented code we can revive it that issue gets resolved. We can also just delete the commented code and not worry about until EPS -> PNG becomes a problem...
I also tested some other PDF/SVG conversions and they seem to work as expected.

🎆 Update image conversion transform to handle EPS images

---

.changeset/pink-cups-flow.md
packages/tex-to-myst/src/refs.ts
packages/tex-to-myst/tests/links.yml
packages/tex-to-myst/tests/refs.yml

Parsing latex `Figure \ref{fig:...}` resulted in `Figure _Figure 1_`. Now it correctly inserts `Figure _1_`.
To insert `_Figure 1_` you can still use `\autoref` in the latex.

#️⃣ tex-to-myst: Only insert figure number for latex \ref

---

docs/accessibility-and-performance.md
docs/background.md
docs/code.md
docs/commonmark.md
docs/creating-pdf-documents.md
docs/creating-word-documents.md
docs/external-references.md
docs/frontmatter.md
docs/math.md
docs/syntax-overview.md
docs/typography.md

Found via `typos --format brief` and `codespell docs`.

🐛 Fix typos in docs

---

.changeset/cuddly-cows-live.md
.changeset/cuddly-turkeys-invite.md
.changeset/fresh-numbers-sit.md
.changeset/fuzzy-frogs-joke.md
.changeset/ten-boats-give.md
packages/tex-to-myst/src/frontmatter.ts
packages/tex-to-myst/src/misc.ts
packages/tex-to-myst/src/tables.ts
packages/tex-to-myst/src/tex.ts
packages/tex-to-myst/tests/tables.yml

- basic implementation of `renewcommand` (same as `newcommand` except no warning on override)
- multiple `\title` values warn
- `adjustbox`, `makecell`, `textwidth`, `onecolum` all pass without warnings

Small improvements to latex support

---

.changeset/serious-ducks-sip.md
package-lock.json
packages/myst-cli/package.json
packages/myst-cli/src/transforms/citations.ts
packages/myst-cli/src/transforms/dois.ts
packages/myst-roles/package.json
packages/myst-roles/src/cite.ts
packages/myst-spec-ext/src/types.ts
packages/myst-to-docx/src/schema.ts
packages/tex-to-myst/package.json
packages/tex-to-myst/src/citations.ts

Refactors and brings the cite nodes into a more visible place.

👩‍🔬 Add cite nodes to myst-spec-ext

---

.changeset/thin-keys-rest.md
packages/myst-transforms/src/frontmatter.spec.ts
packages/myst-transforms/src/frontmatter.ts

Stops a bug from crashing the editor when frontmatter loads to be undefined.

🐛 Load an undefined YAML frontmatter

---

.changeset/early-carpets-sleep.md
.changeset/violet-shrimps-greet.md
packages/myst-cli/src/build/site/watch.ts
packages/myst-cli/src/process/site.ts
packages/myst-cli/src/store/reducers.ts
packages/myst-cli/src/store/selectors.ts
packages/tex-to-myst/src/misc.ts
packages/tex-to-myst/src/parser.ts
packages/tex-to-myst/src/refs.ts
packages/tex-to-myst/src/tables.ts

This attempts to address https://github.com/executablebooks/mystjs/issues/266 (though the repeated site build is difficult to reliably reproduce, so we will see if this helps over time).
This PR starts by adding a simple check: `If we are currently reprocessing and a new reprocess is requested, do not reprocess again.`
However, so intentional changes are not lost, we need one more step: `If we are currently reprocessing and a new reprocess is requested, do not reprocess again right away, but *do* reprocess one more time when we are done.`
As we start considering more and more simultaneous reprocess requests, it gets harder to keep track of what exactly needs to be processed. For example, while reprocessing `file1`, if requests to reprocess `file2` and `file3` do we keep track of all of …

Prevent rebuild loop

---

docs/cross-references.md
docs/math.md

This PR starts to add a few admonitions that indicate where syntax is not in the MyST spec. I think the idea here would be that over time we make MEPs to introduce this syntax, and we gradually remove the warnings :)
Thoughts?

docs: add warning about spec

---

.changeset/nasty-mayflies-accept.md
packages/jtex/src/cli/check.ts

When using `jtex check --fix` both `myst: v1` and `jtex: v1` were written to `template.yml`. We are moving to only use `myst: v1` and not write `jtex: v1` since not all templates are for `tex` ("jtex" on a docx template is maybe confusing).

🔧 Write only 'myst: v1' not 'jtex: v1' in template.yml

---

.changeset/lucky-numbers-brake.md
packages/myst-to-tex/src/index.ts
packages/myst-to-tex/src/utils.ts
packages/myst-to-tex/tests/basic.yml

This attempts to address #297 by escaping some special characters in latex hrefs.
I only escape basic latex characters; we don't want to accidentally replace a character with a latex macro. It is likely not perfect, but common characters like `#` and `_` are now no problem.

💱 Escape basic characters in latex href

---

packages/myst-transforms/src/frontmatter.spec.ts
packages/myst-transforms/src/frontmatter.ts

Fixes #281 maybe?
@rowanc1 I have no idea if someone needs this behavior. Obviously it could be controlled by a switch. For me it seems wrong to dig beyond the first H1 though.

🏗 Stop hoisting deep headings into frontmatter title

---

.changeset/happy-hornets-impress.md
.changeset/hot-chicken-sniff.md
docs/typography.md
packages/myst-parser/src/tokensToMyst.ts
packages/myst-parser/tests/tasklists.spec.ts
packages/myst-spec-ext/src/types.ts
packages/myst-transforms/src/blocks.ts

This parses tasklists into an AST, previously they were going in as HTML. This adds a `checked` property to the AST.

✅ Parse tasklists to an AST

---

.changeset/late-months-talk.md
packages/myst-to-tex/src/utils.ts

LaTeX commands gobble the following space, so this solution is safe https://texfaq.org/FAQ-xspace
See #199

© Copyright symbol must have trailing whitespace

---

.changeset/calm-llamas-fly.md
packages/myst-to-jats/src/frontmatter.ts
packages/myst-to-jats/tests/article.yml

For example:
```xml
<title-group>
<article-title>
Systematic review of day hospital care for elderly people
</article-title>
</title-group>
```
See https://jats.nlm.nih.gov/archiving/tag-library/1.3/element/article-title.html

🏷 Add title/subtitle to JATS

---

.changeset/forty-pugs-drop.md
.changeset/olive-pianos-film.md
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/process/site.ts
packages/myst-cli/src/transforms/embed.ts
packages/myst-cli/src/transforms/types.ts
packages/myst-directives/src/embed.ts
packages/myst-parser/tests/directives/embed.yml

`figure`/`embed` directives may embed code/output cells from other notebooks. To recompute these, we need to know where they come from.
This PR adds url `source` and `sourceKey` to all embed nodes to locate the source notebook cell. This also adds `dependencies` at the top level of the page config with all url sources required to compute embedded content in the page.

📒 Track notebook source for embedded content

---

.changeset/shiny-windows-knock.md
.changeset/warm-oranges-reply.md
packages/citation-js-utils/src/index.ts
packages/myst-cli/src/build/jats/single.ts
packages/myst-to-jats/src/backmatter.ts
packages/myst-to-jats/src/index.ts
packages/myst-to-jats/src/types.ts
packages/myst-to-jats/tests/basic.spec.ts
packages/myst-to-jats/tests/citations.yml

Currently this handles basic journal citations. It will need a bit of expanding for other citation types. We could also move some of this handling to `citation-js-utils` so all the cite transformations / exports are centralized there...?
For now, though, I think this is a nice placeholder start.

👩‍🎓 Add bibliography to JATS export backmatter

---

.changeset/neat-flowers-laugh.md
packages/myst-cli/src/build/site/manifest.ts
packages/myst-frontmatter/src/frontmatter/frontmatter.spec.ts
packages/myst-frontmatter/src/frontmatter/types.ts
packages/myst-frontmatter/src/frontmatter/validators.ts
packages/myst-frontmatter/tests/examples.spec.ts
packages/myst-frontmatter/tests/thebe.yml

The `thebe`, `thebe-core` & `thebe-react` libraries accepts a number of options allowing connections to compute resources and rendering options to be configured. 
These options are currently documented [here](https://thebe-core.curve.space/docs-core/a-configuration) and [here](https://thebe-core.curve.space/docs-core/coreoptions).
This PR adds support for including these options in project frontmatter with the associated validation.

💻 Extending project frontmatter to accept `thebe` options

---

packages/myst-transforms/src/links/plugin.ts
packages/myst-transforms/src/links/wiki.spec.ts
packages/myst-transforms/src/links/wiki.ts

This fixes https://github.com/executablebooks/mystjs/issues/224 (maybe in a bit hacky way).
The wiki link string was being manipulated by adding zero width space by https://github.com/executablebooks/mystjs/blob/8615f221874abb8542176ceeb0e8f8e2da42777e/packages/myst-transforms/src/links/plugin.ts#L20 
which in turn messed up updates to the text.
Also fixed a regex, so `The_big_bang_theory`, correctly transforms to `The big bang theory` and not `The big_bang_theory`.

🐛 Transform Wikipedia links properly

---

.changeset/grumpy-dingos-thank.md
.changeset/tough-ties-punch.md
packages/tex-to-myst/src/basic.ts
packages/tex-to-myst/src/characters.ts
packages/tex-to-myst/src/utils.ts
packages/tex-to-myst/tests/characters.yml

This allows LaTeX parsing of `{\c S} --> Ş`, and any other accents.

Ş Allow characters in groups

---

.changeset/new-months-ring.md
packages/myst-transforms/src/enumerate.ts

⌨️ No-break space for cross-references

---

.changeset/eight-islands-decide.md
packages/myst-cli/src/process/mdast.ts

Traced a bug in not having the webp images show up back to this!

🐛 Await all extra transforms to be completed

---

.changeset/dirty-dolls-pull.md
.changeset/great-mugs-grow.md
.changeset/heavy-impalas-hammer.md
.changeset/tiny-flies-bathe.md
.github/workflows/ci.yml
package-lock.json
packages/jats-to-myst/package.json
packages/myst-cli/tests/outputs/basic-md-and-config.xml
packages/myst-to-jats/package.json
packages/myst-to-jats/src/backmatter.ts
packages/myst-to-jats/src/frontmatter.ts
packages/myst-to-jats/src/index.ts
packages/myst-to-jats/tests/article.yml
packages/myst-to-jats/tests/basic.spec.ts
packages/myst-to-jats/tests/citations.yml
packages/myst-to-jats/tests/multi.yml

This also fixes up a few instances of previously-invalid JATS XML including:
- `contrib-group` now wraps contribs
- `front` with `article-meta` is always present
- `element-citations` are never empty
Also this PR adds XML declaration and doctype headers.

🧐 Add JATS DTD validation to myst-to-jats tests

---

.changeset/brave-worms-provide.md
.changeset/purple-needles-unite.md
packages/myst-cli/src/build/build.ts
packages/myst-cli/src/cli/build.ts
packages/myst-cli/src/cli/options.ts

This allows us to directly specify the output from the CLI, it only allows you to have a single file if you are specifying the output. It also infers the export type and turns on `--force`.
```
myst build example.ipynb -o example.xml
```

🤖 Specify output from the command line

---

.changeset/breezy-tomatoes-itch.md
.changeset/nice-geese-speak.md
packages/myst-spec-ext/src/types.ts
packages/myst-to-jats/src/index.ts
packages/myst-to-jats/tests/article.yml
packages/myst-to-jats/tests/basic.yml
packages/myst-transforms/src/footnotes.ts

This improves some minor things for jats validation (nesting in paragraphs mostly!!).

🧪 JATS Validation

---

.changeset/cyan-rice-burn.md
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/transforms/index.ts
packages/myst-cli/src/transforms/inlineExpressions.ts
packages/myst-roles/src/index.ts
packages/myst-roles/src/inlineExpression.ts
packages/myst-spec-ext/src/types.ts
packages/myst-to-jats/src/backmatter.ts
packages/myst-to-jats/src/index.ts
packages/myst-to-jats/src/inlineExpression.ts
packages/myst-to-jats/src/types.ts

This supports the eval role in jupyterlab_myst in the CLI and exporting out to formats like JATS, docx, tex, and word for a subset of mimetypes. Lots of work still to expand support for other mimetypes, but a good start!

🧮 Inline user_expression support

---

docs/integrating-jupyter.md

the docs now build without any warnings from the `integrating-jupyter` page

📖 Documentation fixes for `thebe`

---

.changeset/gentle-trains-raise.md
packages/myst-cli/src/utils/imagemagick.ts

This fixes some oddities in dealing with imagemagik for layered graphics. Here we only take the first layer. I saw this mostly in working with EPS files from authors.

🌃 Update images for capturing nested layers

---

packages/myst-cli/src/process/site.ts
packages/myst-cli/src/transforms/images.ts
packages/myst-cli/src/utils/resolveExtension.ts
packages/myst-spec-ext/src/types.ts

This is a baby step towards other types of embedding! cc @choldgraf @kolibril13, you can now `![](my-video.mp4)`
See #275, #246

📺 Add videos to work with figures and images

---

.changeset/fluffy-countries-search.md
packages/myst-directives/src/figure.ts

This is a step towards better sub-figure support. Currently you can add a figure that now includes images as the first-children of the directive, this will skip putting those as the caption, and look for non-image nodes for the caption.

🌉 Allow for multiple images in a single figure

---

.changeset/eleven-monkeys-sell.md
.changeset/rare-snakes-rule.md
docs/_toc.yml
docs/glossaries-and-terms.md
docs/glossary.md
packages/myst-cli/src/process/mdast.ts
packages/myst-common/src/utils.ts
packages/myst-directives/src/glossary.ts
packages/myst-directives/src/index.ts
packages/myst-roles/src/index.ts
packages/myst-roles/src/term.ts
packages/myst-transforms/src/enumerate.ts
packages/myst-transforms/src/glossary.ts
packages/myst-transforms/src/index.ts

Adds support for glossary directive and term roles.

🕵🏽‍♀️ Add glossary and term support

---

packages/jats-to-myst/src/index.ts
packages/myst-parser/src/tokensToMyst.ts
packages/myst-parser/tests/myst.spec.ts
packages/myst-to-docx/src/schema.ts
packages/myst-to-html/src/schema.ts
packages/myst-to-jats/src/index.ts
packages/myst-to-md/src/misc.ts
packages/myst-to-md/tests/misc.yml
packages/myst-to-tex/src/index.ts

In a future version of the spec, hopefully this is removed. There isn't anything myst-like about the comments.

💬 Remove `mystComment` in favour of `comment`

---

package-lock.json
packages/jats-to-myst/package.json
packages/jats-to-myst/src/index.ts
packages/jats-to-myst/src/transforms/admonitions.ts
packages/jats-to-myst/src/transforms/typography.ts
packages/myst-to-jats/package.json
packages/myst-to-jats/src/index.ts

This fixes some downstream dependencies in using jats in the browser.

📦 Move from `jats-xml` --> `jats-tags`

---

packages/myst-cli/src/process/notebook.ts
packages/myst-cli/src/transforms/embed.ts
packages/myst-common/src/types.ts
packages/myst-to-jats/src/backmatter.ts
packages/myst-to-jats/src/index.ts
packages/myst-to-jats/src/inlineExpression.ts
packages/myst-to-jats/src/transforms/containers.ts
packages/myst-to-jats/src/transforms/sections.ts
packages/myst-to-jats/src/types.ts
packages/myst-to-jats/src/utils.ts
packages/myst-to-jats/tests/basic.yml
packages/myst-to-jats/tests/notebooks.yml

This PR makes a bunch of not-super-nice changes to identifiers before and during JATS export so there are no duplicates in the JATS xml. It also fixes a few picky structural aspects of how the xml was constructed.

🔧 Fixes for JATS validation

---

.changeset/empty-pigs-agree.md
packages/myst-transforms/src/links/myst.ts

This allows you to also link using `myst:jtex` as a bare link without a target.

🔗 Improve intersphinx linking

---

.changeset/eleven-boats-end.md
.changeset/fuzzy-apples-sit.md
packages/jtex/tests/download.spec.ts
packages/myst-frontmatter/bin/fetchLicenses.mjs
packages/myst-frontmatter/src/licenses/licenses.ts
packages/tex-to-myst/src/basic.ts
packages/tex-to-myst/src/chem.ts
packages/tex-to-myst/src/parser.ts
packages/tex-to-myst/src/tex.ts
packages/tex-to-myst/src/verbatim.ts
packages/tex-to-myst/tests/cases.spec.ts
packages/tex-to-myst/tests/verbatim.yml
packages/tsconfig/base.json

See also: https://github.com/executablebooks/myst-theme/pull/128

🕵🏽‍♀️ LaTeX improvements for `\ce` & `listings`

---

.changeset/seven-seas-care.md
packages/myst-transforms/src/liftMystDirectivesAndRoles.ts

This fixes a bug which was introduced when we changed the order of propogating myst `(targets)=`, which happened before lifting the directives and roles. This now adds the identifiers back onto the first directive/role child.

🐛 Identifiers added to directive child

---

.changeset/five-numbers-invent.md
docs/cross-references.md
packages/myst-cli/src/transforms/links.ts
packages/myst-roles/src/download.ts
packages/myst-roles/src/index.ts

See executablebooks/jupyterlab-myst#158, #189

⤵️ Add {download} role

---

.changeset/dry-poems-repeat.md
packages/myst-cli/src/transforms/outputs.ts
packages/myst-to-tex/src/container.ts
packages/myst-to-tex/src/index.ts
packages/myst-to-tex/src/legends.ts
packages/myst-to-tex/tests/basic.yml

This PR resolves `unknown node type` errors during tex export for `legend` and `output`:
- For `output` - we usually simplify these nodes to other types renderable to tex (e.g. `text`, `image`). However, if the output has no `data`, it was left unchanged. Now, when we encounter these empty output nodes, they are simply removed during the simplification step.
- For `legend` - we now combine this with the corresponding `caption` node and pass it to tex as a multi-paragraph caption

🧹 Fix myst-to-tex legend and output node errors

---

.changeset/loud-weeks-jam.md
packages/myst-cli/src/build/site/manifest.ts
packages/myst-cli/src/process/site.ts

Previously exports in the `config.json` site file were just copied straight from the original frontmatter. This pr updates the exports to include filename/url, like we do for page-level exports:

📤 Put url/filename on project exports in site config

---

.changeset/five-years-collect.md
.changeset/tall-bobcats-worry.md
package-lock.json
packages/jats-to-myst/package.json
packages/jtex/package.json
packages/myst-templates/package.json
packages/myst-templates/src/download.ts

This should address https://github.com/myst-templates/docx_default/issues/1
Same change we made here: https://github.com/curvenote/jats/pull/19 
---
Also this switches site template download from `git clone` to admzip. Before we needed a clone in order to pick up submodules. Now, though, the templates are bundled nicely and can simply be downloaded. Hopefully fixes: https://github.com/executablebooks/mystmd/issues/209
Note - it would be good to update the myst-templates API to have zip urls for site templates, not git, but for now, we construct zip from git.

🤐 Use adm-zip to unzip templates, not unzipper

---

.changeset/stupid-llamas-rest.md
packages/myst-to-jats/src/transforms/containers.ts
packages/myst-to-jats/tests/basic.yml

Simplifying the structure of embedded figures in #477 broke the transform to add `supplementary-material` in JATS export. However, it did fix the ordering of captions and content in figures to address #471...
This PR revives the `supplementary-material` in JATS and in turn resolves #471 I believe.

🔧 Fix supplementary material in jats export

---

packages/tsconfig/base.json

This is a pretty simple change that enables the packages (esp `myst-cli-utils`) to build when part of a larger (deeper) monorepo

🔍 allow myst to build in larger parent monorepos

---

.changeset/short-mugs-bathe.md
packages/myst-cli/src/build/meca/index.ts

This simple filter on the glob matches should resolve #465 - all files are copied with recursive paths anyway, so there is no need to copy folders.

📂 Do not log errors on copying folders in meca bundle

---

.changeset/calm-crews-sort.md
.changeset/wicked-beds-deliver.md
package-lock.json
packages/myst-cli-utils/src/filesystem.ts
packages/myst-cli-utils/src/index.ts
packages/myst-cli/src/build/meca/index.ts
packages/myst-cli/src/project/fromPath.ts
packages/myst-cli/src/project/load.ts
packages/myst-cli/src/utils/getAllBibtexFiles.ts
packages/myst-cli/src/utils/index.ts
packages/myst-cli/src/utils/isDirectory.ts
packages/myst-cli/src/utils/resolveExtension.ts
packages/myst-templates/package.json
packages/myst-templates/src/download.ts
packages/myst-templates/src/validators.ts

We changed site template fetching from clone to download/unzip. However, the unzipping function wasn't copying required template files.
This PR updates the site template download to copy all `files` listed on the template yml (which may use glob patterns). This functionality requires updates to site templates here: https://github.com/executablebooks/myst-theme/pull/178

Copy site template files (using glob)

---

.changeset/empty-days-invent.md
.changeset/lazy-seas-begin.md
packages/myst-config/src/project/validators.ts
packages/myst-frontmatter/src/frontmatter/frontmatter.spec.ts
packages/myst-frontmatter/src/frontmatter/types.ts
packages/myst-frontmatter/src/frontmatter/validators.ts
packages/myst-frontmatter/tests/examples.spec.ts
packages/myst-frontmatter/tests/thebe.yml

- Alias for option `thebe` of `jupyter` #473
- Allows for { jupyter: lite }
This is a start at #463.
**Future work:**
- remove the `boolean | Object` from the binder and server options. We should be explicit in the CLI.
- Update the docs should happen in #463

🛠 Allow jupyter as alias for thebe

---

.changeset/clean-toys-occur.md
.changeset/nasty-foxes-jog.md
packages/myst-cli/src/build/site/manifest.ts
packages/myst-cli/src/transforms/images.ts
packages/myst-frontmatter/src/frontmatter/types.ts
packages/myst-frontmatter/src/frontmatter/validators.ts

This adds a thumbnail to the project manifest (if it doesn't already exist) using the index page thumbnail.

🎑 Add thumbnail to project manifest

---

.changeset/tiny-spoons-itch.md
packages/myst-cli/src/session/session.ts
packages/mystmd-py/.gitignore
packages/mystmd-py/LICENSE
packages/mystmd-py/MANIFEST.in
packages/mystmd-py/mystmd_py/main.py
packages/mystmd-py/scripts/pypi-deploy.sh
packages/mystmd-py/setup.cfg
packages/mystmd-py/setup.py

This introduces a new package that allows deploying `myst` to PyPI, so we can install with:
```
pip install mystmd
```
In order for this to work, users must have node installed. If they do not, they get a warning, like:
If node is installed, the `myst` python library passes all commands/arguments directly through to the JS CLI:

🐍 Add pypi deploy for myst

---

.changeset/long-boxes-yell.md
packages/myst-common/src/extractParts.spec.ts
packages/myst-common/src/extractParts.ts

Previously it only worked on "part" and now it works on either.
We also update the block data to show the part used.

🏷 Extract tagged parts

---

.changeset/tough-ghosts-raise.md
docs/admonitions.md
packages/myst-transforms/src/admonitions.spec.ts
packages/myst-transforms/src/admonitions.ts

See https://github.com/orgs/community/discussions/16925
Support for:
```
> [!NOTE]
> Highlights information that users should take into account, even when skimming.
> [!IMPORTANT]
> Crucial information necessary for users to succeed.
> [!WARNING]
> Critical content demanding immediate user attention due to potential risks.
> **Note**
> This is a note
> **Warning**
> This is a warning
```

✅ Support for new GitHub admonitions

---

docs/exercises.md

The reference label needs to be inside the `{numref}` backtick element.

Fix custom numref labels

---

.changeset/strong-ducks-appear.md
packages/myst-transforms/src/basic.ts
packages/myst-transforms/src/math.spec.ts
packages/myst-transforms/src/math.ts

See executablebooks/MyST-Parser#798
@njzjz, saw your issue on MyST-Parser -- wasn't aware of this for GFM! This is addressing your issue in the javascript client + mystmd CLI.

🧮 Math code blocks for GitHub Flavored Markdown

---

.changeset/khaki-poems-hunt.md
docs/diagrams.md
packages/myst-transforms/src/basic.ts
packages/myst-transforms/src/code.ts
packages/myst-transforms/src/math.spec.ts
packages/myst-transforms/src/math.ts

This supports a raw `mermaid` block in the same way as github and (soon!) JupyterLab. See jupyter/enhancement-proposals#101.
````
```mermaid
flowchart LR
chicken --> egg --> chicken
```
````
Which renders as:
```mermaid
flowchart LR
chicken --> egg --> chicken
```

🧜‍♀️ Support mermaid as a code block

---

.changeset/silver-spoons-shake.md
packages/myst-cli/src/transforms/code.spec.ts
packages/myst-cli/src/transforms/code.ts

See #268
This allows for a `#| label:` to come after an ipython magic command, but still requires them to be at the top of the cell.

🏷 Support ipython magic for label syntax

---

.changeset/silver-bobcats-rush.md
packages/myst-frontmatter/src/frontmatter/frontmatter.spec.ts
packages/myst-frontmatter/src/frontmatter/validators.ts
packages/myst-frontmatter/tests/affiliations.yml

`crypto` does not play nicely with the browser and we really do not need it here, since we are are only using it for generating a basic unique ID.
Instead, I am just using stringified JSON as the unique ID. This feels super silly - these IDs are really gross looking. However, they only exist in memory for string comparisons, so, in practice, as long as we don't start writing them to file I think it's ok.

🔧 Update generated affiliation ids to not use crypto

---

.changeset/angry-mirrors-draw.md
.changeset/eight-moons-repeat.md
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/process/notebook.ts
packages/myst-cli/src/transforms/images.ts

This PR changes how notebooks are parsed to MyST: Instead of building a single markdown document from the cells and calling `parseMyst` once, each cell is parsed individually, nested into `block` nodes (except frontmatter), and concatenated.
This allows us to run mdast transforms at a notebook-cell level (the only time we have access to cell `attachments`), which we use to replace `![](attachment:...)` image links with the base64 value directly. This base64 image is resolved later in `transformImages` (this functionality already existed prior to this PR).
Finally, we add one additional transform that trims base64 `urlSource` values on image nodes, so huge base64 payloads are not bundled into the mdast data.
Fixes: https://github.com/executablebooks/mystmd/issues/528

📎 Handle base64 notebook cell attachments

---

.changeset/thick-eyes-eat.md
packages/myst-cli/src/transforms/outputs.spec.ts
packages/myst-cli/src/transforms/outputs.ts

This PR should address #549 - now multiple outputs on a single jupyter notebook cell will be persisted in pdf/docx exports.

📤 Keep multiple outputs when reducing outputs for pdf/docx exports

---

.changeset/chatty-forks-kick.md
.changeset/fair-spoons-itch.md
.changeset/gentle-socks-rescue.md
packages/myst-to-jats/src/frontmatter.ts
packages/myst-to-jats/src/index.ts
packages/myst-to-jats/src/types.ts
packages/myst-to-jats/tests/article.yml
packages/myst-to-jats/tests/notebooks.yml

Blocks tagged with `part: 'abstract'` are now respected by JATS export and moved appropriately to `<article-meta><abstract>`.
Resolves #560

👩‍🎓 Extract abstract part for JATS frontmatter

---

.changeset/weak-bats-tell.md
packages/myst-cli/src/transforms/images.ts
packages/myst-cli/src/transforms/links.ts
packages/myst-cli/src/utils/headers.ts
packages/myst-cli/src/utils/index.ts

This should address #563 - imgur was unhappy with no `User-Agent` header. Now these links seem to work fine:

🕵️‍♀️ Add User-Agent to image and link fetches

---

.changeset/shaggy-lemons-admire.md
packages/myst-templates/src/validators.ts

This just allows us to reuse `validateOptionsFunction` with different reserved keys.

👩‍💻 Refactor and export template validation functions

---

.changeset/fifty-pants-remain.md
packages/myst-cli/src/build/utils/getFileContent.ts
packages/myst-cli/src/process/file.ts
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/process/site.ts
packages/myst-cli/src/project/load.ts
packages/myst-cli/src/transforms/embed.ts
packages/myst-cli/src/transforms/types.ts
packages/myst-spec-ext/src/types.ts

Purpose of this PR is to make available the project relative path to the different files within a myst site. 
In particular for notebooks, this allows us to understand the folder structure within which he notebooks are developed and executed, where we make the assumption that a jupyter server would be started at the project root and code within the notebooks would be written relative to that. 
When using thebe for computation the correct relative paths for a notebook is required when starting a jupyter session, in order to correctly allow for explicit loading of files or importing of code from local files.
This PR is an attempt at adding this relative path information at `loadFile` time, so that is can be easily used later when constructing the data structure for the page, as well as …

📌 add relative location to pages and sources

---

.changeset/grumpy-rice-eat.md
.changeset/sweet-dragons-live.md
packages/myst-cli/src/process/file.ts
packages/myst-cli/src/transforms/links.ts

- `selectFile` resolves the input file path
- `checkLink` is exported

🔧 A couple tweaks for consuming the myst-cli package

---

packages/myst-frontmatter/src/frontmatter/frontmatter.spec.ts
packages/myst-frontmatter/src/frontmatter/types.ts
packages/myst-frontmatter/src/frontmatter/validators.ts

This opens up access to other providers (e.g. zenodo) beyond those supported in thebe 0.8.2 by default and is paired with changes to allow custom providers to be specified in thebe here https://github.com/executablebooks/thebe/pull/681

📡 enable custom binder providers in frontmatter

---

.changeset/smooth-pianos-reflect.md
packages/myst-cli/src/transforms/embed.ts
packages/myst-cli/src/transforms/outputs.ts

This PR fixes a bug introduced when we reduced `output` nodes for PDF output to `code` etc. where `remove-input`/`remove-output` flags stopped filtering correctly.

🏷 Tag reduced outputs as data.type.output

---

packages/myst-parser/docs/consuming/advanced.md

`myst-parser` no longer exports the `MyST` object and plain js/ts usage would now be via the `mystParse` function. Docs have been updated to reflect this.

📗 update docs to correct myst parser usage

---

.changeset/wet-jeans-sell.md
packages/myst-frontmatter/src/frontmatter/frontmatter.spec.ts
packages/myst-frontmatter/src/frontmatter/types.ts
packages/myst-frontmatter/src/frontmatter/validators.ts
packages/myst-frontmatter/src/utils/edgecases.yml
packages/myst-frontmatter/src/utils/index.ts
packages/myst-frontmatter/src/utils/parseName.spec.ts
packages/myst-frontmatter/src/utils/parseName.ts
packages/myst-frontmatter/src/utils/realnames.yml
packages/myst-frontmatter/src/utils/testnames.yml
packages/myst-frontmatter/tests/affiliations.yml
packages/myst-frontmatter/tests/authors.yml
packages/myst-frontmatter/tests/credit.yml
packages/myst-frontmatter/tests/orcid.yml

This introduces a new utility to parse `given`, `particle`, `family`, `suffix` from string name (maybe this utility should be split out into a separate library!?). The rules of this parsing attempt to follow bibtex patters as documented here: http://maverick.inria.fr/~Xavier.Decoret/resources/xdkbibtex/bibtex_summary.html#names - I had trouble finding a super-legitimate-feeling source of truth... But if we have a separate library, anyone could update it 🙂 
Anyway - on top of that, users may now specify frontmatter `name` as a string as before or as a `Name` object with the above fields, plus `display`. Then, on validation, this is normalized to `name: string` and `nameParsed: Name`. This means the display `name` is still unchanged, but libraries like `myst-to-jats` can access the …

📇 Support parsed author names and parse string names

---

.changeset/four-spoons-approve.md
.changeset/many-masks-jam.md
packages/myst-cli/src/build/utils/getFileContent.ts
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/process/site.ts

Thumbnails and webp-optimized images are only required for site builds. However, both of these were still processed in JATS/pdf/etc exports.
This PR cleans that up and turns off the webp/thumbnail processing where it is not needed.

🎆 Clean up extra image processing

---

package-lock.json
packages/myst-parser/package.json

`myst-common` is now used in `myst-parser`. This adds it to the dependencies.
Coming from a warning in `jupyterlab-myst`:

📦 Add myst-common to myst-parser

---

.changeset/cold-ghosts-laugh.md
.changeset/moody-months-cheat.md
packages/myst-common/src/types.ts
packages/myst-directives/src/admonition.ts
packages/myst-directives/src/code.ts
packages/myst-directives/src/figure.ts
packages/myst-directives/src/iframe.ts
packages/myst-directives/src/image.ts
packages/myst-directives/src/math.ts
packages/myst-directives/src/table.ts
packages/myst-parser/src/directives.ts
packages/myst-parser/tests/directives/directives.spec.ts
packages/myst-parser/tests/directives/label-alias.yml

You can now use `label` or `name` for all directives

👯‍♀️ Add directive option `alias`

---

.changeset/wise-grapes-tell.md
packages/jtex/package.json
packages/jtex/src/export.ts
packages/jtex/src/imports.ts
packages/jtex/src/jtex.ts
packages/jtex/src/types.ts
packages/myst-cli/src/build/pdf/create.ts
packages/myst-cli/src/build/pdf/utils.ts
packages/myst-cli/src/build/tex/single.spec.ts
packages/myst-cli/src/build/tex/single.ts
packages/myst-cli/src/build/types.ts
packages/myst-cli/src/build/utils/localArticleExport.ts
packages/myst-common/src/index.ts
packages/myst-common/src/utils.ts
packages/myst-to-tex/src/index.ts
packages/myst-to-tex/src/types.ts
packages/myst-to-tex/tests/glossaries.spec.ts
packages/myst-to-tex/tests/glossaries.yml

This is an early review of the changes I made to add support to glossaries.
- Glossary definitions are added in the preamble regardless whether or not they will actually be used (room for improvement).
- Glossary references (cross-reference nodes) are rendered accordingly if a glossary definition is found.
There is an issue. The rendered PDF will have the referred terms correctly rendered, however the final glossary, at the end of the page, will not be shown as explained at [Compiling the Glossary](https://www.overleaf.com/learn/latex/Glossaries) section. We need to trigger this sequence of build commands:
1. Invoke the PDF build command `pdflatex file.tex`
2. Invoke the glossary build command `makeglossaries file`, in the same folder
3. Invoke the PDF build command `pdflatex file.tex` …

Add support for glossary

---

.changeset/cold-weeks-hunt.md
packages/myst-cli/src/build/docx/single.ts
packages/myst-cli/src/build/jats/single.ts
packages/myst-cli/src/build/md/index.ts
packages/myst-cli/src/build/meca/index.ts
packages/myst-cli/src/build/pdf/single.ts
packages/myst-cli/src/build/tex/single.ts
packages/myst-cli/src/build/utils/collectExportOptions.ts
packages/myst-cli/src/build/utils/localArticleExport.ts
packages/myst-cli/src/config.ts

Addresses #625 - turns out the loading functions were erroneously marked as `async`. This pr just gets rid of that and gets rid of any `await`s elsewhere...

🐛 Fix bug with async project/site loading

---

.changeset/sixty-balloons-fix.md
packages/myst-cli/src/build/meca/index.ts
packages/myst-cli/src/build/site/manifest.ts
packages/myst-cli/src/build/utils/collectExportOptions.ts
packages/myst-cli/src/process/intersphinx.ts
packages/myst-cli/src/store/selectors.ts
packages/mystmd/tests/exports.yml
packages/mystmd/tests/no-config/index.md

Hopefully this actually fixes #625 - a few `selectors` were not recognizing that they may have `undefined` results, meaning that case was not handled appropriately. After explicitly adding that return type, type errors were exposed and resolved.
I was able to recreate #625 by simply deleting my `myst.yml` file and trying to build an export; with this fix, that now works fine.

🔧 Fix up undefined types from selectors

---

.changeset/famous-maps-float.md
packages/myst-cli/src/session/session.spec.ts
packages/myst-cli/src/session/session.ts
packages/myst-cli/src/session/types.ts

Cloning a session didn't actually do anything besides create a new session... now, the original session keeps track of its clones. This means we can do things like report all errors/warnings from simultaneous builds using these clones.

🐑 Keep track of session clones for error reporting

---

.changeset/lemon-fireants-love.md
packages/myst-cli/src/build/meca/index.ts

This addresses #611 - if a tex export with a .zip output file is specified, it will be added to the meca bundle as a manuscript.

🤐 Add tex-zip to manuscripts included with meca

---

.changeset/six-bikes-divide.md
packages/myst-cli/src/build/jats/single.ts

This adds aliases for the `plain-language-summary`, now used and parsed by default.
This is necessary for the agu2019 template.

🐛 Add `plain-language-summary` & `summary` parts

---

.changeset/thin-eggs-tie.md
packages/myst-cli/src/build/jats/single.ts
packages/myst-to-jats/src/index.ts
packages/myst-to-jats/src/types.ts
packages/myst-to-jats/tests/basic.spec.ts
packages/mystmd/tests/outputs/basic-md-and-config.xml

This adds new lines in the XML exports, but has zero indentation (previously this was 2 spaces).

🧑‍💻 Create flat XML by default in JATS export

---

.changeset/grumpy-apes-check.md
.changeset/wet-moons-yell.md
docs/integrating-jupyter.md
packages/myst-frontmatter/src/frontmatter/frontmatter.spec.ts
packages/myst-frontmatter/src/frontmatter/frontmatter.thebe.spec.ts
packages/myst-frontmatter/src/frontmatter/types.ts
packages/myst-frontmatter/src/frontmatter/validators.ts
packages/myst-frontmatter/tests/thebe.yml

These changes remove the `local` options for now and change the `server` and default `thebe: true` behaviour to remove the possibility of inadvertently connecting to a local server. 
We can discuss the frontmatter layout here, and once we are happy with that we can implement changes in the `myst-theme`'s and upstream in `thebe` to support it.
* `local` section was removed
* `jupyter.server` can no longer be a boolean, it must be an object and must contain a `url` and `token` -- purpose here is to make connecting to a `localhost` server a more deliberate action
* doc changes
* tried to make the docs simpler (based on feedback)
* docs now promote use of the `jupyter` property name instead of `thebe` - `jupyter` has been added as an alias

💡proposed `thebe` frontmatter changes

---

.changeset/chilled-mirrors-watch.md
.changeset/fresh-buckets-carry.md
packages/myst-to-jats/src/frontmatter.ts
packages/myst-to-jats/tests/authors.yml
packages/myst-to-jats/tests/funding.yml
packages/myst-to-jats/tests/multi.yml

- add `name-style="western"` to jats names
- use either `name` or `string-name` element in jats, not both
See:
https://jats4r.org/authors-and-affiliations/
>  It is at the publisher’s discretion whether to use <name> or <string-name> to capture an author’s name
Note the `or`!

🔧 Improve JATS names

---

.changeset/dull-dolphins-learn.md
packages/myst-to-jats/src/transforms/references.ts

Still to do is to customize both the types of elements that are numbered as well as pass in the counter functions as options. Ideally through a plugin structure.

🏷 Ability to customize IDs in myst-to-jats

---

.changeset/strange-hats-knock.md
packages/myst-to-jats/src/frontmatter.ts
packages/myst-to-jats/tests/funding.yml

https://jats4r.org/funding/
> If JATS 1.2 or later if `@vocab=”open-funder-registry”` or `@vocab-identifier=”10.13039/open_funder_registry”` then value of the element must start with `“10.13039/”` else `ERROR`

🐛 Normalize DOI for open-funder-registry

---

.changeset/clever-days-do.md
.changeset/plenty-planets-think.md
packages/myst-frontmatter/src/frontmatter/validators.ts
packages/myst-to-jats/src/frontmatter.ts

I have removed the `short_title` length restriction, which is different in various journals, etc. This should be better enforced with specific checks (e.g. in a template or journal).

🏷 Add short_title to JATS output

---

.changeset/cyan-coins-guess.md
.changeset/light-shirts-tease.md
.changeset/metal-pans-remember.md
.changeset/purple-dancers-report.md
packages/myst-templates/src/frontmatter.spec.ts
packages/myst-templates/src/frontmatter.ts
packages/myst-to-jats/src/frontmatter.ts
packages/myst-to-jats/tests/affiliations.yml
packages/myst-to-jats/tests/authors.yml
packages/myst-to-jats/tests/funding.yml
packages/myst-to-jats/tests/multi.yml

This addresses the issues in #659 without fundamental changes to frontmatter.

👩‍🔬 Only add affiliations associated with authors to JATS and myst-templates

---

.changeset/smooth-chairs-clap.md
packages/myst-to-jats/src/index.ts
packages/myst-to-jats/src/transforms/frontmatter.ts
packages/myst-to-jats/tests/affiliations.yml
packages/myst-to-jats/tests/authors.yml
packages/myst-to-jats/tests/funding.yml
packages/myst-to-jats/tests/multi.yml

This modifies affiliation ids that appear in JATS to be simpler and uniform, by default `aff-1`, `aff-2`, etc.
It also removes the attempted author/affiliation deduplication (which previously didn't work as intended anyway).
- For authors, they simply shouldn't be deduplicated - you want to know all the different authors on each subarticle. Since we removed author ids from JATS (#662) there is no longer any JATS validation worry.
- Regarding affiliations, we do not deduplicate these either: the implication of this is that identical affiliations in different articles/subarticles will appear separately in each. However, they will also be given a different id, so JATS will be happy. I _think_ it would be nicer if affiliations were compared across articles and deduplicated, but the current …

🏫 Simplify affiliation IDs for JATS

---

.changeset/rotten-timers-worry.md
packages/myst-cli/src/process/mdast.ts
packages/myst-transforms/src/html.spec.ts
packages/myst-transforms/src/html.ts
packages/myst-transforms/src/index.ts
packages/myst-transforms/tests/html.yml

This improves a lot of the functionality around HTML processing to get it into the AST before any other transformations. We can now have things like `<figure><img src=""><figcaption>The caption</figcaption></figure>` which will be processed into the correct container. This can also work with HTML links directly to that caption, which will be processed as normal.
The IDs are required to be on the `figure`, not the `image`, but that seems reasonable.
cc @dellaert who is motivated by having HTML that works in google collab, but also works with MyST for LaTeX export.
@fwkoch there are probably a number of other changes incoming for the HTML processing along these lines, but I think we can get them in iteratively.
Fixes:
- https://github.com/executablebooks/mystmd/issues/418

👩‍💻 Improve HTML processing

---

.changeset/shaggy-moles-thank.md
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/transforms/outputs.spec.ts
packages/myst-cli/src/transforms/outputs.ts

This PR should replace the bugfix here: https://github.com/executablebooks/mystmd/pull/679
Before the previous release, during export we wrote _all_ notebook outputs to file. Often these files were read back in during processing and never referenced again, cluttering up the export workspace.
At the last release, we added some cleanup; all the outputs were still written to file, but then as they were read back in, they got deleted. That led to a bug where a single output file used in multiple places was deleted the first time it was used, then errored the second time it was needed.
This PR moves the file writing later in the processing; we never write any files until they are needed, either as static images (when a notebook output is converted to an image node) or as raw output content …

✍️ Write output content to file later in the transform process

---

.changeset/breezy-buckets-boil.md
docs/creating-pdf-documents.md
packages/myst-to-tex/src/index.ts

This prevents the cell/block from being rendered in latex

🏷 Add `no-tex` tag

---

.changeset/pink-mice-deliver.md
packages/myst-to-tex/src/index.ts

We show a warning in MyST if you reference an implicit heading. This removes them from the LaTeX export, which can't handle them and when writing multiple chapters will also warn on duplicate headers.

🗣 Do not write implicit latex labels

---

.changeset/small-falcons-speak.md
packages/myst-common/src/types.ts
packages/myst-spec-ext/src/types.ts
packages/myst-to-jats/src/index.ts
packages/myst-transforms/src/basic.ts
packages/myst-transforms/src/enumerate.spec.ts
packages/myst-transforms/src/enumerate.ts
packages/myst-transforms/src/math.ts
packages/tex-to-myst/src/math.ts
packages/tex-to-myst/tests/math.yml

This adds support for latex-parsing of sub-equations and subsequent export to JATS. The approach is to add a `mathGroup` node, and break up the align sub-equations (which are labeled `1a`, `1b`, etc.).
This breaks the alignment in the display equations, which is needed for JATS export as you cannot have one or more nested labels inside of a mathml block in JATS, and they should be a `disp-formula-group`.
In the future we can add better support for both modes with a custom renderer of `mathGroup` that prefers the aligned version, and stores it (currently) in an `equations` attribute. That theme work is not done yet.

🧮 Add support for sub-equations

---

.changeset/big-dodos-reflect.md
.changeset/gorgeous-glasses-repair.md
packages/myst-to-jats/package.json
packages/myst-to-jats/src/transforms/sections.spec.ts
packages/myst-to-jats/src/transforms/sections.ts
packages/myst-to-tex/src/utils.ts

Adds tests to the section nesting. There was previously a bug that turned
`[1,2,2]` into `[1: [2], 2]` instead of `[1: [2, 2]]`

🪆 Section nesting for JATS

---

.changeset/warm-socks-peel.md
packages/tex-to-myst/src/parser.ts
packages/tex-to-myst/tests/figures.yml

We would only remove a single space previously, this now consumes all of the whitespace at the beginning and end of a paragraph.

🐛 Space in paragraph (Tex Parsing)

---

.changeset/witty-vans-remain.md
packages/myst-to-jats/src/frontmatter.ts
packages/myst-to-jats/tests/article.yml
packages/myst-to-jats/tests/authors.yml
packages/myst-to-jats/tests/funding.yml

This adds a `license-p` paragraph for `CC-BY-4.0` output. Can add more in the future!
This also normalizes orcid output to be the URL.

🏷 Improve JATS frontmatter export

---

.changeset/early-frogs-brush.md
.changeset/red-fans-attack.md
.changeset/swift-news-change.md
.changeset/wet-ants-crash.md
packages/myst-cli/src/build/docx/single.ts
packages/myst-cli/src/build/index.ts
packages/myst-cli/src/build/init.ts
packages/myst-cli/src/build/pdf/create.ts
packages/myst-cli/src/build/site/template.ts
packages/myst-cli/src/build/tex/single.ts
packages/myst-cli/src/config.ts
packages/myst-cli/src/frontmatter.ts
packages/myst-cli/src/process/site.ts
packages/myst-cli/src/project/load.ts
packages/myst-cli/src/session/session.ts
packages/myst-cli/src/store/reducers.ts
packages/myst-cli/src/store/selectors.ts
packages/myst-templates/src/template.ts

When consuming file warnings there was a bug that sometimes made them disappear. You see the log message that the warning occurred, but the store no longer has any record of the warning when processing is complete.
This was caused by `getRawFrontmatterFromFile` always re-loading files, even if they were already loaded, which in the process clears all previous warnings. Simply not re-loading the file if it is already loaded prevents this bug.

🐛 Do not reload configs or files unnecessarily

---

.changeset/dry-rules-itch.md
.changeset/thin-elephants-flash.md
packages/myst-common/src/templates.ts
packages/myst-templates/src/types.ts
packages/myst-templates/src/validators.spec.ts
packages/myst-templates/src/validators.ts

Seems surprising that we didn't have this yet! I suppose this is mostly driven by the jtex side. where we don't have a template option that is a number. This is helpful if we are going to start to use this in other places though!

🔢 Add number to template options

---

.changeset/moody-walls-check.md
packages/myst-cli/src/build/meca/index.ts
packages/myst-cli/src/frontmatter.ts
packages/myst-cli/src/process/file.ts
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/session/cache.ts
packages/myst-cli/src/session/types.ts
packages/myst-cli/src/transforms/images.ts

There was some mismatch in `cache.$mdast` with saving relative paths, then accessing by resolved paths (e.g. https://github.com/executablebooks/mystmd/compare/feat/mdast-cache?expand=1#diff-e11e13e3b479fbfb25096e4e27367dfcc16a339b97d3cab1a4f94b1a769f599cL139)
This PR swaps to uniformly getting/setting these values with resolved paths.

🔧 Cache mdast at full file path

---

.changeset/twenty-coats-beg.md
packages/myst-directives/src/figure.ts
packages/myst-directives/src/table.ts
packages/myst-to-tex/src/container.ts

Adding `class: full-width` will change a figure to the `figure*` environment that spans columns.
See #716

↔️ Full-width images in LaTeX

---

.changeset/forty-parents-grin.md
packages/myst-cli/src/build/docx/single.ts
packages/myst-cli/src/build/tex/single.ts
packages/myst-cli/src/process/file.ts
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/session/types.ts
packages/myst-cli/src/transforms/images.ts

🤦‍♂️ I had this commit locally when testing #721 but it didn't make it into the release. Oh man. Most critically, tex exports are broken without this commit since the `cache.$mdast` lookup is using the wrong file (i.e. `file` vs `article` here https://github.com/executablebooks/mystmd/pull/728/files#diff-809f642b8b08c50fa59434f4dd5e68c8063c8be90e8022b375c13b1edb262a6bL168-R162)

🐛 Fixes to file processing - better typing, undefined handling

---

.changeset/tough-moles-wave.md
packages/myst-cli/src/frontmatter.ts
packages/myst-cli/src/process/mdast.ts

Thumbnail and banner paths in the site config were broken by this PR: #721 - The image transformations were moved later; we kept track of these changes in the file frontmatter, but we did not call `updateFileInfo` again with correct thumbnail/banner values.
Just updating file info again after image writing corrects the site config.

🎆 Write thumbnails/banner back to redux store

---

.changeset/short-bugs-tease.md
docs/citations.md
package-lock.json
packages/myst-cli/package.json
packages/myst-cli/src/transforms/dois.ts
packages/myst-transforms/src/links/doi.ts

Improves the parsing of difficult DOIs that need to be URL encoded or similar and does not validate them after being normalized.

🔗 Improve parsing of difficult DOIs

---

.changeset/silly-parents-listen.md
packages/myst-cli/src/build/tex/single.ts

I have been working through exporting a book in latex and do not want each page to have the glossaries output. This turns it off when there is no template.

🐛 Turn off glossaries for rawTex output

---

.github/workflows/ci.yml
README.md
docs/installing-prerequisites.md
docs/installing.md
docs/quickstart-myst-documents.md
docs/quickstart-myst-websites.md
docs/quickstart.md

📦 📖 Installing mystmd from conda, pypi, and npm

---

.changeset/many-spoons-beg.md
packages/myst-transforms/src/links/plugin.ts

See also: https://github.com/executablebooks/myst-theme/pull/260

🔗 Link text transform should be idempotent

---

.changeset/spotty-peaches-invent.md
packages/markdown-it-myst/src/citations.ts
packages/markdown-it-myst/tests/citations.yml

The current version will eagerly parse too many labels including if we turn some of the nesting off. This improvement excludes `[`, uses a regexp, and ensures that it is short (50 characters).

🥼 Improve suffix citation parsing

---

.changeset/lazy-kangaroos-peel.md
packages/myst-cli/src/transforms/outputs.ts

Small bug that skipped the if statement too early. Need to also include tags.

🐛 Stream outputs and `remove-stdout` on cells

---

.changeset/bright-houses-learn.md
.changeset/dull-cooks-complain.md
.changeset/light-tools-guess.md
.changeset/moody-forks-trade.md
package-lock.json
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/transforms/embed.ts
packages/myst-common/package.json
packages/myst-common/src/utils.spec.ts
packages/myst-common/src/utils.ts
packages/myst-transforms/src/basic.ts
packages/myst-transforms/src/blocks.spec.ts
packages/myst-transforms/src/blocks.ts
packages/myst-transforms/src/images.ts

This PR enables creating a figure directly inside a notebook by adding a caption to a cell:
```python
#| caption: My figure caption
...
plt.show()
```
This modifies the block structure from:
```
block > code/output
```
to
```
block > figure > code/output
```
This PR also cleans up figures referencing other figures (e.g. if you want to include a "notebook figure" created as described above in a separate markdown page). Referencing a figure from another figure removes the original caption / figure number. If you want to keep the original caption / figure number, you may `embed` the figure instead.
For full functionality with thebe, this requires https://github.com/executablebooks/myst-theme/pull/272
TODO:
There is still a little bit of wonkiness with resolving embedded content and figure …

🧱 Transform notebook blocks with captions to figures in place

---

.changeset/thirty-seas-occur.md
packages/myst-to-tex/src/container.ts

This changes from `caption[]*` --> `caption*`, and drops the short-title from unnumberred captions.

🐛 Caption tex renderer for unnumbered captions

---

.changeset/thin-walls-fail.md
packages/myst-to-jats/src/index.ts
packages/myst-to-jats/src/transforms/definitions.ts

Handles nested def lists for JATS and ensures any child of a `def` is a paragraph (as per the spec).

🪆 Nested definition lists for JATS

---

.changeset/proud-guests-brake.md
.changeset/slow-geckos-love.md
packages/myst-to-jats/src/index.ts
packages/myst-to-jats/src/transforms/blocks.ts
packages/myst-to-jats/src/transforms/definitions.ts
packages/myst-to-jats/src/transforms/index.ts

- remove hidden blocks and outputs
- remove link zero-width spaces
- fix def-list nesting in paragraphs

🏷 Improvements to JATS tagging

---

.changeset/cold-pans-lay.md
.changeset/lemon-badgers-occur.md
.changeset/silver-walls-do.md
.changeset/smooth-balloons-tell.md
packages/myst-cli/src/build/docx/single.ts
packages/myst-cli/src/build/jats/single.ts
packages/myst-cli/src/build/md/index.ts
packages/myst-cli/src/build/meca/index.ts
packages/myst-cli/src/build/tex/single.spec.ts
packages/myst-cli/src/build/tex/single.ts
packages/myst-cli/src/build/types.ts
packages/myst-cli/src/build/utils/collectExportOptions.ts
packages/myst-frontmatter/src/exports/exports.yml
packages/myst-frontmatter/src/exports/types.ts
packages/myst-frontmatter/src/exports/validators.ts
packages/myst-frontmatter/src/project/project.yml
packages/myst-to-tex/src/index.ts
packages/myst-to-tex/src/preamble.ts
packages/myst-to-tex/src/types.ts
packages/myst-to-tex/tests/glossaries.spec.ts
packages/simple-validators/src/types.ts
packages/simple-validators/src/validators.spec.ts
packages/simple-validators/src/validators.ts

- `article` is now coerced to `articles` in export frontmatter
- Multiple articles are only valid for tex/pdf - other cases raise errors
- To support this, tex `preamble` must be kept as structured data and compiled at the end (similar to how tex `imports` are already handled)

📮 Support multiple `articles` in a single export

---

.changeset/rude-bats-march.md
packages/myst-templates/src/validators.spec.ts
packages/myst-templates/src/validators.ts

This adds the min/max/integer options to the template defs, for example in #773 we need an integer number with bounds.

⚙️ Allow min/max/number on template types

---

.changeset/lazy-sloths-grab.md
.changeset/little-geese-joke.md
packages/myst-directives/src/figure.ts
packages/myst-spec-ext/src/types.ts
packages/myst-transforms/src/blocks.spec.ts
packages/myst-transforms/src/blocks.ts
packages/myst-transforms/src/containers.spec.ts
packages/myst-transforms/src/containers.ts

Recent release of subfigures caused some funny behaviour with notebook cell figures: the code became the "figure" and output was unexpectedly added to the "caption"
To fix that, this adds `output` as a figure-content type. However, that change turns notebook cell figures into subfigures (a) code and (b) output. Now there is an additional `no-subfigures` option - It can be used explicitly on `figure` directives to suppress subfigure behaviour, and it comes in implicitly on notebook cell figures to keep them a single figure with both code and output.

🎆 No subfigures option

---

.changeset/gentle-socks-leave.md
.changeset/serious-insects-wash.md
.changeset/violet-flies-reflect.md
packages/myst-cli/src/store/selectors.ts
packages/myst-to-jats/src/backmatter.ts
packages/myst-to-jats/src/index.ts
packages/myst-to-jats/src/transforms/blocks.ts
packages/myst-to-jats/src/transforms/index.ts
packages/myst-to-jats/src/types.ts
packages/myst-to-jats/tests/citations.yml
packages/myst-to-jats/tests/multi.yml

This PR addresses some of the tasks here - https://github.com/executablebooks/mystmd/issues/347:
- IDs of affiliations needs to be normalized
- This was caused by immutable objects returned by selectors - not the first time we will be bitten by that stealthy bug. Now, selectors return mutable copies, so hopefully this will not get us again 🤞
- parts need to be rendered after the ID normalization (citation labels are not being transformed)
- now, `parts` are left in the tree for final myst-to-jats mdast transforms, then plucked off immediately before `render`
- multiple unused references show up in the final jats
- now, only the used references are added to the xml, not all available citations

👩‍🎓 JATS citation / affiliation fixes

---

.changeset/fair-points-fly.md
packages/myst-frontmatter/src/project/validators.ts
packages/myst-frontmatter/src/thebe/validators.ts

* fixes #747
* also applies to `jupyter: true` and `jupyter: 'binder'` and aligns with docs.

🛠 use `github` field if no `repo` specified

---

.changeset/khaki-carrots-share.md
packages/myst-transforms/src/containers.spec.ts
packages/myst-transforms/src/containers.ts

This moves the legend to the end of the container.
Rather than directly after the caption.
This is helpful for table notes, etc.
Related to #778, which changes some of the logic there @fwkoch.

🗺 Put table legend at end

---

.changeset/giant-cameras-cry.md
packages/myst-cli/src/build/meca/index.ts

Addresses #802 - this bug was introduced when multiple `articles` were allowed on an export.

🐛 Fix error when article is not defined on meca export

---

.changeset/forty-donkeys-care.md
packages/myst-cli/src/build/meca/index.ts
packages/myst-cli/src/build/utils/collectExportOptions.ts
packages/myst-cli/src/frontmatter.ts

`loadFile` expects a project path in order to resolve its relative location. There were a few places where `loadFile` was called without `projectPath`, allowing full paths into the file metadata...

🐛 Pass projectPath to loadFile whenever possible

---

.changeset/eleven-melons-cry.md
packages/myst-roles/src/doc.ts
packages/myst-roles/src/download.ts
packages/myst-roles/src/reference.ts
packages/myst-roles/src/term.ts

This fixes the bug here: https://github.com/executablebooks/mystmd/issues/807
Some unist operations have trouble with `children: undefined` (as opposed to the `children` key just not existing).

🐛 Prevent undefined children in myst-roles

---

.changeset/brown-suits-serve.md
.changeset/gorgeous-books-sip.md
.changeset/metal-wolves-arrive.md
packages/myst-cli/src/build/build.ts
packages/myst-cli/src/build/jats/single.ts
packages/myst-cli/src/build/md/index.ts
packages/myst-cli/src/build/meca/index.ts
packages/myst-cli/src/build/site/watch.ts
packages/myst-cli/src/build/types.ts
packages/myst-cli/src/build/utils/localArticleExport.ts
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/store/reducers.ts
packages/myst-cli/src/store/selectors.ts
packages/myst-cli/src/transforms/embed.ts
packages/myst-cli/src/transforms/include.ts
packages/myst-frontmatter/src/exports/exports.yml
packages/myst-frontmatter/src/exports/types.ts
packages/myst-frontmatter/src/exports/validators.ts
packages/mystmd/src/build.ts
packages/mystmd/src/options.ts

- You may now `myst build --watch` and built files will be live-reloaded
- Changing dependencies (i.e. included/embedded content) will cause dependent pages to reload (both for exports and site build)
- export format may be inferred from filename

🏗 Add watch to build command

---

packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/transforms/inlineExpressions.ts
packages/myst-directives/src/code.ts
packages/myst-to-docx/src/schema.ts
packages/myst-to-tex/src/index.ts

This PR fixes `Unhandled LaTeX conversion for node of "inlineExpression"` error for PDF and LaTeX output converting from JupyterLab `ipynb` via `myst` command.
Added `inlineExpression` node handler to `myst-to-tex` and `myst-to-docx` packages.
It seems that the current `eval` transformer is working fine, except handling `html` MIME type.
Fixes https://github.com/executablebooks/jupyterlab-myst/issues/194
Manually tested using [examples/inline-interactivity.ipynb](https://github.com/executablebooks/jupyterlab-myst/blob/4684bc358f7d9be3fe62baccc862c35606c9c488/examples/inline-interactivity.ipynb)

🐛  Fix Inline Expressions Render

---

.changeset/new-walls-grab.md
packages/myst-cli/src/build/tex/single.ts

Latex `include` commands should not include the file extensions: https://www.overleaf.com/learn/latex/Management_in_a_large_project Apparently some latex engines don't mind but some do! This PR simply removes the extensions.

🗃 Remove file extensions from latex include

---

.changeset/bright-panthers-leave.md
.changeset/silly-bulldogs-work.md
packages/myst-cli/src/transforms/images.ts
packages/myst-cli/src/transforms/inlineExpressions.ts

Inline expression render fix here still didn't quite get transform order correct #793 - this fixes that up by running `blockMetadataTransform` before `inlineExpressionTransform`.
I also added `images` as a supported inline expression mimetype 🚀

🎆 Support images in inline expressions and fix transform order

---

.changeset/cool-tools-clean.md
.changeset/few-plants-accept.md
.changeset/rotten-kangaroos-raise.md
packages/myst-directives/src/table.ts
packages/myst-to-typst/src/container.ts
packages/myst-to-typst/src/index.ts
packages/myst-to-typst/src/table.ts
packages/myst-to-typst/src/types.ts
packages/myst-to-typst/src/utils.ts
packages/myst-to-typst/tests/basic.yml
packages/myst-to-typst/tests/figures.yml

This uses `tablex` to support tables with col/row spans in typst exports. Other small fixes included in this PR:
- `table` directive is less opinionated. The container children transform added here https://github.com/executablebooks/mystmd/pull/770 deals with tables, so we can make the directive pretty permissive and let that transform error/warn if there are issues.
- DOI citations in typst were converted back to links - we may want to do something better long-term (e.g. pull doi citations into bib) but for now, this fixes broken typst builds
- thematic breaks are now supported in typst
- multi-image figures and legends now work slightly better in typst

🍽 Support tables in typst

---

docs/integrating-jupyter.md

Partially addresses #739, and closes #816.

📖 Document setting `allow_origin` to `http://` rather than `https://`

---

.changeset/thin-houses-provide.md
docs/glossaries-and-terms.md
packages/myst-transforms/src/abbreviations.ts

This might not be the right place, or the best way to do this, but this PR orders abbreviations defined in the frontmatter by length (then by locale). As such, we no longer need to warn about the ordering.

🧭 Order abbreviations by length

---

.changeset/cuddly-coats-joke.md
packages/myst-cli/src/build/utils/bibtex.ts

There was a bug when `@ARTICLE` was used, it seems to work in both tex and typst, but we would render all citations when encountering it.

🐛 Duplicate bibtex entries when uppercase

---

.changeset/healthy-parrots-promise.md
packages/jtex/src/typst/imports.ts
packages/myst-cli/src/build/site/manifest.ts
packages/myst-cli/src/build/typst.ts
packages/myst-frontmatter/src/exports/validators.ts

This allows for multi-page exports for typst

📚 Allow multiple pages in typst export

---

.changeset/silver-zoos-bow.md
packages/myst-to-typst/src/container.ts
packages/myst-to-typst/tests/figures.yml

Previously the matching between a reference and figure label could fail due to case/spaces etc.

🔗 Match typst references and figures

---

.changeset/few-pants-trade.md
.changeset/tame-experts-drive.md
.changeset/warm-drinks-promise.md
packages/myst-cli/src/transforms/outputs.ts
packages/myst-to-typst/src/container.ts
packages/myst-to-typst/src/index.ts
packages/myst-to-typst/src/table.ts
packages/myst-to-typst/src/types.ts
packages/myst-to-typst/tests/cite.yml
packages/myst-to-typst/tests/figures.yml
packages/myst-to-typst/tests/tables.yml

- Citations: now narrative vs parenthetical is respected, and suffixes are supported
- Figures are fixed to allow images/tables plus other content - this allows jupyter notebook figures display both code and output image
- Nested definition lists indent correctly

🔧 More small typst improvements

---

.changeset/nasty-mugs-happen.md
packages/myst-frontmatter/src/numbering/numbering.yml
packages/myst-frontmatter/src/numbering/validators.ts
packages/myst-transforms/src/enumerate.ts

This allows you to additionally start numbering at `3` or any other number, rather than starting every numbering on the page at 1. This is a stepping stone towards sharing book-wide numbering.

🧮 Allow enumeration to start at a specified number

---

packages/myst-cli/src/build/html/index.ts
packages/myst-cli/src/build/jats/single.ts
packages/myst-cli/src/plugins.ts
packages/myst-cli/src/process/file.ts
packages/myst-cli/src/process/intersphinx.ts
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/process/myst.ts
packages/myst-cli/src/process/site.ts
packages/myst-cli/src/project/load.ts

This PR changes no functionality; I wanted to familiarise myself with some of the inner workings through refactoring. There are some new docstrings that mostly state the obvious but it's a start.

📚 Add docstrings to parts of myst-cli

---

.changeset/green-ravens-pump.md
packages/myst-cli/src/frontmatter.ts
packages/myst-cli/src/process/file.ts
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/process/site.ts
packages/myst-cli/src/transforms/embed.ts
packages/myst-cli/src/transforms/types.ts
packages/myst-transforms/src/enumerate.spec.ts
packages/myst-transforms/src/enumerate.ts
packages/myst-transforms/src/frontmatter.spec.ts
packages/myst-transforms/src/frontmatter.ts
packages/myst-transforms/src/glossary.ts
packages/myst-transforms/src/index.ts
packages/myst-transforms/tests/enumerators.spec.ts

By default, if no title is provided, MyST will lift the first H1 header out of the page and make it the title. However, if that header is labeled, the label is lost, e.g.
```markdown
(introduction)=
...
```
Anywhere that references `[](#introduction)` will be broken.
This PR fixes that, so now references to the label will become links to the page. To get here, it took a few steps:
1. processed pages now have `identifiers`
2. `ReferenceStateResolvers` can now get `fileTargets` in addition to "normal" node targets
3. Cross-references to these new file targets resolve into an internal `Link` node.
I also refactored the ReferenceState code a little bit... Previously there was a single page `ReferenceState` and a `MultiPageReferenceState`. Both had functionality to add targets and resolve …

🕵️‍♀️ Support cross-references to file allowing labels on lifted headers

---

.changeset/beige-jobs-decide.md
.changeset/chatty-birds-admire.md
package-lock.json
packages/jats-to-myst/package.json
packages/myst-cli/package.json
packages/myst-common/package.json
packages/myst-ext-proof/package.json
packages/myst-parser/package.json
packages/myst-spec-ext/package.json
packages/myst-to-docx/package.json
packages/myst-to-html/src/schema.ts
packages/myst-to-html/tests/html.spec.ts
packages/myst-to-jats/package.json
packages/myst-transforms/package.json

change `math block` to `math-display` and `math inline` to `math-inline`
ref #859

🎨 Update CSS classes applied to math nodes to match `remark-math`

---

.changeset/poor-maps-knock.md
package-lock.json
package.json
packages/citation-js-utils/package.json
packages/citation-js-utils/src/index.ts
packages/citation-js-utils/types/citation-js/index.d.ts
packages/myst-cli/src/build/utils/collectExportOptions.ts
packages/myst-common/src/plural.ts
packages/myst-frontmatter/src/site/validators.ts
packages/tex-to-myst/src/parser.ts

This PR replaces the use of `citation-js` with `@citation-js/core`. With the CSL and bibtex plugins, the installed size is <1 MB.

📦  Refactor to use `@citation-js/core`

---

.changeset/sweet-chefs-greet.md
packages/jtex/src/jtex.ts
packages/myst-cli/src/build/build.ts
packages/myst-cli/src/build/docx/single.ts
packages/myst-cli/src/build/jats/single.ts
packages/myst-cli/src/build/md/index.ts
packages/myst-cli/src/build/meca/index.ts
packages/myst-cli/src/build/pdf/single.ts
packages/myst-cli/src/build/tex/single.ts
packages/myst-cli/src/build/types.ts
packages/myst-cli/src/build/typst.ts
packages/myst-cli/src/build/utils/localArticleExport.ts
packages/mystmd/src/build.ts
packages/mystmd/src/options.ts
packages/mystmd/tests/exports.yml
packages/mystmd/tests/outputs/multi-page-tex.tex
packages/mystmd/tests/outputs/templated-tex.tex

This adds a `--ci` flag to `myst build` - for now all it does is take the version comments out of jtex-rendered files.

🤖 Add build ci option to not write versions

---

.changeset/yellow-seas-drop.md
packages/myst-to-typst/src/index.ts

DOI citations are now handled correctly in our typst exports so we no longer need to write them as links. Easy!

🛑 Stop turning dois to links in typst

---

.changeset/breezy-hairs-poke.md
packages/myst-cli/src/process/myst.ts
packages/myst-cli/src/process/notebook.ts
packages/mystmd/tests/exports.yml
packages/mystmd/tests/notebook-with-fm/input.ipynb
packages/mystmd/tests/notebook-with-fm/myst.yml
packages/mystmd/tests/outputs/notebook.tex

We modified notebook loading to parse each cell individually - this cased a bug where every cell could have a yaml frontmatter block.
This PR turns off that behaviour for all but the first cell.

🔧  Only parse frontmatter out of first notebook cell

---

.changeset/lemon-boxes-divide.md
.github/actions/install/action.yml
.github/workflows/ci.yml
.github/workflows/release.yml
docs/deployment.md
packages/myst-cli/src/build/gh-actions/index.ts

The node16 actions are being deprecated.

⚙️ Move to `v4` for checkout and node actions

---

.changeset/modern-hotels-drop.md
.changeset/spotty-mirrors-peel.md
docs/reuse-jupyter-outputs.md
packages/myst-cli/src/transforms/code.spec.ts
packages/myst-cli/src/transforms/code.ts
packages/myst-cli/src/transforms/outputs.spec.ts
packages/myst-cli/src/transforms/outputs.ts
packages/myst-frontmatter/src/licenses/licenses.ts
packages/myst-spec-ext/src/types.ts

This allows defining a placeholder image in code cell metadata, e.g.:
```python
#| placeholder: image.png
print('hello world')
```
This will add an `image` node with `placeholder: true` to the output node children mdast. Output rendering code can now be updated to render children and consume this, when appropriate.
(Also as a bonus, new licenses released today 😬)

🎆 Add code cell metadata placeholder image to output children

---

.changeset/orange-radios-rhyme.md
packages/citation-js-utils/src/index.ts
packages/citation-js-utils/tests/basic.spec.ts
packages/citation-js-utils/tests/fixtures.ts

This allows for pulling out DOIs from the `note` element in a bibtex citation, this is quite common in some areas that use IEEE citation styles which by default doesn't show the DOI, so people move it to the note.
We still want to get the DOI out when rendering with MyST.

🎣 Extract DOI from note for citations

---

.changeset/brown-numbers-wait.md
packages/myst-transforms/src/headings.spec.ts
packages/myst-transforms/src/headings.ts

Recently a new transform was added to `basicTransformations` which normalized heading depth to start at `firstDepth` and count sequentially from there (eliminating skipped depth levels in the source document, etc. - introduced here: https://github.com/executablebooks/mystmd/pull/860 and modified here: https://github.com/executablebooks/mystmd/pull/875/files#diff-8c1296487484c1e135623cfc74ae7da928a293e1b6e5078690cfc7a1fe01df09)
However, there was no way to disable this behaviour; running the basic transforms meant heading depths would get normalized.
Now, this transform _only_ runs if you explicitly provide `firstDepth`. `myst-cli` always provides a value for `firstDepth`, so default, opinionated MyST behaviour is unchanged. But if you use `headingDepthTransform` or `basicTransformations` …

🔧  Prevent basic transforms from modifying headings by default

---

.changeset/real-jeans-shout.md
.changeset/rich-frogs-try.md
.changeset/tender-crabs-push.md
docs/figures.md
packages/myst-spec-ext/src/types.ts
packages/myst-transforms/src/enumerate.ts
packages/tex-to-myst/src/figures.ts
packages/tex-to-myst/src/misc.ts
packages/tex-to-myst/src/refs.ts
packages/tex-to-myst/src/tex.ts
packages/tex-to-myst/tests/figures.yml

Also adds support in latex for `subref`, `landscape` and improves `subfigure` support for multiple captions defined in latex.

👈 Cross reference the subEnumerator directly.

---

.github/workflows/release.yml
packages/mystmd/package.json

This PR:
- Updates the `mystmd` package metadata to provide a valid Git URL (only https scheme) for PyPI
- Updates the release workflow to use the new trusted publisher

MAINT: update python release workflow

---

.github/workflows/release.yml
packages/mystmd-py/.gitignore
packages/mystmd-py/pyproject.toml
packages/mystmd-py/scripts/pypi-deploy.sh
packages/mystmd/package.json

This PR changes the build plugin to look for `_package.json` rather than the canonical name. This ensures that the build artifact (`_package.json`) is not found by NPM during local development (as it complains).

MAINT: use _package.json to avoid NPM errors during local dev

---

.changeset/lemon-tomatoes-share.md
packages/citation-js-utils/src/index.ts
packages/citation-js-utils/tests/basic.spec.ts
packages/citation-js-utils/tests/fixtures.ts

This pulls in the DOI from the URL if it isn't already defined.

🎣 Extract DOI from URL for citations

---

.changeset/long-ducks-shave.md
.changeset/new-poems-whisper.md
.changeset/red-schools-love.md
.changeset/serious-hairs-visit.md
packages/myst-cli/src/build/site/watch.ts
packages/myst-cli/src/process/file.ts
packages/myst-cli/src/transforms/include.ts
packages/myst-transforms/src/include.ts
packages/tex-to-myst/src/misc.ts
packages/tex-to-myst/tests/cases.spec.ts
packages/tex-to-myst/tests/input.yml

This supports the input macro for latex, and improves the include transform to be able to be recursive.

🪆 Support `\input` in latex

---

.changeset/rare-trainers-listen.md
.changeset/twelve-walls-talk.md
docs/citations.md
docs/external-references.md
docs/quickstart-myst-websites.md
packages/myst-cli/docs/reference.md
packages/myst-cli/src/build/clean.ts
packages/myst-cli/src/process/intersphinx.ts
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/transforms/dois.ts
packages/myst-cli/src/transforms/links.ts
packages/mystmd/src/clean.ts
packages/mystmd/src/options.ts

This adds a new `cache` directory to the `_build` folder, where web request results may be stored across sessions.
For now, this is storing:
- doi.org bibtex responses for each successful doi request
- intersphinx inventory files
- successful link check statuses

🏴‍☠️ Cache DOIs and intersphinx results to file

---

.changeset/fuzzy-mayflies-punch.md
.changeset/great-goats-search.md
packages/myst-common/src/ruleids.ts
packages/myst-transforms/src/basic.ts
packages/myst-transforms/src/code.spec.ts
packages/myst-transforms/src/code.ts
packages/myst-transforms/src/index.ts

When tex is being parsed, it is possible for inline code `\texttt{}` to have children. If all of those children are text, then the children are transformed into be a single node with `.value`.

🫓 Flatten inlineCode (that may have children)

---

.changeset/itchy-rules-act.md
packages/tex-to-myst/src/parser.ts
packages/tex-to-myst/src/quotes.ts
packages/tex-to-myst/src/tex.ts
packages/tex-to-myst/tests/cases.spec.ts
packages/tex-to-myst/tests/quote.yml

Support quote, displayquote and epigraph

💬 Support quote environments in latex

---

.changeset/wet-crabs-taste.md
docs/table-of-contents.md
packages/myst-cli/src/build/site/watch.ts
packages/myst-cli/src/config.ts
packages/myst-cli/src/project/fromPath.ts
packages/myst-cli/src/project/load.ts
packages/myst-cli/src/project/toc.spec.ts
packages/myst-cli/src/project/types.ts
packages/myst-config/src/project/project.spec.ts
packages/myst-config/src/project/validators.ts

- Without an explicit `_toc.yml` file, the project build pulls in all md/ipynb files from the project directory
- During `myst start` all files within the directory are watched (potentially an arbitrarily large number of files... enough to break the `watch` function)
- Project config already has an `exclude` field for a list of files to "exclude" - however, nothing respects those excluded files...
- Files listed under `exclude` in the project config are treated as `glob` patterns. These come into play in two places:
1. During project build, any md/ipynb that matches an exclude pattern will not be added to the project
2. During `myst start`, everything matched by `exclude` is ignored (so you can ignore folders with lots of unrelated files)
- To make this work, there were some changes to …

❎ Exclude files listed in project config from myst build and watch

---

.changeset/wild-comics-tease.md
packages/myst-cli/src/build/index.ts
packages/myst-cli/src/build/jats/single.ts
packages/myst-cli/src/build/meca/index.ts

This is just some minor cleanup so jats/meca functions have the same type interface as other export functions... We also weren't exporting jats export before.

📤 Conform jats/meca export function interface to other export functions

---

.changeset/neat-dancers-carry.md
docs/frontmatter.md
package-lock.json
packages/myst-cli/package.json
packages/myst-cli/src/build/gh-actions/index.ts
packages/myst-cli/src/build/init.ts
packages/myst-cli/src/build/utils/github.ts
packages/myst-cli/src/build/utils/index.ts
packages/myst-frontmatter/src/project/project.yml
packages/myst-frontmatter/src/project/types.ts
packages/myst-frontmatter/src/project/validators.ts

Adding a unique `id` to project frontmatter gives us a way to consistently track the project across different contexts. By default, this is populated on `init` with `<org>/<repo>` if inside a github project and a `uuid` if not.
I also added brief documentation for the other project-only frontmatter fields 📚📚📚

🪪 Add id to project frontmatter and populate on init

---

.changeset/five-countries-wait.md
.changeset/good-cameras-hammer.md
.changeset/mean-walls-hear.md
.changeset/ninety-pots-smash.md
.changeset/tough-cycles-scream.md
.changeset/weak-games-poke.md
packages/citation-js-utils/src/index.ts
packages/citation-js-utils/tests/basic.spec.ts
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/transforms/citations.spec.ts
packages/myst-cli/src/transforms/citations.ts
packages/myst-cli/src/transforms/dois.ts
packages/myst-common/src/ruleids.ts
packages/myst-common/src/types.ts
packages/myst-spec-ext/src/types.ts

- Some dois do not have bibtex available from doi.org - we now give more useful warnings in this case
- Year is parsed from dates if they are defined as a string in bibtex (e.g. "August 1, 2012") instead of structured `year`/`day` values.
- Fix bug where all non-doi urls were deleted from citation html
- CLI warns on unknown citation labels, eg `@unknown`
- cite nodes now have enumerator value so we can switch to citing like `[1]`
- URLs are pulled from citation data to be available to the renderer

🎓 Citation improvements

---

.changeset/breezy-plants-act.md
package-lock.json
packages/myst-parser/package.json
packages/myst-parser/src/config.ts
packages/myst-parser/src/myst.ts
packages/myst-parser/tests/linkify.spec.ts

There are a ton of domains that `linkify` catches, including `py`... That means someone writing about their python `my_script.py` file gets linkified.
For now, I've addressed this by hard-coding excluded domains in myst parser. We may want to make this configurable at the MyST config level...?
I think hardcoding what is excluded is ok, since users can always explicitly make things a link. If something they want linkified is not working (because of our exclude list), they can just make it an explicit link. Potentially we even lock down the domain list way more... there are currently 1450 valid domains 😳 https://github.com/stephenmathieson/node-tlds/blob/master/index.json (1449 with `py` excluded).

🐍 Remove .py from linkify domains

---

.changeset/gentle-hounds-boil.md
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/transforms/citations.ts
packages/myst-common/src/ruleids.ts

This PR #937 restored warnings for inline citations that could not be resolved - However, these warnings were added too early (before resolving these citation labels as normal cross-references) and, it turns out, there already was a warning in the correct place. It just didn't work because the `vfile` wasn't getting passed around correctly.
This PR removes the recently added warning and fixes the existing warning.

🪵 Log missing citations in the correct place

---

.changeset/lucky-clocks-repair.md
packages/myst-transforms/src/include.ts

This recursive call was causing infinite recursion problems. It should be fixed for real, but for now, this disables the recursion.

🔃 Do not recursively call include transform

---

.changeset/new-walls-brake.md
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/transforms/raw.ts
packages/myst-directives/src/index.ts
packages/myst-directives/src/raw.ts
packages/myst-spec-ext/src/types.ts

The `raw` directive lets you include raw latex in a myst file. The latex will be parsed using `tex-to-myst`:
````markdown
```{raw} latex
\section{Hello World!}
\textbf{Hello World!} Here's some latex!
\begin{equation}
\gamma^2+\theta^2=\omega^2
\end{equation}
Pretty cool!
```
````
You can also use the `raw` directive to add unparsed text:
````markdown
```{raw}
*Keep these astrisks!*
```
````

🥩 Add raw directive

---

.changeset/neat-teachers-look.md
.changeset/weak-squids-refuse.md
packages/myst-cli/src/build/build.ts
packages/myst-cli/src/build/site/prepare.ts
packages/myst-cli/src/build/site/start.ts
packages/myst-cli/src/build/site/watch.ts
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/process/site.ts
packages/myst-cli/src/transforms/images.ts
packages/myst-cli/src/utils/imagemagick.ts
packages/mystmd/src/build.ts
packages/mystmd/src/options.ts
packages/mystmd/src/site.ts

By default we do not convert large images to webp so build time may be shorter. However, there are cases where we may want to convert all images, regardless of size (e.g. one-time publish actions). This PR exposes that functionality to pass in `maxSizeWebp` as an option to `buildSite`

🎆 Expose max size for webp conversion

---

.changeset/mighty-yaks-nail.md
.changeset/nice-papayas-count.md
docs/cross-references.md
docs/frontmatter.md
package-lock.json
packages/myst-frontmatter/src/numbering/numbering.spec.ts
packages/myst-frontmatter/src/numbering/numbering.yml
packages/myst-frontmatter/src/numbering/types.ts
packages/myst-frontmatter/src/numbering/validators.ts
packages/myst-frontmatter/src/project/project.yml
packages/myst-frontmatter/src/project/types.ts
packages/myst-frontmatter/src/project/validators.ts
packages/myst-frontmatter/src/utils/fillPageFrontmatter.spec.ts
packages/myst-frontmatter/src/utils/fillPageFrontmatter.ts
packages/myst-transforms/package.json
packages/myst-transforms/src/enumerate.spec.ts
packages/myst-transforms/src/enumerate.ts
packages/myst-transforms/src/index.ts
packages/myst-transforms/tests/enumerators.yml

This updates numbering frontmatter so each field is an object with `enabled`, `template`, and `start`. `start` sets the first number for the corresponding kind and `template` sets the text when the item is referenced inline.
```yaml
numbering:
figure:
start: 3
template: Fig. %s
```
This is backwards compatible with the previous numbering schema for enabling/disabling numbering, e.g. 
```yaml
numbering: true
```
and
```yaml
numbering:
headings: true
figure: false
```
are still valid.
More details in the docs updates in this PR!

🔢 Expand numbering items to include template and start

---

docs/_toc.yml
docs/contribute-templates.md

@choldgraf following your lead this is some pointers to more tempalte docs and tutorials.

📖 Contribute template docs

---

.changeset/tidy-buttons-sparkle.md
packages/myst-cli/src/build/site/watch.ts

Currently all hidden directories are ignored by the project tree, which selects markdown files that are not in hidden folders or node_modules, etc.
However, these are still being watched, and that can lead to large performance hits if there are a lot of files in the hidden directories (e.g. pixi).
cc @roaldarbol
This is the previous output, in the this PR these files don't trigger changes:

🙈 Ignore hidden directories from watch

---

.changeset/slow-pumpkins-protect.md
packages/myst-cli-utils/src/index.ts
packages/myst-cli-utils/src/session.ts

When adding `fetch` to `ISession`, I removed the basic `Session` implementation from `myst-cli-utils`, so that library did not need to import/implement `fetch`: https://github.com/executablebooks/mystmd/commit/36decbb45e705d4f5af9f3967d676df2e64d342f#diff-abc58fa98ab1efb675ec0fe9411bd055f6ef828067556d9f747e371e1bffd5b2
This PR just brings back that `Session` and resolves the `fetch` issue by leaving it unimplemented.

🧟‍♂️ Restore basic session on myst-cli-utils

---

.changeset/giant-books-greet.md
packages/myst-to-tex/src/math.ts
packages/myst-to-tex/tests/amsmath.yml

🧮 Fix AMSMath environment for LaTeX

---

.changeset/tough-pandas-mix.md
packages/myst-to-typst/src/index.ts
packages/myst-to-typst/tests/cite.yml

This fixes many of the Typst issues that @choldgraf ran into with the CZI report, by wrapping non-identifier labels in `label("<URL>")`
c.f. https://typst.app/docs/reference/model/cite#parameters-key

🏷  Typst: wrap non-identifiers in `label`

---

docs/frontmatter.md

The documentation refers to a `myst` key, rather than `version`.

:books: fix `version` key in documentation config example

---

docs/contribute-docs.md

The repository was moved in executablebooks/mystmd.org#11
I am surprised I didn't catch this in #967 as I waited to merge that because of the change!

📖 Update to repository in docs

---

.changeset/big-peas-crash.md
.changeset/clean-dots-glow.md
.changeset/tidy-windows-smell.md
docs/_toc.yml
docs/blocks.md
docs/document-parts.md
docs/quickstart-myst-documents.md
packages/myst-common/src/extractParts.spec.ts
packages/myst-common/src/extractParts.ts
packages/myst-frontmatter/src/site/validators.ts
packages/tex-to-myst/src/frontmatter.ts

Parts like `abstract`, `acknowledgements`, etc. can be tagged and picked up by templates to be used separately from the rest of the content.
Currently there are two ways of defining these parts - (1) putting them under `parts` in the frontmatter:
```md
---
parts:
abstract: My abstract!
---
...
```
or (2) adding metadata to a block with inline JSON:
```md
+++ { "part": "abstract" }
My abstract
+++
...
```
Both of these require a bit of boilerplate, but worse, if the source for your MyST build is LaTeX, these syntaxes are not available, so you cannot tag a part.
---
This PR updates the `extractPart` method to pull out parts based on sections. It looks for `headings` that match `part` names and, if found, extracts the subsequent paragraphs as the part. That means you can simply do something …

🛸 Update extractParts to pull implicit parts based on heading

---

.changeset/little-garlics-speak.md
docs/_toc.yml
docs/directives.md
docs/directives.mjs
docs/roles.md
docs/typography.md
packages/myst-common/src/types.ts
packages/myst-directives/src/embed.ts
packages/myst-roles/src/keyboard.ts

This is a first pass at documenting all the roles we are including.

📖 Document roles

---

.changeset/fluffy-geese-count.md
.changeset/hungry-ghosts-jog.md
packages/myst-common/src/utils.spec.ts
packages/myst-common/src/utils.ts

💬 Fix glossary terms with quotes in labels

---

.changeset/lemon-days-leave.md
docs/frontmatter.md
packages/myst-frontmatter/src/page/validators.ts
packages/myst-frontmatter/src/project/project.yml
packages/myst-frontmatter/src/site/types.ts
packages/myst-frontmatter/src/site/validators.ts

Addresses the need for `copyright` here: https://github.com/executablebooks/mystmd/issues/1009
For now, this is just a string, available at the site/project/page level, with inheritance (e.g. project copyright is used for page copyright unless page redefines it).

👩‍⚖️ Add copyright to frontmatter

---

.changeset/afraid-coats-repeat.md
.changeset/curvy-stingrays-design.md
.changeset/six-pens-sit.md
.changeset/thirty-avocados-build.md
.changeset/twenty-tips-end.md
.changeset/wild-actors-retire.md
packages/myst-cli/src/build/build.spec.ts
packages/myst-cli/src/build/build.ts
packages/myst-cli/src/build/pdf/single.ts
packages/myst-cli/src/build/types.ts
packages/myst-cli/src/build/typst.ts
packages/myst-cli/src/build/utils/collectExportOptions.spec.ts
packages/myst-cli/src/build/utils/collectExportOptions.ts
packages/myst-cli/src/build/utils/defaultNames.ts
packages/myst-cli/src/frontmatter.ts
packages/myst-common/src/ruleids.ts
packages/myst-frontmatter/src/exports/exports.yml
packages/myst-frontmatter/src/exports/types.ts
packages/myst-frontmatter/src/exports/validators.ts

Previously, when defining exports, you _had_ to specify format:
```
---
exports:
- format: pdf
---
```
This is redundant with extensions...
```
---
exports:
- format: pdf
output: index.pdf
---
```
...and templates...
```
---
exports:
- format: typst
output: lapreprint-typst
---
```
There is also ambiguity around what `format: pdf` means, e.g. if I want a pdf built with `typst`, this failed since pdf was synonymous with `tex` build:
```
---
exports:
- format: pdf
output: lapreprint-typst
---
```
This PR refactors the export collection logic to be more human-friendly.
- Format can now be determined from `format`, `output`, or `template`, redundancy is not required
- `format: pdf` is more flexible and can result in a typst build if typst template or file extension are used
- Export may now …

📤 Refactor exports for more flexibility

---

.changeset/light-teachers-give.md
.changeset/pretty-berries-ring.md
.changeset/seven-waves-serve.md
.changeset/weak-lemons-burn.md
docs/frontmatter.md
packages/myst-frontmatter/src/affiliations/validators.ts
packages/myst-frontmatter/src/contributors/authors.yml
packages/myst-frontmatter/src/contributors/contributors.yml
packages/myst-frontmatter/src/contributors/validators.ts
packages/myst-frontmatter/src/funding/types.ts
packages/myst-frontmatter/src/page/validators.ts
packages/myst-frontmatter/src/site/types.ts
packages/myst-frontmatter/src/site/validators.ts
packages/myst-frontmatter/src/utils/fillPageFrontmatter.spec.ts
packages/myst-frontmatter/src/utils/fillPageFrontmatter.ts
packages/myst-frontmatter/src/utils/referenceStash.spec.ts
packages/myst-frontmatter/src/utils/referenceStash.ts

This reuses the same `stash` infrastructure that as `funding` recipients/investigators.
On the final resolved frontmatter, `editors` and `reviewers` are lists of string ids which index into `contributors` and `authors` (each of those is still a full object).
(The actual editor/reviewer changes are pretty straightforward `frontmatter` updates - there was just another related edge case I ironed out to slightly complicate things...)
(This addresses a point in #1009)

🏫 Add reviewers and editors to frontmatter

---

.changeset/silent-pans-argue.md
.changeset/swift-rocks-flash.md
packages/myst-frontmatter/src/affiliations/validators.ts
packages/myst-frontmatter/src/contributors/authors.yml
packages/myst-frontmatter/src/contributors/contributors.yml
packages/myst-frontmatter/src/contributors/types.ts
packages/myst-frontmatter/src/contributors/validators.ts
packages/myst-frontmatter/src/site/validators.ts

Now, in addition to being a `Person`, any `Contributor` in myst frontmatter may be a "collaboration" - that is, an `Affiliation` with `collaboration: true`. The logic to determine if a user-specified contributor is a person or a collaboration relies on checking the `collaboration` field - if `true`, it is a collaboration and validated as such; if `falsy` it is a person.
This addresses a point in #1009

👯‍♀️ Add collaborations to Contributor type

---

.changeset/flat-moose-work.md
packages/myst-cli/src/build/utils/collectExportOptions.spec.ts
packages/myst-cli/src/build/utils/collectExportOptions.ts
packages/myst-common/src/ruleids.ts

The latest release changed how export format was determined. It introduced a bug where an error was rasied if it wasn't sure if it had a LaTeX or Typst PDF template, e.g. this export currently errors:
```
- format: pdf
template: volcanica
article_type: Report
toc: _toc.yml
output: my-document.pdf
```
This PR restores the previous behaviour where the above export is just assumed to be a LaTeX template.

🐛 Fix bug causing pdf exports to fail

---

.changeset/chilly-mice-yell.md
packages/myst-cli/src/process/notebook.ts
packages/myst-cli/src/transforms/inlineExpressions.ts

Fixing the bug reported in discord:
https://discord.com/channels/1083088970059096114/1224500421402431580/1224500421402431580

🐛 findExpression allows undefined metadata

---

.changeset/fuzzy-pots-think.md
packages/markdown-it-myst/src/directives.ts
packages/myst-parser/tests/directives/code.yml
packages/myst-parser/tests/myst.spec.ts

This code block now has indentation at the start. Previously it was trimmed.
````
```{code-block} c
:linenos: true
:lineno-start: 2
:emphasize-lines: 3
for (int i = 0; i < 10; i++) {
/* do something */
}
```
````

🔭 Trim end of line only in directives (important for `code-blocks`)

---

.changeset/small-avocados-sleep.md
packages/tex-to-myst/src/verbatim.ts
packages/tex-to-myst/tests/verbatim.yml

This can now parse:
```latex
\begin{lstlisting}[language=c,numbers=left,firstnumber=2]
for (int i = 0; i < 10; i++) {
/* do something */
}
\end{lstlisting}
```

🎨 Update `listings` options for tex parsing

---

.changeset/gorgeous-pans-love.md
.changeset/shy-taxis-rhyme.md
packages/myst-cli/src/process/notebook.ts
packages/myst-execute/src/execute.ts

Fixes a bug where the inline expressions were not getting picked up properly in the mystmd side when they were previously executed in JupyterLab-MyST.

🐛 Inline expression parsing

---

.changeset/odd-icons-complain.md
.changeset/purple-ants-tie.md
docs/frontmatter.md
packages/myst-cli/src/build/site/manifest.ts
packages/myst-cli/src/build/utils/collectExportOptions.ts
packages/myst-cli/src/frontmatter.ts
packages/myst-cli/src/process/site.ts
packages/myst-config/src/site/site.spec.ts
packages/myst-config/src/site/types.ts
packages/myst-config/src/site/validators.ts
packages/myst-frontmatter/src/downloads/downloads.yml
packages/myst-frontmatter/src/downloads/index.ts
packages/myst-frontmatter/src/downloads/types.ts
packages/myst-frontmatter/src/downloads/validators.ts
packages/myst-frontmatter/src/exports/exports.yml
packages/myst-frontmatter/src/exports/types.ts
packages/myst-frontmatter/src/exports/validators.ts
packages/myst-frontmatter/src/index.ts
packages/myst-frontmatter/src/project/types.ts
packages/myst-frontmatter/src/project/validators.ts
packages/myst-frontmatter/src/site/validators.ts

Previously, when you built a MyST site, all the `exports` defined on a page became **Downloads** and there was no other way to define additional or different downloads.
This PR adds `downloads` to page/project frontmatter as a place to specify (1) paths to local files and/or (2) export `id` values. Then, when you build your site, no longer do all the exports show up as downloads but only the specific `downloads` you specify.
This also makes improvements to site actions outlined here: https://github.com/executablebooks/mystmd/pull/1048

📥 Add downloads to page/project frontmatter and site config

---

docs/accessibility-and-performance.md
docs/admonitions.md
docs/citations.md
docs/code.md
docs/contribute-add-feature.md
docs/creating-pdf-documents.md
docs/creating-word-documents.md
docs/cross-references.md
docs/documents-exports.md
docs/embed.md
docs/figures.md
docs/frontmatter.md
docs/proofs-and-theorems.md
docs/quickstart-jupyter-lab-myst.md
docs/quickstart-myst-documents.md
docs/quickstart-myst-markdown.md
docs/quickstart-myst-websites.md
docs/reuse-jupyter-outputs.md
docs/tables.md
packages/myst-parser/docs/extending/directives.md
packages/myst-parser/tests/directives.math.md
packages/myst-parser/tests/roles.references.md

This is an attempt at very-dumbly swapping out `:name: ` and replacing it with `:label: `, since I believe that is the preferred nomenclature moving forward. I saw a few different uses in the docs and it was confusing me.
This is just a find/replace, so it might miss some stuff, but I wanted to see how far I'd get by doing it the easy way.
- closes #1068

Change `:name: ` to `:label: ` to standardize label syntax

---

.changeset/curvy-ligers-clap.md
packages/myst-cli/src/transforms/dois.ts

See #1072
@agoose77 this is a much simpler approach than you have taken in #1073. I think that PR actually offers a fix, and this PR is just doing symptoms and error messages so the user can correct. It is not a replacement for your PR, just something we can get out today.

🐛 Do not fail on citation.js

---

CONTRIBUTING.md
README.md
docs/_toc.yml
docs/contributing.md

I thought this PR might be a good place to discuss how users can best contribute to the `mystmd` projects.
Within `executablebooks` there are a few different places to find information, e.g. [within the Community Guide](https://executablebooks.org/en/latest/contribute/) and the [Development Guide](https://compass.executablebooks.org/en/latest/development/conventions.html). I must admit I had never found them before having them pointed out as `mystmd` has its own website. So it begs the question: Should we simply point there or have additional docs for `myst`-related projects? Personally I'd lean towards having docs here too.
Which are the main channels of communication, who are the main devs, what are their domains (so people know who to ping when needed).
EDIT choldgraf: I'd say:
- **For …

Create contribution docs

---

.changeset/fast-pigs-breathe.md
.changeset/flat-pears-poke.md
packages/myst-cli/src/transforms/dois.ts
packages/myst-common/src/extractParts.spec.ts
packages/myst-common/src/extractParts.ts
packages/myst-frontmatter/src/page/validators.ts
packages/myst-frontmatter/src/site/types.ts

We have some "known parts" that we respect in frontmatter validation, e.g. `acknowledgments`, `abstract`. These also have aliases (in the same pattern as other frontmatter aliases), e.g. `acknowledgments` -> `acknowledgements`, `ack`.
However, these aliases were only respected for _top-level_ frontmatter keys; they were not respected when nested under `parts`, nor when called upon in `extractPart`.
Examples:
```
---
ack: Thank you!
---
```
would coerce to 
```
---
parts:
acknowledgments: Thank you!
---
```
but
```
---
parts:
ack: Thank you!
---
```
would remain unchanged during validation.
Also, `extractPart(tree, 'ack')` would not pick up on `part: acknowledgments`.
This PR updates frontmatter and `extractPart` to respect the aliases and coerce/extract consistently.

📓 Respect part aliases in parts frontmatter and extractPart function

---

.changeset/tiny-bikes-invite.md
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/session/types.ts
packages/myst-execute/src/execute.ts
packages/myst-execute/src/manager.ts
packages/myst-execute/tests/run.spec.ts

It turns out that the notebook path that is passed to the session manager should be given relative to the server base-path!

🐛 Set notebook path relative to session manager path

---

CONTRIBUTING.md
docs/contributing.md
docs/embed.md

I noticed that we were pulling in the `# Contributing` title markdown in our `{include}` statement for the contributing guide. I decided to try using the `start-after` argument to see if we can remove that content from the MyST site. In the process I also added an easier-to-find link to the reference docs for both `{embed}` and `{include}`.
I used the `start-after` argument similar to how it's used in Sphinx, and assumed it'd work since it is documented. However it's not cutting off the top part of the included page. I wonder if this is a bug or if I'm using it incorrectly. @rowanc1 or @fwkoch do you have guidance?

📖 Small updates to contributing and include docs

---

.changeset/sixty-ducks-hug.md
CONTRIBUTING.md
docs/creating-pdf-documents.md
docs/creating-word-documents.md
docs/execute-notebooks.md
docs/frontmatter.md
docs/integrating-jupyter.md
docs/myst.yml
docs/proofs-and-theorems.md
docs/settings.md
packages/myst-cli/src/process/site.ts
packages/myst-cli/src/transforms/links.ts
packages/myst-cli/src/utils/addWarningForFile.ts
packages/myst-config/src/errorRules/errorRules.yml
packages/myst-config/src/errorRules/index.ts
packages/myst-config/src/errorRules/types.ts
packages/myst-config/src/errorRules/validators.ts
packages/myst-config/src/project/types.ts
packages/myst-config/src/project/validators.ts
packages/myst-config/tests/examples.spec.ts

This adds a `error_rules` to the project configuration, which can be used to disable logging rules in the CLI.

🚦 Change severity of the error messages

---

.changeset/mean-windows-hammer.md
packages/myst-common/src/index.ts
packages/myst-common/src/types.ts
packages/myst-parser/src/directives.ts
packages/myst-parser/src/myst.ts
packages/myst-parser/src/roles.ts
packages/myst-parser/src/tokensToMyst.ts
packages/myst-parser/tests/recursiveParsing.spec.ts
packages/myst-transforms/src/basic.ts

This is a simple PR to permit MyST directives to invoke the MyST parser.
I don't know whether we'll want to provide a more explicit set of parsing routines, e.g. `parseInline` and `parseBlock`. My hunch is that we can get to that fairly easily using transforms, so it's not necessary.

🪆 Add support for nested parsing

---

docs/table-of-contents.md

We have removed most references to nested projects, this was still in the docs.
See #670

📖 Update docs around nesting of files

---

.changeset/rare-bats-switch.md
packages/myst-cli/src/plugins.ts

When loading plugins, we were previously only loading from `currentProjectConfig`. This PR updates the loading logic to also look at the `currentSiteConfig` and load all plugins from each of the site's projects.

🔌 Load plugins from all site projects, rather than just "current project"

---

.changeset/wet-buttons-heal.md
packages/myst-cli/src/build/html/index.ts

There must be a better way around this with relative paths [^1], but until then, this is a simple quick-fix for RTD deployments. The user would still need #984 to have a seamless experience.
Closes #983
[^1]: https://github.com/executablebooks/mystmd/issues/188#issuecomment-2003171341

🔗 Use `READTHEDOCS_CANONICAL_URL` as baseurl if defined

---

.readthedocs.yaml

I will create a `mystmd-temp` slug to test if it all works as expected
Closes #968

📖 Add ReadTheDocs automation

---

.changeset/happy-gorillas-argue.md
.changeset/young-snakes-cough.md
docs/blocks.md
docs/creating-pdf-documents.md
packages/myst-common/src/index.ts
packages/myst-common/src/utils.ts
packages/myst-to-docx/src/schema.ts
packages/myst-to-tex/src/index.ts
packages/myst-to-tex/tests/basic.yml
packages/myst-to-typst/src/index.ts
packages/myst-to-typst/tests/basic.yml

You can now add `page-break` or `new-page` to block metadata to create a new page in `tex`, `typst`, and `docx`:
```md
+++ { "new-page": true }
My conclusion is on a new page.
```
For typst/docx both `page-break` and `new-page` add a page break. For tex, `page-break` and `new-page` insert `\pagebreak` and `\newpage`, respectively.
See #714

📄 Support new-page/page-break tags in tex/typst/docx

---

.changeset/silent-dancers-burn.md
.changeset/tame-apricots-doubt.md
docs/directives.md
docs/myst.yml
docs/tables.md
package-lock.json
packages/myst-directives/package.json
packages/myst-directives/src/index.ts
packages/myst-directives/src/table.ts
packages/myst-transforms/src/html.ts
packages/myst-transforms/tests/html.yml

Implements https://docutils.sourceforge.io/docs/ref/rst/directives.html#csv-table-1, addressing need on #189 
See #893.

✨ Add `csv-table` directive

---

docs/tables.md

This tiny PR just applies an HTML formatter to the table HTML, so that it is more readable (less wrapping)
*Before:*
```html
<table>
<tr><th rowspan="2">Projection</th><th colspan="3" align="center">Area in square miles</th></tr>
<tr><th align="right">Large Horizontal Area</th><th align="right" style="background: -webkit-linear-gradient(20deg, #09009f, #E743D9); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">Large Vertical Area</th><th align="right">Smaller Square Area<th></tr>
<tr><td>Albers Equal Area</td><td align="right">7,498.7</td><td align="right">10,847.3</td><td align="right">35.8</td></tr>
<tr><td>Web Mercator</td><td align="right">13,410.0</td><td align="right">18,271.4</td><td align="right">63.0</td></tr>
<tr><td>Difference</td><td align="right" …
```

:1234: Format table HTML in documentation

---

.changeset/early-insects-cross.md
docs/notebooks-with-markdown.md
packages/myst-cli/src/transforms/links.ts

This fixes #1135 by scoping the URL rewriting to non-static links.
I think what was happening was that the URL was being re-written as an internal link, but the `static` attribute was causing MyST to try and resolve that re-written link as a static item.
This change now prevents rewriting for static items (we'll always want those in the `static` endpoint).
I didn't add a test yet - not sure where that should go, would appreciate some pointers.

:bug: Always bundle static links

---

.changeset/red-wolves-nail.md
docs/embed.md
packages/myst-cli/src/frontmatter.ts
packages/myst-cli/src/process/file.ts
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/transforms/include.ts
packages/myst-transforms/src/frontmatter.ts
packages/myst-transforms/src/include.ts

Files loaded in the `include` directive previously retained their frontmatter in the `mdast` tree, resulting in an unwanted `yaml` code block. Additionally, everything in the `include` frontmatter was ignored (mostly we do want to ignore it, but for `.tex` source files, `include`s may have math macros, etc, that we need to inherit).
Now, we reuse the file loading functions from `loadFile` in the `include` directive. These functions remove and give access to file frontmatter. That means no more yaml blocks and we can inherit `math` and `abbreviations` into the parent file's frontmatter.

🧮 Frontmatter in `include` files removed, math/abbreviations maintained

---

.changeset/small-zoos-watch.md
packages/myst-transforms/src/include.ts

This updates `include` frontmatter implementation to match the documentation: https://github.com/executablebooks/mystmd/pull/1156/commits/81d7490074ea72b3c3ba94b07c0323b3a5a7aa8e

🧮 Ensure include file frontmatter takes priority

---

package-lock.json
packages/myst-toc/.eslintrc.cjs
packages/myst-toc/.gitignore
packages/myst-toc/README.md
packages/myst-toc/package.json
packages/myst-toc/src/guards.ts
packages/myst-toc/src/index.ts
packages/myst-toc/src/toc.ts
packages/myst-toc/src/types.ts
packages/myst-toc/tests/examples.spec.ts
packages/myst-toc/tests/test.yml
packages/myst-toc/tsconfig.json

In #1102, we identified the need for a new table of contents format.
This format must satisfy the following goals:
1. Easy to humanly read/write
2. Easy to programatically read/write
3. Expressive enough to represent complex trees
This PR is a WIP in that direction. The TOC schema can be build using 
```bash
npm run build:schema --workspace=packages/myst-toc
```
and then used with <https://www.jsonschemavalidator.net/> (or the CLI equivalent) to verify a TOC JSON blob.
Here's an example "complex" TOC:
```yaml
- title: Main
file: main.md
- title: Overview
children:
- file: overview-1.md
- file: overview-2.md
- url: https://google.com
- file: getting-started.md
children:
- file: getting-started-part-1.md
- file: getting-started-part-2.md
```
There are notably two kinds of "subtrees" in …

:ballot_box: Add new table-of-contents validator

---

.changeset/wet-beds-change.md
packages/myst-cli/src/build/init.ts
packages/myst-cli/src/build/meca/index.ts
packages/myst-cli/src/build/utils/collectExportOptions.ts
packages/myst-cli/src/process/site.ts
packages/myst-cli/src/project/fromPath.ts
packages/myst-cli/src/project/fromTOC.ts
packages/myst-cli/src/project/index.ts
packages/myst-cli/src/project/load.ts
packages/myst-cli/src/project/toTOC.ts
packages/myst-cli/src/project/toc.spec.ts
packages/myst-cli/src/utils/toc.ts
packages/myst-common/src/ruleids.ts
packages/mystmd/src/init.ts
packages/mystmd/src/options.ts

This is a clean-up PR, before we start doing surgery on TOC handling.

✏️ Rename Toc -> TOC

---

docs/dropdowns-cards-and-tabs.md

This documents the `:link:` option for cards and adds it to the short reference below.
I tried to use a reference to the card directive like `` {myst:directive}`card` ``, but that didn't resolve for some reason. Maybe that's why the reference is manually included in the page?
Either way:
- closes #1184

Document link option with card

---

.changeset/purple-spoons-visit.md
packages/myst-transforms/src/links/myst.ts
packages/myst-transforms/src/links/plugin.spec.ts
packages/myst-transforms/src/links/plugin.ts

If you define a cross-project reference like so `[](xref:key#identifier)`, it will be filled in with relevant text from the target. However, like this `<xref:key#identifier>`, the text remains "xref:key#identifier"
With this PR, that default text is removed, allowing relevant text to be filled later.

📐 Replace xref text when using angle brackets

---

docs/_toc.yml
docs/background.md
docs/guiding-principles.md

This adds the [guiding principles for MyST defined in this document](https://docs.google.com/document/d/1EMMCXmua894qDiBHPXGIbM485atwc1CTkKUhigQuCG0/edit?usp=sharing). It has been iterated on several times already by @choldgraf, @agoose77 , and @rowanc1 .
This is a snapshot of our current guiding principles, meant to both align our own team on the goals and impact we want MyST to have, and to provide visibility to the external world for our aspirations as a project.
- closes #1146

🧭  Add guiding principles page

---

.changeset/weak-bugs-press.md
packages/myst-cli/src/process/site.ts

This is possible to use the `image.*` as the src, if that is the case, an mp4 will be used by default for the web, but png for the static exports.

📺 Prefer video in web build if available

---

.changeset/gorgeous-sloths-change.md
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/transforms/ror.ts

This was a bad merge last night, and the link caching got refactored after. That is now using the same machinery.

🦁 Fix ROR naming

---

docs/admonitions.md
docs/code.md
docs/cross-references.md
docs/diagrams.md
docs/directives.mjs
docs/embed.md
docs/execute-notebooks.md
docs/exercises.md
docs/glossaries-and-terms.md
docs/math.md
docs/notebooks-with-markdown.md
docs/proofs-and-theorems.md
docs/quickstart-jupyter-lab-myst.md
docs/quickstart-myst-markdown.md
docs/reuse-jupyter-outputs.md
docs/syntax-overview.md

This does a few things around improving the display of directives and roles:
- Adds `{brackets}` around directives / roles when displayed
- Adds makes arguments and options display like `{directivename.argument}` (instead of just `argument`)
- Adds `{myst:directive}` and `{myst:role}` throughout a bunch of places

📖  Add brackets to directive and roles in docs

---

.changeset/lucky-shoes-search.md
packages/myst-cli/src/process/loadReferences.ts

Intersphinx xrefs did not resolve on first load (subsequent loads from disk are fine). This was particularly a problem for CI where it is always a first load.

🐛 Fix bug where intersphinx xrefs do not resolve on first load

---

.changeset/silent-tools-stare.md
packages/myst-transforms/src/enumerate.ts

This PR makes sure we don't accidentally delete the `identifier` on cross reference resolution.
This happened because we now share the `nodesFromMystXRefData` function (which gets the target node from remote mdast) between xref resolution and embed rendering. The latter requires `definitionTerms` to be wrapped in `definitionList`, so that function returns a `definitionList` node for "term" xrefs (but `identifier` is still on the child `definitionTerm`). The xref resolution code looked to that top-level target node for `identifier`, and in this case when none was found, removed it from the xref node...
Now, we just make sure `identifier` is never entirely removed.

🔧 Fix broken term xrefs by no removing identifier on xref node

---

.changeset/brown-ducks-speak.md
.changeset/ten-countries-live.md
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/transforms/embed.ts
packages/myst-transforms/src/links/check.ts

- On embed, the error message for non-existent reference vs. existing intersphinx reference is different
- On empty link text, error if this was caused by a non-existent reference, otherwise warn that text is empty

🚨Better error messages for broken xrefs

---

docs/myst.yml
docs/plugins.md
docs/requirements.txt
docs/templates.mjs
docs/website-templates.md

There's a hand-coded table of theme options, but the options have changed since it was written. ~This adds a little code-cell that pulls the latest YAML for each theme's configuration, and inserts it as a pandas table.~ This PR adds a new `myst:template` directive that pulls in the template information from <https://api.mystmd.org>.
It is current pretty simplistic, in a future iteration we could parse the output as markdown but that's blocked on:
This also documents the `site.actions` and `site.nav` options, since those exist but aren't documented anywhere.

:heavy_plus_sign: Add `myst:template` directive for documentation

---

docs/integrating-jupyter.md
docs/quickstart-myst-websites.md

This small PR just fixes some typos in our documentation.

:abc: Update Jupyter case and typos

---

.changeset/green-brooms-applaud.md
.changeset/large-peas-melt.md
.changeset/many-worms-know.md
.changeset/stupid-experts-pull.md
docs/frontmatter.md
docs/quickstart-myst-websites.md
packages/myst-cli/src/build/site/watch.ts
packages/myst-cli/src/config.ts
packages/myst-cli/src/project/load.ts
packages/myst-cli/src/store/reducers.ts
packages/myst-cli/src/store/selectors.ts
packages/myst-cli/src/store/types.ts
packages/myst-config/src/index.ts
packages/myst-frontmatter/src/utils/fillPageFrontmatter.spec.ts
packages/myst-frontmatter/src/utils/fillPageFrontmatter.ts
packages/mystmd/tests/exports.yml
packages/mystmd/tests/extend-config/proj-a/index.md
packages/mystmd/tests/extend-config/proj-a/myst.yml
packages/mystmd/tests/extend-config/proj-b/myst.yml
packages/mystmd/tests/extend-config/proj-c/macros.yml
packages/mystmd/tests/outputs/basic-site-config.json
packages/mystmd/tests/outputs/extend-config-config.json
packages/mystmd/tests/outputs/extend-config-index.json
packages/mystmd/tests/outputs/site-xrefs-config.json

This PR allows users to have project frontmatter defined in multiple files (all of the same `myst.yml` format), then the main `myst.yml` can bring in those other files under the top level `extends` key. A small example has been added to the docs.

✨ Add `extends` field to myst.yml for composing multiple yamls

---

docs/documents-exports.md
docs/embed.md

Inspired by this discussion:
- https://github.com/orgs/executablebooks/discussions/1182#discussioncomment-9540505
This adds a short description of how you can split a document across many parts. I figured it's worth documenting since this is a very common workflow. @matthewfeickert curious if you would have found this here?

📖 Document include for splitting a document across multiple parts

---

docs/execute-notebooks.md
packages/myst-execute/src/execute.ts
packages/myst-execute/tests/execute.yml

This was already supposed to be implemented, but a silly mistake prevented it from working.

:bug: Support `raises-exception` in cell execution

---

packages/myst-cli/src/project/utils.ts
packages/myst-cli/src/project/utils.yml

This PR fixes a bug with TOC writing, if the `toc:` entry contains a trailing comment.

:wrench: Match YAML section keys with comments

---

.changeset/large-ravens-shop.md
packages/myst-cli/src/build/utils/collectExportOptions.ts
packages/myst-cli/src/project/fromTOC.ts
packages/myst-cli/src/project/load.ts
packages/myst-cli/src/utils/resolveExtension.ts

Old jupyterbook-style `_toc.yml` files allowed (required...?) filenames without extensions. We are hoping to encourage explicit filenames with extensions in the new `myst.yml` toc.
This PR raises warnings/errors during toc resolution; there are 4 distinct errors:
- toc entry has an extension but does not exist
- toc entry has no extension and cannot be resolved to a file that exists
- toc entry has no extension and resolves to a single file (this is just a warning, but still surfaced to the user)
- toc entry has no extension and resolves to multiple files
This PR addresses https://github.com/executablebooks/mystmd/issues/1248
Note - legacy jupyterbook toc behavior and warnings/errors are unchanged.

🚨 Surface warnings during toc file extension resolution

---

.changeset/hot-actors-destroy.md
packages/myst-cli/src/build/build.ts
packages/myst-cli/src/build/init.ts
packages/myst-cli/src/build/legacy.ts
packages/myst-cli/src/build/site/manifest.ts
packages/myst-cli/src/build/site/start.ts
packages/myst-cli/src/build/utils/collectExportOptions.ts
packages/myst-cli/src/build/utils/localArticleExport.ts
packages/myst-cli/src/config.ts
packages/myst-cli/src/process/site.ts
packages/myst-cli/src/project/load.ts
packages/myst-cli/src/project/toTOC.ts
packages/myst-cli/src/project/toc.spec.ts
packages/myst-cli/src/session/session.spec.ts
packages/myst-cli/src/session/session.ts
packages/myst-cli/src/session/types.ts
packages/mystmd/src/clirun.ts

`extends` pr was added here to allow one myst.yml to extend another: https://github.com/executablebooks/mystmd/pull/1215
In that PR and in this issue https://github.com/executablebooks/mystmd/issues/336 the next step was allowing remote urls for the extend content so centralized data may be reused across users/projects. This PR adds that remote resolution step!
Biggest thing about this pr is going from sync to async at the config loading level; this means many functions are newly awaited... big diff minor impact.

🌎 Fetch config extensions from URL

---

.changeset/short-deers-explain.md
packages/myst-directives/src/table.ts

This PR ensures that we wrap captions in CSV-table nodes with the `caption` node.
Fixes #1273

:bug: Fix CSV-table caption

---

.changeset/sixty-suns-serve.md
packages/myst-cli/src/session/session.ts

Some of the DOI updates made slow requests very apparent - it feels like MyST is hanging when it's just waiting for a response.
This little PR adds a small log message to `session.fetch` that appears when a response takes more than 5s.

⏳ Add a log message for slow web requests

---

.changeset/seven-kangaroos-matter.md
docs/frontmatter.md
packages/myst-frontmatter/src/page/validators.ts
packages/myst-frontmatter/src/site/types.ts
packages/myst-frontmatter/src/site/validators.ts

@agoose77 @jmunroe as we were talking through this today in the pythia meetup, this brings tags up to the top level to support some of the work in Pythia, especially around galleries. This is necessary to support some of the work in collecting centralized resources.
Previously we could add tags to pages, but not projects. This opens up the possibility to tag a project and is more in line with how pythia, scipy-proceedings, and curvenote are dealing with projects that have this metadata at the project level.

🏷 Add tags to project frontmatter

---

.changeset/clean-chicken-own.md
packages/myst-cli/src/project/fromTOC.ts

Currently there is a constraint that the first toc entry must be a file; this becomes the project's `index` file. However, if this entry has a `file` and `children`, the children were previously just ignored. This PR adds an error if children are present on the index file.

🔧 Error if toc index file has children

---

docs/cross-references.md
docs/execute-notebooks.md
docs/table-of-contents.md

I have moved code to a backtick-fence rather than colon (some formatters kill whitespace not in a code block, and yaml was changing).

📖 Minor docs fixes

---

.changeset/polite-rings-divide.md
packages/myst-cli/src/transforms/dois.ts

We just released fixes for `403` errors from doi.org (#1285). Immediately, a bunch of `429 Too Many Requests` errors were encountered.
This PR attempts to address these new errors by limiting simultaneous requests to doi.org and improving messaging if DOI requests are slow (similar to messaging for slow requests in #1288).

🙉 Update doi fetching to resolve 429 too many request errors

---

.changeset/yellow-ghosts-deny.md
packages/myst-cli/src/build/site/manifest.ts
packages/myst-cli/src/config.ts
packages/myst-cli/src/session/cache.ts
packages/myst-templates/src/validators.ts

Previously, site template options of type "file" (e.g. `logo`) had to be local, existing paths. Now, they may be remote URLs, which are downloaded and cached to file first.
This partially addresses https://github.com/executablebooks/mystmd/issues/1296 (logo and logo_dark should be good; favicon is currently not working at all, I'll fix in a separate pr).

🌎 Allow remote files for template/site options

---

.changeset/cold-games-warn.md
packages/myst-cli/src/config.ts
packages/myst-frontmatter/src/utils/fillPageFrontmatter.spec.ts
packages/myst-frontmatter/src/utils/fillPageFrontmatter.ts

Previously, if `options` were defined in `myst.yml#site` and in an `extend` config file - the `extend` fields would be overridden. Now, they are combined, as we already do with project frontmatter. This is helpful as we are making site options more reusable: #1296

🤝 Combine site options when using config extend

---

.changeset/chilly-flies-appear.md
packages/myst-cli/src/build/site/manifest.ts

This should address https://github.com/executablebooks/mystmd/issues/1315 by:
- enabling webp conversion on project thumbnail and banner
- in the case where project thumbnail exists but does not have an optimized version, leaving the optimized thumbnail `undefined` instead of falling back to the index page's optimized thumbnail

🎆 Optimize project thumbnail/banner and fallback correctly

---

.changeset/hot-pillows-refuse.md
packages/myst-cli/src/session/session.ts
packages/myst-cli/src/session/types.ts
packages/myst-cli/src/transforms/dois.ts

This partially addresses https://github.com/executablebooks/mystmd/issues/1335 - now, the rate limiting previously implemented at a page level (and therefore easily exceeded during a build with multiple pages) is shared across the entire session.

🚦 Share doi request limiter across session

---

.changeset/lovely-beans-rescue.md
packages/tex-to-myst/src/figures.ts
packages/tex-to-myst/src/tex.ts
packages/tex-to-myst/tests/figures.yml

The `wrapfigure` latex environment is now supported by myst. It just creates a figure, exactly the same as the `figure` environment would, no consideration to wrapping at this point.

👩‍🎓 Add wrapfigure latex environment

---

.changeset/tidy-parrots-boil.md
packages/tex-to-myst/src/verbatim.ts
packages/tex-to-myst/tests/verbatim.yml

This PR addresses a very specific issue encountered here, where `code` captions were inheriting `{}` from the source tex: https://github.com/scipy-conference/scipy_proceedings/pull/916
Possibly a more general solution would be worth considering (Do these brackets show up elsewhere? Do they imply we should run tex-to-myst on the contents or something?). But for now, this quick fix improves the simplest cases where latex has `caption={My Caption}`.

🥌 Remove curly braces around properties in verbatim latex handler

---

.changeset/sour-jeans-happen.md
packages/tex-to-myst/src/frontmatter.ts
packages/tex-to-myst/src/utils.ts
packages/tex-to-myst/tests/commands.yml

Previously, `providecommand` was not supported and `renewcommand` did not care if the macro was already defined. Now: 
- `newcommand`: warns if macro is already defined (still overrides the previous command, to maintain previous behavior with MyST)
- `renewcommand`: warns if macro is _not_ already defined (either way, it sets the new command)
- `providecommand`: never warns - if macro is not defined, it sets the new command; if macro is defined, it does nothing

👩‍🎓 Differentiate behavior of newcommand, renewcommand, providecommand

---

.changeset/famous-squids-hide.md
packages/myst-cli/src/build/site/watch.ts
packages/myst-cli/src/config.ts
packages/myst-cli/src/project/fromTOC.ts

Recent updates broke `exclude` resolution on windows:
- `exclude` entries are supposed to use `/` forward slashes since they are "glob" patterns, regardless of platform (`\` back slashes are reserved as the escape character)
- However, during config load, these entries were resolved to absolute paths. For posix paths, this was fine: given `exclude: my/pattern` it would give `/my/full/path/my/pattern`. However for windows, it was more like `C:\my\full\path\my/pattern`.
- We did another pass to normalize all slashes to forward slashes - this fixed the windows paths so glob pattern matching was happy with them. _However_ it also turned escape characters into path separators...
- I removed this last normalization step, optimistically to prevent issues with escaped symbols. Unfortunately, this …

🔧 Fix exclude glob/path resolution

---

docs/table-from-file.html
docs/tables.md

This PR does two small things: 
1. Documents that `:label:` is needed for table numbering.
2. Introduces import table from file via `{include}`.
I've added an HTML table file too.
Closes #1241.

:chair: Update `table` docs

---

packages/myst-cli/src/transforms/images.ts

Fixes #1376 by making `imagemagick` part of the main red error message.

✅ Add helpful error information when image conversions fail

---

.changeset/late-ladybugs-raise.md
packages/myst-cli/src/transforms/images.ts

This should not error; uppercase image extensions are fine:

🚨 Do not warn on uppercase image extensions

---

docs/cross-references.md

We have a section on equation targets, but it's not really up-to-date; now we prefer using general Markdown links for references unless specific text is needed.

🪣 Remove specific reference to `eq` role in general docs

---

.changeset/eight-gifts-live.md
packages/myst-frontmatter/src/utils/fillPageFrontmatter.ts

This addresses https://github.com/jupyter-book/mystmd/issues/1362
Previously, when extending from multiple config files, the contributors and affiliations are lost if they are not used on any of the intermediate steps.
With this PR, all contributors and affiliations are persisted right until the final page resolution, when unused affiliations/contributors are removed.

✍️ Keep all contributors/affiliations until final page resolution

---

.github/workflows/ci.yml

Addresses the recent node bug described here: https://github.com/npm/cli/issues/7657

🐛 Pin node 22.4 in actions

---

docs/executable-plugins.md
docs/javascript-plugins.md
docs/markup.mjs
docs/markup.py
docs/myst.yml
docs/plugins.md
docs/unsplash.py
packages/myst-cli/src/config.ts
packages/myst-cli/src/executablePlugin.ts
packages/myst-cli/src/plugins.ts
packages/myst-common/src/ruleids.ts
packages/myst-config/src/project/types.ts
packages/myst-config/src/project/validators.ts

This PR fixes #1298 in a different way to #1325 by adding a new "executable" type of plugin (the approach taken in https://gist.github.com/agoose77/66700b2a172b4c11d4801f742534e4f7). Unlike #1325, this PR adds support for Python via an IPC mechanism (stdout, stdin).
#1325 and this PR are _not_ mutually exclusive; #1325 adds support for an in-process Python executor, which supports sharing stateful proxies between JS and Python. This PR, meanwhile, is fully decoupled and allows for further languages. Note that, unlike #1325, we do not vendor Python, so it is possible that users may define plugins whose environment is not sufficiently reproducible and thus see build errors.
> [!NOTE]
> #1325 will need to be rebased and updated to use this new mechanism for declaring plugin _types_.
To …

:computer: Add support for IPC-backed plugins

---

packages/myst-cli/src/build/build.ts
packages/myst-cli/src/cli/build.ts
packages/myst-cli/src/cli/clean.ts
packages/myst-cli/src/init/init.ts
packages/myst-cli/src/project/load.ts
packages/myst-cli/src/utils/index.ts
packages/myst-cli/src/utils/whiteLabelling.ts
packages/mystmd/src/index.ts
packages/mystmd/src/init.ts

The current plan for Jupyter Book is to have it be a thin white-labelled distribution of MyST-MD. The intention here is to avoid having to maintain a separate application with its own release cadence. Instead, we'll just re-skin MyST whilst making it clear that Jupyter Book _is_ MyST.
See also https://github.com/executablebooks/jupyter-book-myst/issues/3
This PR suggests one way to do this, by reading from the environment. Using this approach will require us to be careful in how we write our error messages. I added four functions:
- `binaryName()` - the name of the binary e.g. `myst` or `jupyter book`
- `readableName()` the human-readable name of the application, e.g. `myst` or `Jupyter Book (via MyST)`
- `homeURL()` - the URL of the application
- `baseConfigs` - a list of URLs / file …

🖊 Add support for white-labelling to MyST CLI

---

packages/myst-cli/src/build/utils/collectExportOptions.ts
packages/myst-cli/src/build/utils/getFileContent.ts
packages/myst-cli/src/process/file.ts
packages/myst-cli/src/process/site.ts
packages/myst-cli/src/project/fromPath.ts
packages/myst-cli/src/project/fromTOC.ts
packages/myst-cli/src/utils/resolveExtension.ts

This feature would be useful for enabling a nice workflow for pulling in mdast built from the Sphinx extension https://github.com/executablebooks/sphinx-ext-mystmd.

🐱 Add support for pre-parsed mdast-type files (`.myst.json`)

---

packages/myst-parser/src/myst.ts

when using myst-parser as a unified plugin, any options supplied by the user were not actually being used. This fixes that problem

feat: allow user options to apply to mystParser

---

.changeset/tough-crabs-watch.md
docs/frontmatter.md
packages/myst-frontmatter/src/downloads/downloads.yml
packages/myst-frontmatter/src/downloads/validators.ts
packages/myst-frontmatter/src/exports/exports.yml
packages/myst-frontmatter/src/exports/validators.ts
packages/myst-frontmatter/src/utils/fillPageFrontmatter.spec.ts
packages/myst-frontmatter/src/utils/fillPageFrontmatter.ts

We added the ability to compose yaml files when constructing your `myst.yml` file: https://github.com/jupyter-book/mystmd/pull/1215. This allows shared config, reducing duplication (and errors) across articles and just making authors' lives easier.
However, the original behavior was for fields to replace previous values. So if you define `keywords` in your `myst.yml`, any `keywords` defined in configuration files that the `myst.yml` `extends` are lost. Since then, we realized this meant `options` were not composed, so an option in your `myst.yml` could replace an inherited, totally unrelated option. This was fixed here: https://github.com/jupyter-book/mystmd/pull/1309. There were also some cases where contributors could be lost, addressed here: …

🐈 Concatenate list fields when extending project frontmatter

---

.changeset/silly-rivers-obey.md
docs/document-parts.md
docs/frontmatter.md
packages/myst-frontmatter/src/page/types.ts
packages/myst-frontmatter/src/page/validators.ts
packages/myst-frontmatter/src/project/project.yml
packages/myst-frontmatter/src/project/types.ts
packages/myst-frontmatter/src/project/validators.ts

MyST projects allow authors to define `parts` on each page, for example `abstract`, `acknowledgments`, etc. However, in many cases, these parts apply to the entire project, not a single page. For example, if my project is a scientific article with a myst page for each section, it doesn't really make any sense for the abstract to be defined on only one random page. See https://github.com/jupyter-book/mystmd/issues/1246
This PR lifts all the types / validation of `parts` from `page` frontmatter to `project` frontmatter, allowing authors to define parts directly in their `myst.yml`
Since this logic is inherited from project to page, the `page` behavior is unchanged. Also, the values are _not_ inherited from project to page, so if you define `parts.abstract` in your project, it will not be …

💇‍♀️ Allow parts in project frontmatter

---

.changeset/modern-wombats-boil.md
packages/myst-transforms/src/html.spec.ts
packages/myst-transforms/src/html.ts
packages/myst-transforms/tests/html.yml

Previously we were converting HAST to MDAST as full-documents, which was introducing paragraphs. 
`hast-util-from-util` always creates a `root` node, and `hast-util-to-mdast` introduces paragraphs for phrasing content inside a `root` node.
HTML nodes are `StaticPhrasingContent`, so we should already be e.g. inside a paragraph if we need one and thus can remove this wrapping? @rowanc1 you have touched this logic most recently.
Fixes #1400

#️⃣ Fix HTML tags in inline contexts

---

.changeset/early-colts-rhyme.md
packages/myst-cli/src/utils/imagemagick.ts

In #1388 we switched our ImageMagick command from `convert` (used by ImageMagick >= 6) to `magick` (used by ImageMagick 7). However, some linux distributions including, most notably, Ubuntu 22.04 - `ubuntu-latest` on github actions, still use ImageMagick 6.
This PR updates the invocation of ImageMagic commands to still use `convert` if that command is available and `magick` is not (`magick` still remains the preferred default if both are available).

🎆 Fall back to 'convert' command for imagemagick

---

.changeset/fuzzy-games-call.md
packages/myst-cli/src/project/fromPath.ts
packages/myst-cli/src/project/fromTOC.ts
packages/myst-cli/src/project/toc.pattern.spec.ts
packages/myst-cli/src/project/toc.spec.ts
packages/myst-toc/src/toc.ts

This PR addresses #1323 by:
1. Simplifying patterns to only generate `file` entries
2. Drop support for `pattern` entries with `children` -- in the schema, `pattern` entries can only be leaves.

📂 Drop folders in `pattern` expansion

---

docs/accessibility-and-performance.md
docs/admonitions.md
docs/background.md
docs/citations.md
docs/exercises.md
docs/external-references.md
docs/index.md
docs/math.md
docs/proofs-and-theorems.md
docs/quickstart.md
docs/table-of-contents.md
docs/website-templates.md

Closes #1094 (for now).
Also cleans up `JupyterBook` -> `Jupyter Book` in our docs.

📖 Improve MyST vs Sphinx

---

.changeset/real-clouds-jam.md
packages/myst-cli/src/build/docx/single.ts
packages/myst-cli/src/build/jats/single.ts
packages/myst-cli/src/build/md/index.ts
packages/myst-cli/src/build/tex/single.ts
packages/myst-cli/src/build/types.ts
packages/myst-cli/src/build/typst.ts
packages/myst-cli/src/build/utils/getFileContent.ts
packages/myst-cli/src/session/session.ts

Fixes #1415 
@fwkoch I'm not clear on what the purpose of `session.clone` is, so I'm not sure whether sharing a Jupyter session between all clones is reasonable. I *think* we want the Jupyter session manager to be a singleton so that we don't end up spinning up multiple local servers, but your input is useful here if I've got the wrong end of the stick.

:dart: Support `--execute` for building non-sites

---

.changeset/yellow-cherries-clap.md
packages/myst-cli/src/process/file.ts
packages/myst-common/src/ruleids.ts

This PR adds some validation for JSON-file input, and applies our frontmatter transforms.

:wrench: Tighten up JSON input

---

packages/mystmd-py/src/mystmd_py/main.py

There's no need for us to resolve this symlink, and some platforms like Snap use a single binary to dispatch aliased applications (i.e. symlink with name `node` points to `/usr/bin/snap`).
This PR changes the `Path.resolve()` to `Path.absolute()`, and fixes a mistake in the node version validation.
Fixes #1419

:snake: Don't resolve `node` symlink

---

docs/accessibility-and-performance.md

they were not labeled in anything rendered on the page, only the references and image file names

add  jupyter book/ quarto labels for lighthouse runs in captions

---

docs/glossaries-and-terms.md
docs/glossary.md

This adds documentation about indices to the index support PR. I tried to push to your branch directly but it was rejected so this is a PR for the same thing.
I wrote the docs because I wanted to see how the index support felt in actual usage. Hopefully this is helpful as well!

Add documentation to index support

---

.changeset/clean-pears-pull.md
packages/myst-cli/src/transforms/code.ts

If `code-cell` tags were not a list, MyST would print a nice error, but then crash anyway.
This PR simply adds a `return` if tags are not a list. This allows the build to continue, just ignoring the tags.

🐛 Prevent crash on non-list tags for code-cell

---

docs/deployment.md

This PR attempts to clarify the different ways that a MyST site can be deployed (and why you'd pick one over the other).
Closes https://github.com/executablebooks/mystmd/issues/927
There's more to cover here, such as deploying a MyST _server_ to Vercel, but I think this is a good start for our JB MVP docs.

🌐 Update deployment documentation to clarify deployment types

---

.changeset/early-donkeys-worry.md
.changeset/sweet-taxis-obey.md
packages/citation-js-utils/src/index.ts

This breaks on citations with more than one publisher.

🐛 Citations broken with trim when a list

---

.changeset/empty-rules-grow.md
docs/creating-pdf-documents.md
packages/myst-cli/src/transforms/raw.ts
packages/myst-directives/src/index.ts
packages/myst-directives/src/raw.ts
packages/myst-roles/src/index.ts
packages/myst-roles/src/raw.ts
packages/myst-spec-ext/src/types.ts
packages/myst-to-tex/src/index.ts
packages/myst-to-typst/src/index.ts
packages/mystmd/tests/exports.yml
packages/mystmd/tests/raw/.gitignore
packages/mystmd/tests/raw/index.md
packages/mystmd/tests/raw/myst.yml
packages/mystmd/tests/raw/outputs/index.json
packages/mystmd/tests/raw/outputs/out.tex
packages/mystmd/tests/raw/outputs/out.typ

This PR expands the `raw` node/role/directive behavior to allow tex- and typst-specific raw content that is only included in the respective export.
Currently, there is some existing `raw` functionality:
````
```{raw}
This inserts *raw* `unparsed` text in all contexts.
```
````
````
```{raw} latex
This allows you to use \textit{latex} in your markdown.
It will be \texttt{parsed} to MyST AST and included in all contexts.
```
````
(I feel like the latter is a little funny, since it says "raw" but it is parsing to AST... but that's ok for now.)
This PR adds `raw:latex` and `raw:typst` directives and roles that allow inserting typst and tex into your document that _only_ show up in their respective exports. So, for example, you can insert typst-specific formatting that is not required …

🍣 Add raw directives/roles for inserting tex/typst-specific content

---

.changeset/curly-ads-repeat.md
.changeset/kind-planes-rhyme.md
docs/frontmatter.md
packages/myst-frontmatter/src/biblio/biblio.yml
packages/myst-frontmatter/src/biblio/types.ts
packages/myst-frontmatter/src/biblio/validators.ts
packages/myst-frontmatter/src/utils/fillPageFrontmatter.spec.ts
packages/myst-frontmatter/src/utils/fillPageFrontmatter.ts
packages/myst-frontmatter/src/venues/types.ts
packages/myst-frontmatter/src/venues/validators.ts
packages/myst-frontmatter/src/venues/venues.yml
packages/myst-templates/src/validators.ts

Journals and Issues may have DOIs, in addition to articles. This PR adds `doi` to `venue` and `biblio`, for journals and issues respectively. It also adds `short_title` to `venue`, as often journals have an abbreviation.
I also tweaked `fillProjectFrontmatter` so `biblio` fields fill (rather than replacing the entire `biblio` object). This allows you to define `volume`/`issue`/`doi` in a shared config and `first_page`/`last_page` on an article.

🎓 Add DOIs for venue and biblio

---

docs/contribute-add-feature.md

the code block filename and emphasize-lines in  `docs/contribute-add-feature.md`,
turns some `packages/myst-transforms/src/index.ts` into `packages/myst-cli/src/process/mdast.ts` to keep the consistency with the context above and practice.
The previous version just mislead me at my first time to go through the guide

🖊️ Fix filename and highlight typo in `contribute-add-feature.md`

---

.changeset/spicy-dingos-knock.md
packages/myst-cli/src/build/utils/defaultNames.ts
packages/myst-cli/src/process/file.ts
packages/myst-cli/src/utils/fileInfo.ts
packages/myst-cli/src/utils/resolveExtension.spec.ts
packages/myst-cli/src/utils/resolveExtension.ts

Presently we use `path.parse` to strip away file extensions before slug generation. This PR replaces that logic with a custom `parse` function that understands the MyST extension list.
I'm not 100% sure whether talking about `.myst.json` as an _extension_ rather than a "suffix" is a poor choice of language, but we're walking down this path for now.

🐌 Fix slug generation for `.myst.json` files

---

.changeset/tasty-fireants-behave.md
packages/myst-parser/src/fromMarkdown.ts
packages/myst-parser/src/myst.ts
packages/myst-parser/src/tokensToMyst.ts
packages/myst-parser/tests/strikethrough.spec.ts

Ends up parsing out to a `delete` node and uses the rendering logic for the delete directive

␡ Enable strikethrough as markdownit extension

---

.changeset/ninety-jokes-tie.md
.changeset/twelve-dodos-shout.md
docs/glossaries-and-terms.md
packages/myst-frontmatter/src/project/project.yml
packages/myst-frontmatter/src/project/types.ts
packages/myst-frontmatter/src/project/validators.ts
packages/myst-transforms/src/abbreviations.ts
packages/myst-transforms/tests/abbreviations.spec.ts
packages/myst-transforms/tests/abbreviations.yml
packages/simple-validators/src/validators.spec.ts
packages/simple-validators/src/validators.ts

This ignores longer abbreviations:
```yaml
HR: Heart Rate
RHR: null
```
This would make: HR an abbreviation, but leave RHR alone. Previously there was no way to let the `HR` in `RHR` not be abbreviated with `R<HR>`.

🆎 Explicitly ignore longer abbreviations

---

docs/myst.yml
docs/quickstart-executable-documents.md
docs/quickstart.md

This adds a tutorial on executable content to our quickstart tutorials. It is based on a little demo that we gave the DeepLabCut team in Geneva earlier today. Folks were very interested to learn about the executable content in MyST, so we covered these topics.
~~This also updates our mystmd install instructions in the tutorials so that we just install `mystmd` straight away with `conda` rather than installing `nodejs` manually.~~ I've reverted this so that we can focus the quickstart conversation over in:
- #1454

🚀 Add executable docs tutorial

---

.changeset/witty-shirts-guess.md
packages/myst-cli/src/init/init.ts
packages/myst-cli/src/utils/git.ts

MyST was previously creating .gitignore's in subfolders of a git repository. We only want that to happen if the main repo does not already ignore `_build`.
This updates the logic to be based on `git check-ignore _build` rather than parsing the `.gitignore` in the current folder (and not traversing upwards, etc.)

🤫 Update gitignore based on `git check-ignore`

---

.changeset/silver-points-carry.md
docs/admonitions.md
packages/myst-directives/src/admonition.ts
packages/myst-directives/src/dropdown.ts
packages/myst-spec-ext/src/types.ts

Fixes #1319
Requires: https://github.com/jupyter-book/myst-theme/pull/452

🗃 Start admonitions in the open position

---

docs/index.md
docs/install-node.md
docs/installing.md
docs/myst.yml
docs/quickstart.md
docs/update-myst.md

Instead of going into detail about provisioning `node`, let's just go all-in on conda-forge; there's already a detailed article on installing manually

⏩ Simplify quickstart guide to use `mamba`

---

.changeset/dirty-bugs-drop.md
package-lock.json
packages/myst-cli/package.json
packages/myst-cli/src/process/myst.ts
packages/myst-ext-icon/.eslintrc.cjs
packages/myst-ext-icon/README.md
packages/myst-ext-icon/package.json
packages/myst-ext-icon/src/index.ts
packages/myst-ext-icon/tests/icon.spec.ts
packages/myst-ext-icon/tsconfig.json

This PR adds support for a subset of the icon syntax from sphinx-design. Although this new role supports the legacy role names such as `{fab}`, the preferred aliases are:
```
'icon:oct',
'icon:mrg',
'icon:mol',
'icon:mrd',
'icon:msp',
'icon:mtt',
'icon:fab',
'icon:far',
'icon:fas'
```

🖼 Add `icon` node

---

.changeset/dirty-bugs-drop.md
packages/myst-cli/src/process/myst.ts

I have published and added `ebp-bot` to the npm package. Changed this to a patch bump and removed unneeded import for now.

📦 Published `myst-ext-icon`

---

.changeset/rotten-tools-live.md
packages/myst-cli/src/store/types.ts
packages/myst-cli/src/utils/addWarningForFile.ts
packages/myst-cli/src/utils/imagemagick.ts

Only show webp warnings on debug by default. Can turn this back on with an errorRule.
Fixes https://github.com/jupyter-book/mystmd-quickstart/issues/1

🤫 Quiet webp warnings

---

flake.lock
flake.nix

This is a dev PR that adds `flake.nix` for Nix users. This makes it as easy to start running/developing MyST as `nix develop`. 
> [!NOTE]
> Developers will need to modify their NodeJS prefix in order for `myst` to be found on `PATH`
I will take responsibility for keeping this up to date, and it's only intended as a convenience for developers.

🤖 Add `flake.nix` for Nix users

---

packages/mystmd-py/src/mystmd_py/main.py

We use `os.exec` to make the MyST binary an invisible wrapper after startup. However, on Windows this doesn't work as intended. So, this PR sets up a subprocess on Windows instead.
Fixes https://github.com/jupyter-book/mystmd/issues/1425

👷 Check `platform.system` to fix `myst` on Windows

---

docs/frontmatter.md
docs/notebooks-with-markdown.md

Add the a section about kernel spec and a section about jupytext. following issue #1372

🔬 Improve documentation for kernel spec and cell blocks

---

.changeset/sour-apes-swim.md
docs/website-templates.md
packages/myst-cli/src/build/html/index.ts
packages/myst-cli/src/build/site/manifest.ts
packages/myst-cli/src/build/site/start.ts
packages/myst-cli/src/build/site/template.ts
packages/myst-cli/src/frontmatter.ts
packages/myst-cli/src/session/types.ts
packages/myst-frontmatter/src/page/types.ts
packages/myst-frontmatter/src/page/validators.ts

This enables per-page options for the site.
Picked up in the theme in https://github.com/jupyter-book/myst-theme/pull/472

💽 Add site options to each page

---

docs/installing.md
docs/quickstart.md

This puts the actual install code front and center, and de-emphasizes the knowledge of `nodejs` now that this is installed for you on both pip and conda-forge.
Also removed a section on separating the site config which is no longer relevant.

📖 Update to installation docs

---

.changeset/twenty-paws-ring.md
packages/citation-js-utils/src/index.ts

This addresses #1539 - `citation-js-utils` now looks at `accessed` for date in addition to `issued`.
Currently, this change eliminates the "Accessed..." text from the reference:

🎓 Replace n.d. with access date for urls in citations

---

.changeset/short-peas-love.md
packages/myst-cli/src/process/file.ts
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/process/notebook.ts
packages/myst-cli/src/process/site.ts
packages/myst-cli/src/transforms/types.ts

Aims:
* extend notebook processing to lift widget state from notebook metadata
* notebook metadata can be big and should be out-of-band
Todo:

💦 building widget state

---

.github/workflows/python-ci.yml
packages/mystmd-py/src/mystmd_py/main.py
packages/mystmd-py/src/mystmd_py/nodeenv.py

In some recent refactoring work, the `nodeenv` integration added some duplicate code. This PR removes that, and ensures that we're testing its usage.
I couldn't find an elegant way to create an environment without Node.js without using Docker. There's also Nix, but I know that it is not something people are familiar with. Although I am confident it would be simple to understand, if it goes wrong, things get hard.

🧹 Clean up `nodeenv` and add CI tests

---

.changeset/orange-dingos-promise.md
.changeset/unlucky-ties-reflect.md
docs/frontmatter.md
package-lock.json
packages/myst-cli/src/frontmatter.ts
packages/myst-frontmatter/package.json
packages/myst-frontmatter/src/licenses/licenses.spec.ts
packages/myst-frontmatter/src/licenses/licenses.yml
packages/myst-frontmatter/src/licenses/types.ts
packages/myst-frontmatter/src/licenses/validators.ts
packages/myst-frontmatter/src/page/page.yml
packages/myst-frontmatter/src/project/project.yml
packages/myst-to-md/src/utils.ts

Currently `license` values in MyST frontmatter are strict. They must be from the [SPDX license list](https://spdx.org/licenses/), referenced by ID, with no extra, custom information. This is probably how licenses _should_ be used - just pick a good, existing one and stick with that, don't try to embellish it or make up your own. However, in reality, this is not the case. Publishers, authors, etc often have their own license notes, urls for their license policies, or entirely new licenses.
This PR updates license validation in MyST to enable more flexibility when defining license.
First, you may define a license as an SPDX ID, as before. The behavior for this is unchanged: it will be automatically expanded to contain all the relevant license metadata, including name, url, OSI status, etc: …

🪪 Allow custom licenses outside SPDX

---

.changeset/slimy-feet-sit.md
docs/frontmatter.md
packages/myst-frontmatter/src/page/validators.ts
packages/myst-frontmatter/src/project/project.yml
packages/myst-frontmatter/src/project/types.ts
packages/myst-frontmatter/src/project/validators.ts

This PR just adds two more identifiers to frontmatter:
- `pmid` - PubMed ID, numeric value assigned to all PubMed records
- `pmcid` - PubMed Central ID, assigned to any records in the open-access PubMed Central database
These identifiers are added alongside existing identifiers `doi` and `arxiv`, and they are treated similarly during validation.

🏥 Add PubMed identifiers to frontmatter

---

.changeset/loud-parrots-rescue.md
docs/deployment-github-pages.md
packages/myst-cli/src/init/gh-actions/index.ts

I received a [deprecation notice](https://github.com/berkeley-cdss/curriculum-guide/actions/runs/11221254729) in GitHub actions that the artifact actions were old. I bumped `upload-pages-artifact` to v3 and that required bumping `deploy-pages` as well.
Via https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/ :
> Starting November 30, 2024, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact). Customers should update workflows to begin using [v4 of the artifact actions](https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/) as soon as possible.
Note that `upload-pages-artifact` …

✊ Bump action versions.

---

.changeset/curly-readers-compete.md
packages/myst-frontmatter/src/licenses/licenses.yml
packages/myst-frontmatter/src/licenses/validators.ts

This just makes two minor improvements to license validation - I'll point them out in the comments.

🪪 Improvements to spdx license validation

---

.changeset/twenty-rocks-divide.md
docs/directives.mjs
docs/exercises.md
packages/myst-directives/src/admonition.ts
packages/myst-directives/src/aside.ts
packages/myst-directives/src/bibliography.ts
packages/myst-directives/src/blockquote.ts
packages/myst-directives/src/code.ts
packages/myst-directives/src/div.ts
packages/myst-directives/src/dropdown.ts
packages/myst-directives/src/embed.ts
packages/myst-directives/src/figure.ts
packages/myst-directives/src/glossary.ts
packages/myst-directives/src/iframe.ts
packages/myst-directives/src/image.ts
packages/myst-directives/src/include.ts
packages/myst-directives/src/mdast.ts
packages/myst-directives/src/mermaid.ts
packages/myst-directives/src/mystdemo.ts
packages/myst-directives/src/table.ts
packages/myst-directives/src/utils.ts
packages/myst-ext-exercise/src/exercise.ts
packages/myst-ext-exercise/tests/exercise.spec.ts
packages/myst-ext-grid/src/index.ts
packages/myst-ext-proof/src/proof.ts
packages/myst-ext-tabs/src/index.ts

This PR tackles #1657. We will need an upstream `myst-theme` PR to ensure that these are actually set in the DOM.
I omitted the documentation directives `{myst:role}` et al. I didn't think they needed it.

🎁 Use `commonDirectiveOptions` in all directives

---

CONTRIBUTING.md

This PR is an attempt to slightly formalize my answer to this: https://github.com/jupyter-book/mystmd/pull/1650#issuecomment-2485557941
I'm totally open to feedback here - this is just the general rules I personally follow when bumping versions (and I always try to avoid any changes that don't just fall under `patch`...).
These rules are different from "official" semantic versioning which is basically - major: any breaking change, minor: any feature, patch: bugfix. But I'd argue in favor of maintaining the distinction between user-facing breaking change vs. developer-facing breaking change. (Possibly this suggests we should have different versioning on `mystmd` - "user-facing" - and `myst-cli` - "dev-facing" - where breaking changes can imply different levels of impact...)

👩‍💻 Proposed notes on versioning for contributors

---

.changeset/cold-elephants-vanish.md
package-lock.json
packages/myst-to-html/package.json
packages/myst-to-html/src/schema.ts
packages/myst-to-html/tests/schema.spec.ts

Addresses a sub-issue in #1676 for HTML exports of `keyboard` nodes.
I only test the hast here, because we should be able to rely on the ecosystem tests for hast-to-html imo.

⌨️ Add `keyboard` support to `myst-to-html`

---

.changeset/nervous-avocados-tell.md
packages/myst-transforms/src/links/plugin.spec.ts
packages/myst-transforms/src/links/plugin.ts

No hanging single characters on a link.
We put `<wbr/>` in HTML so that long URLs wrap at nice places. This wrapped and is especially noticeable in links ending with slash `mystmd.org/`, and then the slash would be on the next line alone.
This ensures that it needs at least three characters at the end before breaking the URL.

🔗 Improve link formatting

---

.changeset/beige-ways-learn.md
.changeset/clean-toys-work.md
.changeset/heavy-melons-count.md
.changeset/soft-shrimps-brake.md
.changeset/tidy-crabs-rhyme.md
.changeset/unlucky-adults-fry.md
packages/myst-to-typst/src/container.ts
packages/myst-to-typst/src/index.ts
packages/myst-to-typst/src/table.ts
packages/myst-to-typst/tests/cross-references.yml
packages/myst-to-typst/tests/figures.yml
packages/myst-to-typst/tests/tables.yml

This PR just has a handful of typst improvements from working on formatting a PDF export:
Newly supported small typst features include:
- ordered lists that do not start at 1
- table cell background color
Areas where typst now matches other myst exports better:
- cross-references maintain their children (e.g. `[see here](#fig1)` will render as "see here" in typst instead of the default "Figure 1")
- table legends now appear below tables
Areas where it is easier to customize typst:
- default "breakable" value for figures may be set in your source content
- "columnStyle" can be defined on a per-table basis, allowing injecting specific column widths (and possibly other table styles)

🔧 More typst export improvements

---

.changeset/few-lemons-dream.md
.changeset/red-planes-marry.md
docs/figures.md
packages/myst-cli/src/transforms/images.ts
packages/myst-cli/src/utils/ffmpeg.ts
packages/myst-cli/src/utils/index.ts
packages/myst-cli/src/utils/resolveExtension.ts

This PR adds support for avi and mov files if `ffmpeg` is installed. This plugs in to the existing image conversion logic, so the code changes are quite straightforward.

🎬 Add video conversions for avi, mov -> mp4

---

docs/math.md

📖 Spelling of `multiline` --> `multline`

---

.changeset/tricky-moles-enjoy.md
packages/myst-parser/src/tokensToMyst.ts
packages/myst-parser/tests/math.spec.ts
packages/mystmd/tests/basic-tex-math/input.md
packages/mystmd/tests/outputs/basic-tex-math.tex

🧮 Trim all math to ensure no new lines in latex output

---

docs/glossaries-and-terms.md

📖 Improve the documentation around abbreviations

---

.changeset/large-countries-cheer.md
packages/myst-cli/src/transforms/outputs.ts

If `output` has `html` media type that includes `image` node with no `url`, that output is entirely ignored. This approach is a little heavy-handed, but likely if we encounter an image with no url, the html is too complex to convert to markdown at all.
(This is a small part of the changes originally in https://github.com/jupyter-book/mystmd/pull/1701)

🎆 Prevent html outputs that translate to empty images

---

.changeset/new-birds-bake.md
packages/myst-to-typst/src/index.ts

This prevents cross-references to other pages in typst from being written as (invalid) links. They now remain as (correct) cross-references.
(This is a small part of the changes originally in https://github.com/jupyter-book/mystmd/pull/1701)

🔧 Fix project cross-references in typst

---

.changeset/nasty-pets-smell.md
packages/myst-to-typst/src/container.ts
packages/myst-to-typst/src/math.ts

For the most part, typst handles its own numbering. This PR forces typst to reset numbering where myst resets numbering. However, the way this PR determines where numbering resets is by looking at the `enumerator` - if this value is customized with `template` to not look like `#.#.#`, this counter reset will not happen...
(This is a small part of the changes originally in https://github.com/jupyter-book/mystmd/pull/1701)

🖐 Support restarting counter for each typst article in multi-article export

---

.changeset/rare-months-rest.md
packages/myst-cli/src/build/typst.ts

`parts` are allowed to be defined at the project level. For static exports, these were previously always ignored. This PR allows typst export to pick up on these `parts` when the typst export is also defined in the `myst.yml` file. In these cases, it is prioritized over page-level `parts`.
(This is a small part of the changes originally in https://github.com/jupyter-book/mystmd/pull/1701)

📄 Prioritize project-level parts for project-level typst export

---

.changeset/clean-meals-scream.md
.changeset/gorgeous-trainers-fetch.md
docs/myst.yml
docs/notebook-configuration.md
docs/notebooks-with-markdown.md
docs/settings.md
packages/myst-common/src/types.ts
packages/myst-execute/src/execute.ts
packages/myst-to-docx/src/schema.ts
packages/myst-to-jats/src/index.ts
packages/myst-to-md/src/misc.ts
packages/myst-to-tex/src/index.ts
packages/myst-to-typst/src/index.ts

See also:
- jupyter-book/myst-theme#517
- Fixes #1108

🙈 Notebook Cell Tags Documentation

---

docs/accessibility-and-performance.md
docs/admonitions.md
docs/background.md
docs/citations.md
docs/contribute-add-feature.md
docs/contribute-docs.md
docs/creating-pdf-documents.md
docs/execute-notebooks.md
docs/external-references.md
docs/index.md
docs/table-of-contents.md

This updates some of the MyST documentation to clarify references to Jupyter Book V1 vs. V2. Here are major highlights:
- It tries to include "V1" wherever it refers to the Sphinx stack version of Jupyter Book
- It includes more explanation about how Jupyter Book V2 is a distribution of MyST
- It cleans up some explanation about the relationship between MyST and Jupyter Book (which was based on V1)
- It adds guidelines for where to put different kinds of documentation (and closes https://github.com/jupyter-book/jupyter-book/issues/2239)

📖 Update documentation for Jupyter Book V2 vs V1 references

---

.changeset/dull-ravens-knock.md
packages/myst-to-typst/src/index.ts
packages/mystmd/tests/include-recursive/three.md
packages/mystmd/tests/math-macros/outputs/index.typ
packages/mystmd/tests/outputs/include-circular.typ
packages/mystmd/tests/outputs/include-recursive.typ

These lead to duplicates in multi-article exports.

🏷️ Do not label implicit heading nodes

---

.changeset/curvy-geese-retire.md
packages/myst-to-typst/src/index.ts
packages/myst-to-typst/src/proofs.ts
packages/myst-to-typst/tests/proofs.yml

📑 Add proof, solution, exercise defaults to typst export

---

.changeset/three-moles-give.md
packages/myst-to-typst/src/index.ts
packages/myst-to-typst/tests/lists.yml

📋 New lines in markdown lists are not written to typst

---

docs/executable-plugins.md

Correct file ending in doc for executable plugin

.py in file name in configuration instruction

---

.changeset/cool-meals-travel.md
.changeset/few-bulldogs-enjoy.md
packages/myst-to-typst/src/container.ts
packages/myst-to-typst/src/table.ts

Typst compiling fails for:
1. tables inside divs
2. tables with non-rgb cell colors (e.g. `"white"`)
This PR makes a couple tiny changes that fix those things.

🔧 Typst fixes for tables with divs and non-rgb cell colors

---

docs/execute-notebooks.md
docs/notebook-configuration.md
docs/notebooks-with-markdown.md

🏷️ Change `tags` type to match `jupytext`

---

.changeset/late-phones-jam.md
packages/myst-cli/src/build/html/index.ts
packages/myst-cli/src/utils/fetchWithRetry.ts
packages/myst-cli/src/utils/index.ts

Limits outgoing connections to five.
Fixes #1775
See also #1336

🔄 Fetch with Retry for HTML build

---

.changeset/quiet-toys-dream.md
docs/frontmatter.md
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/utils/addEditUrl.ts
packages/myst-frontmatter/src/project/types.ts
packages/myst-frontmatter/src/project/validators.ts

This is to enable an `Edit on Github` button in the theme. The `edit` url will be computed `github` is provided in the frontmatter and `git` is available (unless `edit` is explicitly set to `null`)

🔧 Add edit url to file frontmatter

---

.changeset/spotty-melons-hug.md
packages/myst-cli/src/transforms/inlineExpression.spec.ts
packages/myst-cli/src/transforms/inlineExpressions.ts

🗪 Removes quotes around `{eval}` outputs

---

.changeset/shy-spoons-exist.md
packages/myst-cli/src/transforms/inlineExpression.spec.ts
packages/myst-cli/src/transforms/inlineExpressions.ts

Quotes are semantically important things, so we should provide a way for users to preserve them if necessary. This PR ensures that we only strip quotes if the user does not specify (through various channels) that they should not be stripped.
I have no strong feelings on whether this field should be `strip-quotes` or `keep-quotes`.
Example notebook:
````markdown
---
kernelspec:
name: python3
display_name: python3
---
```{code-cell} python3
from IPython.utils.capture import capture_output
with capture_output() as c1:
display("hi", metadata={"strip-quotes": False})
with capture_output() as c2:
display("hi")
class CustomString:
def __init__(self, text: str, keep_quotes: bool):
self._text = text
self._keep_quotes = keep_quotes
def _repr_mimebundle_(self, include=None, exclude=None):
return ( …

💬 Preserve quotes in inline expressions upon request

---

.changeset/large-clouds-mix.md
packages/myst-parser/src/config.ts

🌎 Remove TLD of `.java` and `.zip` from linkify

---

.changeset/mean-seals-invent.md
packages/myst-transforms/src/enumerate.spec.ts
packages/myst-transforms/src/enumerate.ts

Addresses the issue brought up here: https://github.com/jupyter-book/mystmd/pull/1391#issuecomment-2616782516 - where `exercises` switched to continuous numbering with no change to the frontmatter.

🐛 Fix unwanted continuous numbering for some enumerated types

---

docs/documents-exports.md

📖 Improve documentation around export config in the myst.yml

---

.changeset/weak-readers-rule.md
packages/myst-cli/src/plugins.ts
packages/mystmd/tests/math-macros/outputs/index.typ

Closes #1813
It looks like the problem was here
https://github.com/jupyter-book/mystmd/blob/d1f8768eb4dbada0a370765ba696fbb3c00ba66f/packages/myst-cli/src/plugins.ts#L87
`fs.statSync` raises an error if there is no file/directory.
This PR adds an option so that `fs.statSync` returns `undefined` if there is no file, then handles that possibility when calling `isFile()`.
I see that there is another instance of `fs.statSync(...).isFile()` in `plugins.ts` that might cause similar problems.

🐛 Improve error message for missing javascript and python plugins

---

docs/installing.md

This PR updates the installation instructions to include `conda` as an option (in addition to `mamba`) for clarity as many end users of Jupyter Book have access to `conda`.

📖 Update to installing instructions to include conda

---

.changeset/dirty-ducks-tie.md
docs/execute-notebooks.md
docs/frontmatter.md
packages/myst-cli/src/process/mdast.ts
packages/myst-frontmatter/src/page/types.ts
packages/myst-frontmatter/src/page/validators.ts

This PR closes #1619 by adding a new `skip_execution` field to the page frontmatter. I don't anticipate it being a stable addition — we'll probably rethink at the very least _where_ it lives when we tackle #1498 and #1373. But, let's just get something in for now.

🚫 Add page frontmatter option to disable execution

---

.changeset/slimy-pumas-join.md
packages/myst-cli/src/process/site.ts

This addresses #1854 - With the introduction of continuous numbering, we now need to partially reprocess all pages if one changes (new numbering on one page may impact numbering on another). During this reprocessing, transformed thumbnails were attempting to re-transform, but the thumbnail transform is non-idempotent, so it was raising an error.
For this change, we now say "if one page changes, only reprocess the thumbnail for that page (even if you are doing other reprocessing for other pages)"

🔧 Fix errors about missing images on non-first builds

---

.changeset/forty-radios-hide.md
docs/website-templates.md
packages/myst-cli/src/init/jupyter-book/upgrade.ts

Fixes #1866 
I made `_toc.yml` a requirement for upgrading too, as this is a required file in JB1. I'm not sure why I didn't do this to begin with.

 📂 Set `site.options.folders: true` for JB upgrades

---

.changeset/hot-panthers-roll.md
packages/myst-directives/src/include.ts
packages/myst-parser/tests/directives/include.yml

Closes #813
The filters get applied for non-literal includes. The code change is just removing a conditional block which made an early return when `literal === false`. This does mean includes are slightly more expensive now, and I think some of the processing of filter/options doesn't make sense when `literal === false`. It does keep the code quite clean and simple though.
I've tested this locally, but haven't added any tests.
````markdown
start-after and end-before
```{include} ./data.txt
:filename: true
:start-after: BEGIN
:end-before: END
```
lines
```{include} ./data.txt
:lines: 2,3
```
literal with start-after and end-before
```{include} ./data.txt
:literal: true
:start-after: BEGIN
:end-before: END
```
Test "upgrading" to literal when `lang` is defined
```{include} ./data.txt
:lang: …

Handle unsupported options for include directive

---

.changeset/spotty-planets-fetch.md
docs/deployment.md
docs/myst.yml
docs/public/style.css
docs/website-style.md
docs/website-templates.md
packages/myst-cli/src/build/html/index.ts
packages/myst-transforms/src/blocks.ts

> [!WARNING]
> Depends upon #1864 to add support for `class` on blocks
This PR adds documentation for the proposed jupyter-book/myst-theme#540

💇 Add documentation on `site.options.style`

---

docs/proofs-and-theorems.md

See title!
This fixes our docs which refer to legacy options because they're not pulling from the directive definition.

✏️ Use `myst` directive with `proof` option definitions

---

.changeset/brave-dragons-pump.md
docs/directives.md
packages/myst-cli/src/build/site/manifest.ts
packages/myst-cli/src/build/utils/projectManifest.ts
packages/myst-cli/src/process/mdast.ts
packages/myst-cli/src/process/site.ts
packages/myst-directives/src/index.ts
packages/myst-directives/src/indices.ts
packages/myst-directives/src/toc.ts
packages/myst-transforms/src/enumerate.ts
packages/myst-transforms/src/index.ts
packages/myst-transforms/src/toc.spec.ts
packages/myst-transforms/src/toc.ts

This PR addresses https://github.com/jupyter-book/mystmd/issues/1800
It introduces a new `toc` directive that, for site builds, is transformed into a list-based table of contents. You may specify `context` to switch between project, page, and section contents. The default context is project.
- `project` - for this context, entries in the table of contents are all project pages and folders. You may also use `toctree` as an alias for the directive. (This provides partial functionality similar to the sphinx toctree directive, although that directive allows you to _define_ child pages and their order. The MyST toc directive is only for display and entirely dependent on the toc structure defined in the `myst.yml` file. See sphinx toctree here: …

✨ New table of contents directive

---

CONTRIBUTING.md

The build process uses unix commands that probably won't work in cmd.exe. Switching to WSL, or a unix like shell such as Git Bash and configuring npm to use it solves the issue.

📖 Adds note on Windows builds to Contribution guide

---

.changeset/config.json
.changeset/thick-terms-dance.md
docs/versions.md
packages/myst-cli/src/spec-version.ts
packages/myst-migrate/src/migrations.ts
packages/myst-migrate/src/tests/version_1_2.spec.ts
packages/myst-migrate/src/v2_blockClasses.ts
packages/myst-transforms/src/blocks.ts

Blocks could previously define class on `block.data?.class`, this has been explicitly moved to `block.class`.

🚀 Update the `SPEC_VERSION` for `block.class`

---

.changeset/brave-cameras-count.md
.gitignore
packages/myst-cli/src/build/site/start.ts
packages/myst-cli/src/build/site/template.ts
packages/myst-cli/src/cli/options.ts
packages/myst-cli/src/cli/start.ts
packages/myst-templates/src/template.ts
packages/myst-templates/src/validators.ts

- This command line argument uses the same mechanism as the manifest loader
- The theme manifest currently has a files section that includes build products that are not present when working locally. This commit therefore drops the `files` key from the `template.yml`.
- When determining whether to obtain the manifest locally or download it, we currently check whether `template_dir/node_modules` exists; again, this is not the case when working locally, and merely wanting to point to a different manifest file, so this check was simplified to only check for the presence of the manifest file itself.
Since I do not know the project history, removing `files` and the check for `node_modules` may well violate some known constraint. Happy to be pointed in a better direction!

⌨️ Add command line argument to `myst start` for selecting template

---

packages/myst-cli/src/init/gh-actions/index.ts

Extends the existing comment to help users who may change deployment options after their original setup, as they may encounter CSS issues.
I just spent an hour tracking this down - while the comment was there as a hint, I wasn't quite sure this was the problem. I just added a slightly more explicit note as my situation may happen again: a user who initially tests as site on `<username>.github.io`  and later decides to move to `theirwebsite.org`, sets everything up correctly for custom domains on GH and their DNS machinery, but gets a borked website with zero CSS.
I'm also happy to add more to the docs if desired, though I didn't quite stumble due to docs issues, it really was this action that threw me for a loop.

Clarify BASE_URL instructions in GH action for custom domains.

---

packages/myst-cli/src/init/gh-actions/index.ts

✍️ Escape backticks in `init --gh-pages` template

---

.changeset/long-fishes-change.md
packages/myst-cli/src/transforms/links.ts

This makes a fix to the checkLinkTransform, that processes `card` nodes in addition to `links`. Card nodes can have optional `url` properties, which when undefined cause a fatal error.
Reproduce using:
```markdown
:::{card}
some content
:::
:::{card}
:link: https://curvenote.com
some content linked
:::
```
and running `myst build --check-links`, the first card will cause the build failure.

👨🏻‍🔧 fix check link transform for cards

---

.changeset/selfish-news-love.md
packages/myst-cli/src/transforms/crossReferences.ts

I created this PR when working on output upgrading a few months ago. It's a simple change to make it easier to determine why xref processing fails.

🪄 Improve error handling during cross reference resolution

---

.changeset/weak-bananas-cover.md
packages/myst-cli/src/process/mdast.ts

Subsequent PRs that look to introduce Markdown output support from code-cells will want to make use of as much of the AST transform pipeline as possible. This PR moves kernel execution before much of the basic transforms, so that we can later do this. It should not break / change anything.

🔙 Move execution transform earlier in mdast pipeline

---

docs/md-vs-ipynb.md
docs/myst.yml

This is a brief guide to give users an idea for when to choose between markdown-based notebooks and `ipynb` files. It's inspired by a conversation with @bsipocz in [this discussion thread](https://github.com/orgs/executablebooks/discussions/1262#discussioncomment-12857027). The goal of this page isn't to tell users what to do, but to help them understand the pros/cons of each approach, and when they should consider using each format.
@bsipocz if you have any thoughts (recognizing that we can't be _too_ opinionated here, I'd rather give information than tell people they're "doing it wrong") on how we can make this content more useful, please provide suggestions!

Add a brief guide to choosing between `.md` and `.ipynb`

---

.husky/pre-commit
docs/developer.md
package.json

For folks without VSCode, this could help by providing a git pre-commit hook that is run via eslint and prettier to fix things up.
----
Running `npx husky` installs the git pre-commit hook.
From then on, whenever you make a commit, eslint and prettier will be invoked, re-formatting the commit automatically.
If you want to revert this behavior, remove `core.hooksPath` from `.git/config`.

✅ Add husky and lint-staged to help devs fix code before pushing

---

docs/developer.md

This adds brief instructions for how anybody can make a release on GitHub and share with others in the Jupyter community. It's a quick write-up of a few steps that I followed to make the release here: 
https://github.com/jupyter-book/mystmd/releases/tag/mystmd%401.3.26
I'm adding it both to reduce the amount of arbitrary decision-making and writing for new releases, and also to provide guidelines so that any other team member can make releases more easily!

📖 Add guidelines for publishing a release to GitHub

---

docs/contribute-docs.md

This updates our documentation infrastructure to make it more transparent for our team to understand how the docs at mystmd.org are hosted, how to update them, and how it all works.
I may have gotten some things factually wrong, so it would be great to get a review from somebody with more knowledge than me to make sure it is correct.
- Depends on https://github.com/jupyter-book/mystmd.org/pull/27 for the dispatch option

Update documentation about our documentation infrastructure at mystmd.org

---

.changeset/thin-owls-begin.md
packages/jtex/tests/download.spec.ts
packages/myst-templates/src/download.spec.ts
packages/myst-templates/src/download.ts
packages/mystmd/tests/indices/outputs/index.tex
packages/mystmd/tests/math-macros/outputs/index.tex

Closes #1714 by changing the default template, as suggested in https://github.com/jupyter-book/mystmd/issues/1714#issuecomment-2767357252
We could also make a MyST-ified version of the Curvenote template, but I think this is a simple enough start.

🔄 Change default LaTeX template to `plain_latex`

---

.changeset/wise-ducks-cough.md
packages/myst-cli/src/cli/build.ts
packages/myst-cli/src/cli/options.ts
packages/mystmd/src/templates.ts

In pursuing #2033, I discovered that the error messages for `myst templates download` were not intuitive.
This PR closes #2033 by rewording the errors to make recovery steps clearer.

⚠️ Improve error messages for `myst templates download` command

---

docs/website-navigation.md
docs/website-style.md

This adds some light documentation for how you can make content fill to the right sidebar area using the CSS grid classes. It took me a while to figure this one out so I thought it'd be helpful to add.

Document how to put content in the right sidebar area

---

docs/contribute-docs.md
docs/overview.md

Removes these warnings:
```
⚠️  overview.md:50 Legacy syntax used for link target, please prepend a '#' to your link url: "admonition-github-compatibility"
The link target should be of the form `[](#target)`, including the `#` sign.
This may be deprecated in the future.
⚠️  contribute-docs.md:171 Legacy syntax used for link target, please prepend a '#' to your link url: "export-excalidraw"
The link target should be of the form `[](#target)`, including the `#` sign.
This may be deprecated in the future.
```

⚠️ Remove docs warning on legacy link syntax

---

.changeset/thick-geese-sing.md
packages/myst-directives/src/code.spec.ts
packages/myst-directives/src/code.ts

Fixes jupyter-book/jupyter-book#2361

🧮 Improve `emphasize-lines` to allow for ranges

---

.github/workflows/label.yml
.github/workflows/release.yml

This PR adds a simple workflow that ensures PRs have a set of particular labels before they can pass:
- enhancement
- bug
- documentation
- maintenance
- release

🤖 Add required label workflow

---

docs/authorship.md
docs/frontmatter.md
docs/myst.yml

This splits out a little bit of the authorship reference documentation into a dedicated "Authorship" section in the user guide. The goal here is to separate out the "reference docs" (which are appropriately listed under `Reference`) and the how-to and conceptual docs (which are hard to find right now because they're embedded in the big reference docs page).
This doesn't change any content, just tries to make a subset of it more modular and discoverable, with cross-references to our reference docs for more complete lists.
It's a complement to #2021 which is focused on adding more social media frontmatter support

Add a dedicated authorship and affiliations section

---

docs/contribute-docs.md

I think this addresses the comments that @rowanc1 made as a follow up to https://github.com/jupyter-book/mystmd/pull/1958
It tries to clarify where the theme infrastructure vs. the content deployment infrastructure is located

📖 Update documentation on docs contributions

---

package-lock.json
package.json
turbo.json

This tiny PR just updates `turbo` from the previous 2-year-old version. This does not impact any of the packages, just the monorepo build, so hopefully it's non-controversial.

📦 Bump turbo repo

---

.changeset/gentle-feet-relax.md
packages/myst-cli/src/config.ts
packages/myst-cli/src/plugins.ts
packages/myst-cli/src/process/file.ts
packages/myst-cli/src/session/session.ts
packages/myst-cli/src/session/types.ts
packages/myst-common/src/types.ts

This addresses https://github.com/jupyter-book/mystmd/issues/2071 - Previously, we were processing `parts` files before `plugins` were loaded on the `session`. This ended up caching an empty list of `plugins` which was then never repopulated. Plugins were just silently gone!
@stefanv had a first pass at addressing this here https://github.com/jupyter-book/mystmd/pull/1925 - that PR prevented caching the empty list; however, `plugins` were still not loaded before `parts` processing, so referencing a plugin in a part would fail.
In this PR, I now call `loadPlugins` earlier, while processing project fronmtatter. This happens before any `parts` or other files are processed, so now `plugins` are available during `part` processing and are never cached as an empty list.

🔌 Load plugins earlier, before parsing frontmatter parts

---

.changeset/rotten-needles-cough.md

This ensures that the frontmatter package is re-deployed with a proper version bump in the simple-validators dependency, captured in #2105 and #2021

🩹 Add changeset for `myst-frontmatter`

---

docs/deployment-httpd.md
docs/deployment.md
docs/myst.yml

Adds documentation for static web page deployment on Apache httpd, as discussed in #2086 .

Add doc for Apache httpd deployment

---

.changeset/chilled-onions-jump.md
packages/myst-cli/src/transforms/images.ts

Only when image is not found.
Fixes #2123

⚠️ Fix warning about `.*` image extension

---

docs/document-parts.md
docs/myst.yml
docs/website-navigation.md

This improves our documentation around both site parts, how parts work in general, and cross-links for how to use them to define footers.

Clarify site parts for footers

---

.changeset/violet-ants-try.md
packages/myst-cli/src/transforms/crossReferences.ts

In this log message, "Updated link text" has an additional space of indentation. I don't _think_ this is intentional.
```
📖 Built content/index.md in 63 ms.
🪄  Updated link text for 1 external MyST reference in 4.42 ms seconds
```

➡️ Indentation of log message in `crossReference`

---

.changeset/famous-mayflies-camp.md
packages/myst-cli/src/transforms/crossReferences.ts

With this PR,
```
🪄 Updated link text for 1 external MyST reference in 151 ms seconds
```
is now
```
🪄 Updated link text for 1 external MyST reference in 142 ms
```

⏱️ Remove time unit from timing message

---

.changeset/strange-beans-listen.md
packages/myst-cli/src/init/gh-actions/index.ts
packages/myst-cli/src/utils/whiteLabelling.ts

I noticed that running `jupyter book init --gh-pages` refers to myst. This PR fixes that under Jupyter Book 2, so that users install the proper package.
This still isn't perfect — the `--curvenote` option uses a Curvenote action, which theoretically doesn't know about Jupyter Book. But I think that's a problem for another day.

🎬 More whitelabelling for `myst init`

---

docs/index.md

I am still having a hard time to find where the upgrade docs is located, and even google is not very useful to find it.

DOC: Adding upgrade guide link

---

.changeset/purple-penguins-dress.md
packages/myst-transforms/src/admonitions.ts
packages/myst-transforms/src/index.ts

Exposes the test function to format admonition headers. No functional changes.

🔄 Refactor admonition parsing to expose header function

---

docs/frontmatter.md

One-liner typo fix for the documentation: the correct SPDX license identifier for CC BY-NC-SA 4.0 is `CC-BY-NC-SA-4.0`, not `CC-BY-N-SA-4.0` (missing the `C`). Without the `C`, the license information is not found and the license information on rendered page is undefined.

📖 Fix typo in frontmatter.md for CC-BY-NC-SA license

---

.changeset/smart-feet-jump.md
packages/myst-parser/package.json
packages/myst-parser/src/fromMarkdown.ts
packages/myst-parser/src/tokensToMyst.ts
packages/myst-parser/src/transforms/index.ts
packages/myst-parser/src/transforms/listItemParagraphs.spec.ts
packages/myst-parser/src/transforms/listItemParagraphs.ts
packages/myst-parser/src/tsconfig.json
packages/myst-parser/tests/commonmark.spec.ts
packages/myst-parser/tests/directives/table.yml
packages/myst-parser/tests/myst.spec.ts
packages/myst-parser/tests/tasklists.spec.ts
packages/myst-to-tex/src/index.ts
packages/myst-to-tex/tests/basic.yml
packages/myst-to-typst/tests/basic.yml
packages/mystmd/tests/indices/outputs/recipes.json

This transforms listItems after parsing with markdown-it, to ensure that they are mdast compliant. This is important in formatting (e.g. #1948). Without this each inline element of the list item will be on a different line.
Fixes #1957

🐛 mdast lists need to be in paragraphs

---

.changeset/smooth-insects-exercise.md
packages/myst-parser/src/transforms/listItemParagraphs.spec.ts
packages/myst-parser/src/transforms/listItemParagraphs.ts

Before `footnoteReferences` are not treated as inline elements:
After:

🐛 List elements with `footnoteReference`s as children

---

.changeset/light-coins-draw.md
packages/myst-cli/src/build/site/logger.ts
packages/myst-cli/src/build/site/start.ts

Pass the host name through correctly to the theme and ensure that the default configuration will only serve on localhost unless a host is specified and passed through explicitly with `--keep-host`.
See also: jupyter-book/myst-theme#646
Fixes #2254

🔐 Improve security for localhost

---

.changeset/honest-jeans-enjoy.md
packages/myst-cli/src/build/site/start.ts

🔎 Set `HOST` environment variable to `127.0.0.1` on ReadTheDocs CI

---

.github/labeler.yml
.github/workflows/auto-label.yml
.github/workflows/enforce-label.yml

Enforcing label requirements is a good way to ensure that our release notes are easy to generate. Although it is not directly harmful to contributors that the current workflow requires contributors with permissions to assign these labels, we could make this easier!
This PR fixes #2325 by adding labels according to the path and/or branch name.

🏷️ Add autolabeler rules
