- README.md
Add install instructions, please modify or ask questions to get up and running and we can clarify the readme!
> 📖  DOCS: Add developer install instructions

- src/index.ts
> Improve initialization options; pass in externally

- package.json
Add keywords to the package for better searching on npm.
> 📚 DOCS: Keywords for package

- src/roles/index.ts
> 🐛 BUG: Safari regexp negative look behind

- fixtures/math.ams.integration.md
- fixtures/math.ams.md
- fixtures/math.md
- index.html
- src/index.ts
- src/math/amsmath.port.yaml
- src/math/amsmath.ts
- src/math/math.ts
- src/math/utils.ts
- src/roles/math.ts
- tests/fixtures.spec.ts
Adds AMS math, similar to https://github.com/executablebooks/markdown-it-py/pull/12
> ⚡️ Add amsmath parsing

- docs/_config.yml
- docs/index.md
> 📖 DOCS: Add demo page and badges

- package-lock.json
- package.json
- src/mdast/tokensToMyst.ts
- src/mdast/transforms.ts
Is a new bug with the latest version of unist-util-map
> 🐛 Do not assign undefined to node children

- package-lock.json
- package.json
- src/mdast/index.ts
- src/mdast/transforms.ts
- tests/transforms/converthtml.spec.ts
- tests/transforms/converthtml.yml
> ✨ NEW: Transform for converting html nodes to mdast

- package-lock.json
- package.json
- src/myst.ts
- src/plugins.ts
- src/types.ts
Requires a release of:
- https://github.com/executablebooks/markdown-it-docutils/pull/41
See also:
#54 
Todo:
> 🐛  Use colonFence plugin from myst-extras

- docs/creating-pdf-documents.md
- docs/curvenote.yml
- docs/index.md
- packages/jtex/docs/curvenote.yml
- packages/myst-cli/docs/curvenote.yml
- packages/myst-to-tex/docs/curvenote.yml
- packages/myst-transforms/docs/curvenote.yml
This updates the docs settings to be inline with the current website configs.
> 📖⚙️ Update settings and links for internal docs

- package-lock.json
- packages/myst-to-docx/package.json
- packages/myst-to-docx/src/utils.ts
This was a hangover from using prosemirror-docx as the starting place for myst-to-docx.
> 🐛 Remove dependence on @curvenote/schema

- .changeset/sour-candles-yawn.md
- packages/myst-cli/src/build/tex/single.spec.ts
- packages/myst-common/src/extractParts.spec.ts
- packages/myst-common/src/extractParts.ts
> 💇‍♀️ Modify extractPart: no longer support tags

- .changeset/great-impalas-double.md
- package-lock.json
- packages/myst-cli/jest.config.cjs
- packages/myst-transforms/jest.config.cjs
- packages/myst-transforms/package.json
- packages/myst-transforms/src/basic.ts
- packages/myst-transforms/src/index.ts
- packages/myst-transforms/src/math.spec.ts
- packages/myst-transforms/src/math.ts
> ✈️ Lift equations out of paragraphs

- packages/myst-cli/src/transforms/images.ts
- packages/myst-cli/src/utils/inkscape.ts
This is to fix an error when `inkscape` is not available, but `imagemagik` is. We now fallback from PDF --> PNG, rather than error.
> 🎇 Improve fallback when inkscape is not available

- .changeset/khaki-ducks-turn.md
- packages/myst-common/src/utils.ts
Small change for future changes, mostly a typescript thing!
> 🤫 Allow toText to take a null

- packages/citation-js-utils/package.json
- packages/citation-js-utils/tsconfig.base.json
- packages/intersphinx/package.json
- packages/intersphinx/tsconfig.json
- packages/jtex/package.json
- packages/jtex/tsconfig.base.json
- packages/myst-cli-utils/package.json
- packages/myst-cli-utils/tsconfig.json
- packages/myst-cli/package.json
- packages/myst-cli/tsconfig.json
- packages/myst-common/package.json
- packages/myst-config/package.json
- packages/myst-config/tsconfig.json
- packages/myst-frontmatter/package.json
- packages/myst-frontmatter/tsconfig.json
- packages/myst-spec-ext/package.json
- packages/myst-spec-ext/tsconfig.json
- packages/myst-templates/package.json
- packages/myst-templates/tsconfig.json
- packages/myst-to-docx/package.json
- packages/myst-to-docx/tsconfig.json
- packages/myst-to-jats/package.json
- packages/myst-to-jats/tsconfig.json
- packages/myst-to-tex/package.json
- packages/myst-to-tex/tsconfig.json
- packages/myst-transforms/package.json
- packages/mystjs/package.json
- packages/mystjs/tsconfig.json
- packages/simple-validators/package.json
- packages/simple-validators/tsconfig.json
`option-click` now brings you to the source location rather than the type
> 🧙‍♂️ Improve source-maps for development

- packages/myst-cli/src/build/site/manifest.ts
- packages/myst-cli/src/process/site.ts
- Move exports to page json on site build (instead of site manifest)
- Add the source file at the top of the exports list.
> 🌎 Publish source file and exports

- .changeset/tame-cougars-flash.md
- packages/myst-cli-utils/src/logger.ts
- packages/myst-cli-utils/tsconfig.json
> 🐛 Path replacement on windows for logging

- .changeset/thirty-snakes-swim.md
- packages/myst-to-tex/src/index.ts
> 🐛 LaTeX: Capture framed environment

- .changeset/gentle-panthers-smell.md
- packages/myst-cli/src/build/site/logger.ts
> 🐛 Catch and mute spurious warnings

- .github/ISSUE_TEMPLATE/0-bug-report.yml
- .github/ISSUE_TEMPLATE/1-feature-request.yml
- .github/ISSUE_TEMPLATE/config.yml
> 🐛📖 Issue templates for `.github`

- .changeset/curvy-bulldogs-play.md
- packages/myst-cli/src/transforms/images.ts
- packages/myst-cli/src/utils/imagemagick.ts
This converts PDFs to PNGs in the build. They now work for Word and web export.
> 🎇 Support for PDF images

- docs/cross-references.md
- docs/figures.md
- docs/quickstart-myst-websites.md
This adds documentation for #156 and #160
> 📚 Document notebook cell labels and separate site/project configs

- .changeset/curly-pans-own.md
- README.md
- docs/analytics.md
- docs/dropdowns-cards-and-tabs.md
- docs/index.md
- docs/quickstart-myst-websites.md
- packages/jtex/docs/contribute-a-template.md
- packages/jtex/docs/create-a-latex-template.md
- packages/jtex/docs/index.md
- packages/myst-cli/README.md
- packages/myst-cli/src/build/init.ts
- packages/myst-templates/src/download.spec.ts
- packages/myst-templates/src/session.ts
- packages/myst-to-jats/tests/basic.yml
> 🔗 Update domain to myst-tools for all links.

- packages/myst-cli/src/build/site/watch.ts
This addresses #183 - creating or deleting markdown files now reloads the entire project, adding/removing pages for these files. Previously this full reload only happened when the `_toc.yml` file was updated or a new `bib` file was added.
This likely introduces some inefficiencies - we are reloading everything when we really only need to reload the project structure... but I suspect in practice, things are fast enough to not worry - this still happens infrequently compared to page edits. Something to keep an eye on, though.
One other small change is renaming the `triggerReload` argument to `serverReload`, hopefully eliminate some confusion with page vs. project vs. server reload.
> 🔄 Reload project on all created/deleted files during watch

- docs/creating-pdf-documents.md
- docs/creating-word-documents.md
- docs/index.md
- docs/quickstart-myst-documents.md
- packages/jtex/docs/create-a-beamer-template.md
- packages/myst-cli/src/session/session.ts
This adds more relevant links from the front page of the docs, and corrects a few bugs in the docs users have reported.
> 📖 Improve onboarding documentation

- docs/quickstart-myst-documents.md
Suggestions from @kolibril13, opened up #217 to track emoji support.
> 📖 Improve quickstart with warnings

- .changeset/tidy-cooks-confess.md
- packages/myst-common/src/utils.ts
- packages/myst-parser/src/directives.ts
- packages/myst-parser/src/roles.ts
Un-recognized roles/directives crash the demo:
> 🐛 Delete children rather than set to undefined

- README.md
Follows the updates that have been made for #181.
> 📖 Update package lists in README

- docs/code.md
> 📖 Remove code-numbering warnings

- .changeset/twenty-rabbits-repeat.md
- packages/myst-to-tex/src/index.ts
> #️⃣ unstar sections when numbering=true

- packages/myst-cli/src/transforms/images.ts
- packages/myst-cli/src/utils/imagemagick.ts
> 🌠 Support TIFF images

- .changeset/heavy-crabs-grin.md
- .changeset/witty-items-build.md
- packages/myst-directives/src/code.ts
- packages/myst-directives/src/index.ts
- packages/myst-spec-ext/src/types.ts
See #284
Follows the implementation here: https://jupyterbook.org/en/stable/file-types/myst-notebooks.html
> ⌨️ Add code-cell directive

- packages/myst-parser/README.md
Changes the readme based on prompting from @astrojuanlu 🙏
> 📖 Small updates to `myst-parser` readme

- .changeset/curvy-kiwis-smile.md
- .changeset/lucky-bananas-drum.md
- .changeset/ninety-pumpkins-exist.md
- .changeset/sixty-pears-end.md
- .changeset/three-actors-fly.md
- packages/citation-js-utils/src/index.ts
- packages/myst-cli/src/transforms/citations.ts
- packages/myst-spec-ext/src/types.ts
- packages/tex-to-myst/src/characters.ts
- packages/tex-to-myst/src/citations.ts
- packages/tex-to-myst/src/tex.ts
- packages/tex-to-myst/src/utils.ts
- packages/tex-to-myst/tests/citations.yml
- Allow macros in tex parsing
- Prefix and suffix for inline citations
> 👩‍🔬 Inline citation improvements

- .changeset/twenty-files-double.md
- packages/myst-cli/src/process/file.ts
- packages/myst-cli/src/process/mdast.ts
- packages/myst-cli/src/transforms/embed.ts
- packages/myst-cli/src/transforms/outputs.ts
- packages/myst-cli/src/transforms/types.ts
- packages/myst-common/src/index.ts
- packages/myst-common/src/types.ts
> 🌀 Change to `SourceFileKind` (from KINDS)

- .changeset/selfish-bags-exercise.md
- package-lock.json
- packages/myst-cli/package.json
Thanks to @GYHHAHA
See discussion here:
https://github.com/orgs/executablebooks/discussions/986
> 🐛 Add `p-limit` to dependencies

- .changeset/bright-dots-applaud.md
- packages/myst-frontmatter/src/frontmatter/frontmatter.spec.ts
- packages/myst-frontmatter/src/frontmatter/types.ts
- packages/myst-frontmatter/src/frontmatter/validators.ts
- packages/myst-frontmatter/tests/thebe.yml
This updates thebe options in frontmatter to (1) remove unnecessary advanced options, (2) add local config options, and (3) allow some option objects to also be overridden with true/false.
> 📂 Update thebe frontmatter options

- .changeset/strong-toys-speak.md
- packages/myst-to-tex/src/index.ts
- packages/myst-to-tex/src/math.ts
- packages/myst-to-tex/tests/math.spec.ts
> 📡 Recursive math commands for LaTeX

- .changeset/funny-olives-cross.md
- packages/myst-parser/src/directives.ts
Change unknown directives from showing warnings to showing errors.
> 🙀 Unknown directives show errors

- .changeset/friendly-gifts-bake.md
- packages/myst-frontmatter/src/frontmatter/frontmatter.spec.ts
- packages/myst-frontmatter/src/frontmatter/types.ts
- packages/myst-frontmatter/src/frontmatter/validators.ts
- packages/myst-templates/src/frontmatter.ts
- packages/myst-templates/src/types.ts
This PR would enable us to add a collaboration field as need by the [Physical Review Template](https://github.com/dressedfez/myst_template_physical_review_journals). 
The template has been updated accordingly see [here](https://github.com/dressedfez/myst_template_physical_review_journals/issues/12).
> Adds collaboration associated with author

- .changeset/wild-ligers-hammer.md
- README.md
- docs/analytics.md
- docs/cross-references.md
- docs/dropdowns-cards-and-tabs.md
- docs/glossary.md
- docs/index.md
- docs/myst.yml
- docs/quickstart-myst-documents.md
- docs/quickstart-myst-websites.md
- packages/jtex/docs/contribute-a-template.md
- packages/jtex/docs/create-a-latex-template.md
- packages/jtex/docs/index.md
- packages/jtex/docs/myst.yml
- packages/myst-cli/README.md
- packages/myst-cli/docs/myst.yml
- packages/myst-cli/src/build/init.ts
- packages/myst-cli/src/session/session.ts
- packages/myst-cli/tests/basic-md-and-config/myst.yml
- packages/myst-templates/src/download.spec.ts
- packages/myst-templates/src/session.ts
- packages/myst-to-jats/docs/myst.yml
- packages/myst-to-jats/tests/basic.yml
- packages/myst-to-md/docs/myst.yml
- packages/myst-transforms/docs/myst.yml
> 🎨 Re-brand to https://mystmd.org

- .changeset/two-donuts-breathe.md
- packages/myst-cli/src/build/site/manifest.ts
The fastest project was the home page before!
> 🐎 Race condition in writing project config

- packages/jtex/docs/contribute-a-template.md
> 📖 Update jtex docs

- .changeset/tiny-terms-give.md
- package-lock.json
- packages/myst-cli/src/utils/check.ts
- packages/mystmd/package.json
- packages/mystmd/src/index.ts
Check that we are on a LTS version of node.
> ✅ Check that node >=16

- .changeset/great-dolphins-fail.md
- .changeset/silver-avocados-speak.md
- docs/figures.md
- docs/quickstart-jupyter-lab-myst.md
- docs/quickstart-myst-documents.md
- docs/quickstart-myst-markdown.md
- docs/quickstart-myst-websites.md
- docs/quickstart.md
- packages/jtex/docs/create-a-latex-template.md
- packages/myst-directives/src/iframe.ts
- packages/myst-parser/tests/directives/iframe.yml
- packages/myst-spec-ext/src/types.ts
Allow iframes to have captions as well, which turn them into figures.
> 📺 Document videos and iframes

- docs/quickstart-myst-documents.md
Related to https://github.com/executablebooks/mystmd/issues/482
> Start documentation of Markdown exporter

- .changeset/blue-seahorses-hammer.md
- packages/myst-cli/src/frontmatter.ts
- packages/myst-cli/src/utils/toc.ts
- packages/myst-transforms/src/frontmatter.spec.ts
- packages/myst-transforms/src/frontmatter.ts
This applies to file frontmatter. It should resolve https://github.com/executablebooks/mystmd/issues/459
> 🪵 Log errors instead of throwing on frontmatter yaml load

- .changeset/nasty-spies-grow.md
- packages/myst-transforms/src/frontmatter.ts
> ⚠️ Add YAML error messages to logs

- package-lock.json
- packages/myst-to-typst/.eslintrc.cjs
- packages/myst-to-typst/CHANGELOG.md
- packages/myst-to-typst/README.md
- packages/myst-to-typst/package.json
- packages/myst-to-typst/src/container.ts
- packages/myst-to-typst/src/index.ts
- packages/myst-to-typst/src/math.ts
- packages/myst-to-typst/src/types.ts
- packages/myst-to-typst/src/utils.ts
- packages/myst-to-typst/tests/admonitions.yml
- packages/myst-to-typst/tests/basic.yml
- packages/myst-to-typst/tests/cite.yml
- packages/myst-to-typst/tests/code.yml
- packages/myst-to-typst/tests/comments.yml
- packages/myst-to-typst/tests/cross-references.yml
- packages/myst-to-typst/tests/definitions.yml
- packages/myst-to-typst/tests/figures.yml
- packages/myst-to-typst/tests/footnotes.spec.ts
- packages/myst-to-typst/tests/footnotes.yml
- packages/myst-to-typst/tests/links.yml
- packages/myst-to-typst/tests/lists.yml
- packages/myst-to-typst/tests/math.spec.ts
- packages/myst-to-typst/tests/run.spec.ts
- packages/myst-to-typst/tests/sections.yml
- packages/myst-to-typst/tsconfig.json
This is the initial implementation of the `myst-to-typst` work. I have pulled it out from the CLI and removed a few other pieces that don't work yet so that we can get this merged.
> 🪄 Initial `myst-to-typst` implementation

- .changeset/tiny-spoons-itch.md
- packages/myst-cli/src/session/session.ts
We should do this through an environment variable set in python in the near future.
> ⎌ Undo upgrade message changes

- .changeset/good-hairs-drive.md
- packages/myst-cli/src/build/gh-pages/index.ts
> 🐛 Update URLs for github.io domains

- .changeset/curvy-carrots-warn.md
- packages/myst-cli/src/build/gh-pages/index.ts
@kolibril13 this should fix it up for other people as well:
> 🌍 Unset `BASE_URL` for github.io domains

- docs/deployment.md
- packages/myst-cli/src/build/gh-actions/index.ts
- packages/myst-cli/src/build/init.ts
- packages/mystmd/src/init.ts
- packages/mystmd/src/options.ts
This updates the documentation and github action codes for:
- GitHub pages
- Curvenote
Both now have docs and auto-creation scripts.
> 🤖 Updates for auto-creation of github actions

- docs/glossaries-and-terms.md
This now points to RST and gives an example to Sphinx users.
See executablebooks/MyST-NB#544 and #618
> 📚 Improve glossary documentation

- .changeset/twelve-pianos-vanish.md
- docs/table-of-contents.md
- packages/myst-cli/src/project/fromPath.ts
- packages/myst-cli/src/project/toc.spec.ts
Now `chapter10` comes after `chapter9`.
> 🗺 Sort table of contents

- .changeset/tricky-cooks-invite.md
- docs/deployment.md
- packages/myst-cli/src/build/gh-actions/index.ts
cc @ErnestSuyver, some small updates to the GitHub deployment action for custom github domains.
> 📖 Update deployment documentation

- .changeset/yellow-rivers-grab.md
- package-lock.json
- package.json
- packages/citation-js-utils/package.json
- packages/jats-to-myst/package.json
- packages/jtex/package.json
- packages/myst-cli/package.json
- packages/myst-common/package.json
- packages/myst-templates/package.json
- packages/myst-to-docx/package.json
- packages/myst-to-html/package.json
- packages/myst-to-jats/package.json
- packages/myst-to-md/package.json
- packages/myst-to-tex/package.json
- packages/myst-transforms/package.json
- packages/mystmd/.eslintrc.cjs
- packages/mystmd/package.json
- packages/tex-to-myst/package.json
> 🧹 Warn about unlisted dependencies

- .changeset/green-rocks-retire.md
- packages/tex-to-myst/src/misc.ts
- packages/tex-to-myst/src/refs.ts
- packages/tex-to-myst/src/tex.ts
> 📑 Add additional nodes for parsing latex

- .changeset/thick-garlics-serve.md
- .changeset/tough-owls-rest.md
- packages/myst-to-jats/src/frontmatter.ts
- packages/myst-to-jats/src/index.ts
- packages/myst-to-jats/tests/authors.yml
- packages/myst-to-jats/tests/basic.yml
> 🗝 Escape all attributes in js2xml for JATS

- .changeset/hungry-deers-tan.md
- .changeset/perfect-camels-double.md
- .changeset/twelve-rockets-develop.md
- docs/frontmatter.md
- package-lock.json
- packages/jtex/docs/document.md
- packages/myst-frontmatter/src/frontmatter/types.ts
- packages/myst-frontmatter/src/frontmatter/validators.ts
- packages/myst-frontmatter/tests/affiliations.yml
- packages/myst-to-jats/package.json
- packages/myst-to-jats/src/frontmatter.ts
- packages/myst-to-jats/tests/funding.yml
- packages/myst-to-jats/tests/multi.yml
> 🎓 JATS author/affiliation updates

- .changeset/smooth-apples-impress.md
- packages/myst-to-jats/src/frontmatter.ts
- packages/myst-to-jats/tests/funding.yml
Pulls out some of the changes in #656.
> 🎓 Do not include deparment in funding institution

- .changeset/gentle-beans-sip.md
- .changeset/silly-jars-deliver.md
- packages/myst-to-jats/src/index.ts
- packages/tex-to-myst/src/misc.ts
- packages/tex-to-myst/src/siunitx.ts
- packages/tex-to-myst/src/tables.ts
- packages/tex-to-myst/src/tex.ts
- packages/tex-to-myst/tests/siunitx.yml
> 📜 Improvements to LaTeX parsing

- .changeset/short-glasses-tease.md
- package-lock.json
- packages/myst-to-jats/package.json
- packages/myst-to-jats/src/index.ts
- packages/myst-to-jats/tests/basic.yml
- packages/myst-transforms/src/index.ts
- packages/myst-transforms/src/math.ts
We still need to pass macros down to this file.
And then remove them in the LaTeX
> 🧮  Improve MathML export for JATS

- .changeset/shy-readers-check.md
- packages/myst-cli/src/process/mdast.ts
- packages/myst-cli/src/transforms/outputs.spec.ts
- packages/myst-cli/src/transforms/outputs.ts
This addresses https://github.com/executablebooks/mystmd/issues/660 by removing the extra notebook output files during processing.
> ✂️ Delete temporary output files in reduceOutput transform

- .changeset/poor-hotels-worry.md
- package-lock.json
- packages/myst-cli/src/process/mdast.ts
- packages/myst-cli/src/transforms/include.ts
- packages/myst-transforms/src/include.ts
I am surprised that we didn't see this in our testing, but did figure it out thanks to @eurunuela.
> 🐛 Fix async issue with include transform

- .changeset/fluffy-toes-jump.md
- packages/myst-cli/src/build/site/prepare.ts
- packages/myst-cli/src/build/site/start.ts
- packages/mystmd/src/options.ts
- packages/mystmd/src/site.ts
> ⚓️ Specify PORT in the CLI

- .changeset/lazy-ravens-invent.md
- docs/citations.md
- packages/myst-roles/package.json
- packages/myst-roles/src/cite.spec.ts
- packages/myst-roles/src/cite.ts
> 👩‍🔬 Prefix and suffix parsing for citation roles

- .changeset/wild-jokes-draw.md
- packages/myst-transforms/src/basic.ts
- packages/myst-transforms/src/removeUnicode.spec.ts
- packages/myst-transforms/src/removeUnicode.ts
> ⁇ Remove unknown unicode characters by default

- .changeset/purple-dragons-march.md
- package-lock.json
- packages/myst-parser/src/myst.ts
- packages/myst-parser/src/types.ts
- packages/myst-parser/tests/commonmark.spec.ts
- packages/myst-parser/tests/myst.spec.ts
- packages/myst-parser/tests/smartquotes.spec.ts
- packages/myst-to-tex/package.json
- packages/myst-to-tex/tests/smartquotes.spec.ts
> ＂ Enable smartquotes

- .changeset/loud-gorillas-design.md
- .changeset/rich-coins-cough.md
- .changeset/thirty-spiders-trade.md
- docs/directives.md
- docs/tables.md
- package-lock.json
- packages/myst-common/src/types.ts
- packages/myst-directives/package.json
- packages/myst-directives/src/code.spec.ts
- packages/myst-directives/src/code.ts
- packages/myst-directives/src/include.spec.ts
- packages/myst-directives/src/include.ts
- packages/myst-directives/src/index.ts
- packages/myst-directives/src/table.ts
- packages/myst-parser/src/directives.ts
- packages/myst-parser/src/roles.ts
- packages/myst-roles/src/term.ts
> 🍽 Add table directive

- .changeset/polite-kangaroos-bow.md
- packages/jtex/src/imports.ts
- packages/myst-to-tex/src/index.ts
- packages/myst-to-tex/src/proof.ts
- packages/myst-to-tex/tests/glossaries.yml
Addresses https://github.com/executablebooks/mystmd/issues/737
> 🧹 Tidy newlines in tex output

- packages/myst-cli/src/process/notebook.ts
This is a no-op! But better to use the types and utilities that we already have! :)
@stevejpurves I think you might be making a few changes in here.
> 🔃 Refactor to use `nbtx` utilities

- .changeset/lovely-walls-behave.md
- .changeset/pretty-mirrors-fail.md
- .changeset/strange-bugs-suffer.md
- .changeset/three-wombats-pump.md
- docs/_toc.yml
- docs/frontmatter.md
- docs/settings.md
- packages/myst-cli/src/process/mdast.ts
- packages/myst-cli/src/transforms/code.ts
- packages/myst-cli/src/transforms/outputs.spec.ts
- packages/myst-cli/src/transforms/outputs.ts
- packages/myst-common/src/index.ts
- packages/myst-common/src/types.ts
- packages/myst-frontmatter/src/project/project.yml
- packages/myst-frontmatter/src/project/types.ts
- packages/myst-frontmatter/src/project/validators.ts
- packages/myst-frontmatter/src/utils/fillPageFrontmatter.ts
This adds a few known settings to the project/page, these are meant to change how parsing, plugins or transforms behave. The first settings I put in are around removing notebook stderr/stdout outputs from cells and removing matplotlib strings.
> ⚙️ Add `settings` to project

- .changeset/green-bulldogs-float.md
- .changeset/little-fans-pretend.md
- docs/settings.md
- packages/myst-cli/src/build/tex/single.ts
- packages/myst-frontmatter/src/index.ts
- packages/myst-frontmatter/src/project/types.ts
- packages/myst-frontmatter/src/project/validators.ts
- packages/myst-frontmatter/src/settings/index.ts
- packages/myst-frontmatter/src/settings/mystToTex.yml
- packages/myst-frontmatter/src/settings/settings.yml
- packages/myst-frontmatter/src/settings/types.ts
- packages/myst-frontmatter/src/settings/validators.ts
- packages/myst-frontmatter/src/settings/validatorsMystToTex.ts
- packages/myst-to-tex/src/index.ts
- packages/myst-to-tex/src/types.ts
- packages/myst-to-tex/tests/basic.yml
- Introduce mystToTex settings
- Including minted, listings, or verbatim for code cells
See also #369
> ⚙️ Add settings for latex rendering

- .changeset/slow-eggs-relax.md
- packages/myst-frontmatter/src/numbering/validators.ts
> ♽ Refactor error suppression

- .changeset/eighty-students-sin.md
- .changeset/lovely-beds-shout.md
- package-lock.json
- packages/myst-cli/src/process/mdast.ts
- packages/myst-cli/src/process/notebook.ts
- packages/myst-cli/src/transforms/code.ts
- packages/myst-directives/package.json
- packages/myst-directives/src/code.ts
- packages/myst-transforms/src/code.ts
should fix:
* #748 
* #816 
* https://github.com/executablebooks/thebe/issues/699
* #669 
See https://github.com/stevejpurves/text-based-myst-nbs for the test case I've been using - especailly note the thematic break in the text based notebook
> fixing execution in text based notebooks

- .changeset/plenty-otters-allow.md
- packages/myst-cli/src/build/typst.ts
> 🎇 PDF in typst is not supported

- .changeset/rotten-falcons-suffer.md
- packages/myst-to-typst/src/index.ts
- packages/myst-to-typst/tests/basic.yml
- packages/myst-to-typst/tests/cross-references.yml
- packages/myst-to-typst/tests/run.spec.ts
> 🔗 Cross references with trailing text

- .changeset/happy-shirts-hear.md
- packages/myst-templates/src/frontmatter.ts
> 📆 Show date as UTC date

- .changeset/long-tables-suffer.md
- package-lock.json
- packages/myst-cli/src/build/utils/collectExportOptions.ts
- packages/mystmd/tests/outputs/notebook.tex
This should address the heading level bug described here: https://github.com/curvenote/curvenote/issues/467
Recent changes improved title/section level handling on multi-article exports, but certain single-article cases got worse. This PR should return the single-article back to previous behavior.
> 🔧 Fix section level for single article exports

- docs/website-themes.md
Closes #881 and replaces #https://github.com/jbusecke/mystmd/pull/1#issuecomment-1930662436.
> 📖 Fix typo in Website Themes doc page

- .github/actions/install/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- packages/myst-execute/tests/run.spec.ts
This is trying out a "composite action" so install steps are not duplicated across ci / release actions.
> 🤖 Consolidate install steps for all github actions

- .github/workflows/release.yml
- packages/mystmd/package.json
> 🛠 Fix deployment to PyPI

- .changeset/hip-pigs-walk.md
- packages/myst-frontmatter/src/contributors/authors.yml
- packages/myst-frontmatter/src/contributors/validators.ts
> 🧞‍♀️ Affiliations can be an object

- .changeset/warm-radios-watch.md
- packages/tex-to-myst/src/quotes.ts
Just came accross another environment, builds on #922.
> 💬 Support quotation environment in latex

- README.md
- package.json
- turbo.json
See #995 and Discord conversations.
> 📖 Update install and development help

- docs/_toc.yml
- docs/embed.md
This is a brief overview of "embedding" things with MyST. It's probably not complete, but I found it hard to discover this content and the sensible behavior so thought I'd write up my understanding of it right now.
A few questions:
1. I couldn't figure out how to embed content from a different page. Is that possible?
2. I wasn't sure whether it was best to use a dedicated page (so it's more discoverable) or use a sub-section of the "cross references" page, but this seemed to be the simplest approach. Is that OK?
> 📖 Embedding documentation

- .changeset/smart-spiders-cough.md
- packages/myst-transforms/src/html.ts
- packages/myst-transforms/tests/html.yml
Picks up on the `align` property in a table cell.
> 🍽 Table cell alignment

- .changeset/flat-hounds-chew.md
- .changeset/funny-walls-beg.md
- packages/myst-common/src/extractParts.ts
- packages/myst-parser/src/tokensToMyst.ts
Addresses the issues raised here: https://github.com/executablebooks/mystmd/issues/1050 - more discussion on that issue
> ✂️ Extract parts is more careful to remove parts from tree

- .changeset/kind-plants-ring.md
- packages/jtex/src/typst/export.ts
- packages/myst-cli/src/build/typst.ts
> 📄 Typst compile should be in quotes

- .changeset/shaggy-bobcats-behave.md
- packages/myst-cli/src/transforms/doi.spec.ts
- packages/myst-cli/src/transforms/dois.ts
> 🐛 Support and test complex DOIs

- .changeset/violet-pets-retire.md
- packages/myst-transforms/src/code.spec.ts
- packages/myst-transforms/src/code.ts
> 🐛 Syntax highlighting for R

- .changeset/three-gorillas-battle.md
- docs/_toc.yml
- docs/analytics.md
- docs/quickstart-myst-websites.md
- docs/website-templates.md
- packages/myst-cli/src/build/html/index.ts
- packages/myst-cli/src/build/init.ts
See #925
Requires: https://github.com/executablebooks/myst-theme/pull/361
> ⭐️ Add custom favicon

- docs/creating-pdf-documents.md
- Mulit-Article renamed to Multi-Article
> [DOC] Fix typo in creating-pdf-documents.md

- .changeset/dull-snakes-dream.md
- docs/notebooks-with-markdown.md
- packages/myst-cli/src/process/notebook.ts
- packages/myst-directives/src/code.ts
- packages/myst-execute/.gitignore
- packages/myst-execute/src/execute.ts
- packages/myst-execute/tests/execute.yml
- packages/myst-spec-ext/src/types.ts
- packages/myst-to-jats/src/transforms/sections.ts
- packages/myst-to-jats/tests/basic.yml
- packages/myst-to-jats/tests/notebooks.yml
- packages/myst-transforms/src/blocks.spec.ts
- packages/myst-transforms/src/blocks.ts
> 🧱 Add kind to block and make execution more specific

- .changeset/clever-coats-rhyme.md
- packages/myst-directives/src/table.ts
This fixes a failure I found in the live demo. @agoose77, you might have more insights as to why this happens?
> 🐛 CSV Table directive parsing

- .changeset/witty-dodos-guess.md
- packages/myst-transforms/src/html.ts
See executablebooks/jupyterlab-myst#232
> 🎨 Support details/summary in HTML

- .changeset/hungry-spies-decide.md
- packages/myst-cli/src/build/html/index.ts
See executablebooks/myst-theme#370
> 🎨 Support theme variables for static site exports

- .changeset/heavy-flies-dress.md
- packages/myst-to-tex/src/index.ts
- packages/myst-to-tex/tests/basic.yml
- packages/myst-to-typst/src/index.ts
- packages/myst-to-typst/src/types.ts
- packages/myst-to-typst/tests/basic.yml
> 🧱 Basic support for div/span in typst and LaTeX

- packages/mystmd/src/options.ts
Fixes case bug introduced in #1177
> 🐛 `--write-toc` case bug

- .changeset/hip-readers-taste.md
- packages/myst-spec-ext/src/types.ts
- packages/myst-transforms/src/links/myst.spec.ts
- packages/myst-transforms/src/links/myst.ts
- packages/myst-transforms/src/links/plugin.spec.ts
This will allow for recursive links in the theme.
> 🔗 Add remote cross-project link to AST

- docs/figures.md
just clarifies a little bit because it wasn't clear to me at first
> 📖  Clarify how to link to image+videos

- .changeset/smooth-ways-enjoy.md
- package-lock.json
- packages/myst-cli/package.json
> 🧬 Support for bioRxiv URLs

- .changeset/stupid-apples-unite.md
- docs/external-references.md
- packages/myst-cli/src/process/mdast.ts
- packages/myst-cli/src/transforms/index.ts
- packages/myst-cli/src/transforms/ror.ts
- packages/myst-common/src/ruleids.ts
- packages/myst-transforms/docs/links.md
- packages/myst-transforms/src/links/index.ts
- packages/myst-transforms/src/links/ror.ts
https://github.com/executablebooks/mystmd/assets/913249/260e7642-fdb3-4ae7-9026-a5ca53c23e07
> 🦁 Add ROR hover links

- .changeset/cold-turkeys-sip.md
- packages/myst-cli/src/process/mdast.ts
- packages/myst-common/src/utils.ts
- packages/myst-to-html/src/state.ts
We can do this now that we require `node>=18`.
> 🧹 Use `structuredClone` instead of JSON for copies

- docs/integrating-jupyter.md
- **typo Juptyer vs Jupyter**
- **typo bindle vs bundle**
> 📖 Documentation Typos

- .changeset/big-vans-kick.md
- packages/myst-transforms/src/html.spec.ts
- packages/myst-transforms/src/html.ts
> 📺 Support for HTML video tags

- .changeset/blue-candles-laugh.md
- packages/myst-cli/src/build/html/index.ts
> 🐛 Cross references for static sites

- docs/asides.md
- docs/commonmark.md
- docs/cross-references.md
- docs/embed.md
- docs/exercises.md
- docs/figures.md
- docs/quickstart-myst-markdown.md
- docs/typography.md
Currently all unsplash images are broken, this pins them to images that I have taken..
I have not put them in the repo so that we can also use them in the examples. Not sure on the best way to do this.
> 🌄 Fix unsplash images

- .changeset/wild-feet-work.md
- packages/myst-cli/src/build/init.ts
> 📖 Update the basic myst init

- .changeset/rich-vans-admire.md
- packages/myst-common/src/ruleids.ts
> :bug: Address rule-id typo

- .changeset/rude-llamas-cover.md
- packages/myst-transforms/src/html.spec.ts
- packages/myst-transforms/src/html.ts
> ❕ Combine html nodes split by whitespace in reconstructHtml transform

- .changeset/poor-days-tell.md
- packages/myst-cli/src/build/gh-actions/index.ts
- packages/myst-cli/src/build/init.ts
- packages/myst-cli/src/build/utils/git.ts
This idea came out of the Pythia Hackathon.
Fixes: #1304
> :zap: Write initial `.gitignore` in `myst init`

- .changeset/clean-kangaroos-jump.md
- packages/myst-cli/src/process/file.ts
- packages/myst-cli/src/process/mdast.ts
- packages/myst-cli/src/process/notebook.ts
Fixes #1283 by merging notebook metadata (frontmatter) with cell-defined metadata
> :hammer_and_wrench: Combine frontmatter from notebook to support different kernels

- .changeset/sweet-items-sell.md
- packages/myst-parser/src/config.ts
Just carrying on the same theme as this PR: https://github.com/executablebooks/mystmd/pull/1363
> 🌐 Exclude '.so' from tlds

- CONTRIBUTING.md
Changed git clone git@github.com:executablebooks/mystmd.git to git@github.com:jupyter-book/myst.git in CONTRIBUTING.md
> 📖 Updating CONTRIBUTING.md

- .changeset/good-eggs-unite.md
- packages/myst-cli/src/utils/imagemagick.ts
This should address https://github.com/jupyter-book/mystmd/issues/1170 and partially https://github.com/jupyter-book/mystmd/issues/290
> 🪄 Use 'magick' command instead of 'convert' for imagemagick

- .changeset/strange-pumpkins-relax.md
- packages/myst-transforms/src/enumerate.ts
Addresses https://github.com/jupyter-book/mystmd/issues/1364
> 👩‍💻 Change code caption numbers from 'Code' to 'Program'

- .changeset/little-shirts-decide.md
- packages/myst-transforms/src/frontmatter.spec.ts
- packages/myst-transforms/src/frontmatter.ts
This should address the duplicate heading bug discussed in #1222
> 🧱 Do not duplicate h1 title nested in block

- .changeset/fast-gifts-fly.md
- packages/myst-cli/src/build/utils/collectExportOptions.spec.ts
- packages/myst-cli/src/build/utils/collectExportOptions.ts
> 📤 Allow multi-article meca export, following jats

- .changeset/afraid-pandas-hug.md
- .changeset/angry-badgers-flow.md
- .changeset/tiny-mice-rescue.md
I forgot to add changesets over the weekend, so a few PRs need follow up.
> :broom: Add changesets

- .changeset/gold-impalas-cheer.md
- packages/myst-execute/src/execute.ts
- packages/myst-execute/tests/execute.yml
Fixes #1117 
Later on we probably want to move this out of the logs into a dedicated file. However, this is an incremental improvement.
> ✍️ Report tracebacks during kernel execution

- .changeset/friendly-stingrays-matter.md
- .changeset/green-schools-lay.md
- .changeset/sixty-crews-doubt.md
- package-lock.json
- packages/myst-templates/src/validators.ts
- packages/myst-to-typst/package.json
- packages/myst-to-typst/src/container.ts
- packages/myst-to-typst/src/math.ts
- packages/myst-to-typst/src/types.ts
This also depends on an update to `tex-to-typst`: https://github.com/curvenote/tex-to-typst/pull/8
> 📄 Small typst improvements

- .changeset/old-shoes-walk.md
- package-lock.json
- packages/myst-to-typst/package.json
> 🐛 Typst math updates

- docs/deployment-github-pages.md
This is just a teenie typo fix :)
> fix: tiny typo

- docs/guiding-principles.md
> 📝 Fix typo in documentation

- .changeset/gentle-buckets-cheat.md
- docs/glossaries-and-terms.md
- docs/glossary.md
- packages/myst-transforms/src/indices.spec.ts
- packages/myst-transforms/src/indices.ts
See https://github.com/jupyter-book/mystmd/issues/190#issuecomment-2301637051
> È Index accents

- .changeset/kind-cooks-hug.md
- packages/myst-transforms/src/admonitions.ts
See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts
> ⚠️ Expand github alerts to include `tip` and `caution`

- .changeset/empty-otters-judge.md
- packages/myst-cli/src/build/html/index.ts
> 🐛 Write favicon as binary

- .changeset/silly-experts-sniff.md
- packages/markdown-it-myst/src/nestedParse.ts
- packages/markdown-it-myst/tests/roles.spec.ts
- packages/myst-parser/tests/roles/subscript.yml
> 🐛 Inline parsing of roles

- .changeset/nasty-suits-study.md
- packages/myst-cli/src/build/site/logger.ts
- packages/mystmd/src/index.ts
> 🤫 Quiet warning about `punycode`

- .changeset/angry-parrots-cough.md
- packages/myst-cli/src/init/jupyter-book/toc.ts
- packages/myst-cli/src/init/jupyter-book/upgrade.ts
> 🐛 Warn instead of crashing for missing files during upgrade

- .changeset/kind-pigs-act.md
- packages/myst-to-tex/src/math.ts
- packages/myst-to-tex/tests/amsmath.yml
> 🐛 Ensure that AMS Math environments are fully enclosed.

- .changeset/lazy-dots-vanish.md
- packages/markdown-it-myst/src/directives.ts
- packages/markdown-it-myst/tests/directives.spec.ts
- packages/myst-ext-reactive/tests/reactive.spec.ts
- packages/myst-parser/src/roles.ts
- packages/myst-parser/src/tokensToMyst.ts
- packages/myst-parser/tests/directives/code.yml
- packages/myst-parser/tests/directives/ext.directive.spec.ts
- packages/myst-parser/tests/directives/math.yml
- packages/myst-parser/tests/myst.spec.ts
> 🐞 Directive option flag is always a boolean

- .changeset/chilly-eyes-smash.md
- packages/myst-to-tex/src/math.ts
- packages/myst-to-tex/tests/amsmath.yml
> 🐛 Top level AMS Math environments are not wrapped.

- packages/myst-to-tex/tests/amsmath.yml
This is a bit more confidence in #1519 for latex output around nesting of AMS math.
cc @dellaert
> 🧪 Additional test cases

- .changeset/red-swans-remain.md
- packages/myst-cli/src/build/html/index.ts
Fixes #1449
Replaces https://github.com/jupyter-book/myst-theme/pull/485
> 🌠 Support favicon in static builds

- docs/execute-notebooks.md
- docs/integrating-jupyter.md
- docs/interactive-notebooks.ipynb
- docs/myst.yml
- docs/notebooks-with-markdown.md
- docs/reuse-jupyter-outputs.md
This PR hopes to close #1569 by reworking our existing titles. See the branch preview for more details.
> 🔠 Rework execution documentation titles and descriptions

- docs/quickstart-myst-documents.md
- docs/quickstart.md
This moves away from "enriched" to something meaningful --> "Scientific Articles" which is what this tutorial is about.
We should probably write another one in the future about books / courses, etc. which is a bit more focused on the toc.
> 📖 Update doc tutorial titles

- .changeset/poor-shrimps-tickle.md
- packages/myst-to-typst/src/index.ts
> 🗂️ Render tabs in typst

- .changeset/cool-suits-repair.md
- packages/myst-directives/src/iframe.ts
- packages/myst-spec-ext/src/types.ts
- packages/myst-to-typst/src/index.ts
Enables iframes to be written to PDFs.
> 🎇 Placeholder for iFrame

- .changeset/nervous-buttons-give.md
- packages/myst-parser/src/config.ts
- packages/myst-parser/tests/linkify.spec.ts
> 🌎 Remove TLD of `.es` from linkify

- .changeset/strange-baboons-build.md
- docs/execute-notebooks.md
- packages/myst-cli/src/session/session.ts
> 🚀 Always launch a new Jupyter Server

- package-lock.json
- packages/myst-to-typst/package.json
> 🧮 Update typst math conversion (v0.0.14)

- .changeset/funny-chairs-argue.md
- packages/myst-cli/src/session/session.ts
@choldgraf can you give a thumbs up?
Reminded from #1760
> 🦋 Change from twitter link to bsky link

- .changeset/serious-boats-film.md
- packages/myst-cli/src/init/gh-actions/index.ts
> 📖 Update comment in GH Pages deploy script

- .changeset/long-bees-pay.md
- package-lock.json
- packages/jats-to-myst/package.json
- packages/myst-cli/package.json
- packages/myst-frontmatter/package.json
- packages/myst-to-jats/package.json
- packages/myst-transforms/package.json
> 📦 Update to `doi-utils` v2.0.4

- docs/dropdowns-cards-and-tabs.md
See jupyter-book/myst-theme#506 for the change that warrants this PR.
> 📌 Update docs about grid breakpoints to reflect changes in theme

- .changeset/pretty-glasses-kiss.md
- packages/myst-cli/src/init/jupyter-book/toc.ts
> ✍️ Fix typo in Jupyter Book TOC upgrade routine

- docs/execute-notebooks.md
- docs/notebooks-with-markdown.md
> 📖 Improve Executable Markdown Documentation

- docs/website-navigation.md
`site-options` --> `#site-options` and linting
> 📖 Remove warnings

- .changeset/clean-students-fail.md
- package-lock.json
- packages/jats-to-myst/package.json
- packages/myst-cli/package.json
- packages/myst-frontmatter/package.json
- packages/myst-to-jats/package.json
- packages/myst-transforms/package.json
See #1336, continuous-foundation/doi-utils#16
> 📦 Update to `doi-utils` v2.0.5

- docs/website-landing-pages.md
> 🐝 Fix missing class in landing-pages

- .changeset/chatty-mangos-deliver.md
- package-lock.json
- packages/myst-cli/package.json
- packages/myst-to-jats/package.json
Fixes https://github.com/jupyter-book/mystmd/issues/1883
> 📦 Bump `nbtx` 0.4.0

- .changeset/giant-camels-buy.md
> 📝 Add missing changeset

- docs/creating-pdf-documents.md
This adds clearer instructions for how to install and use Typst, see [this discord thread for some context](https://discord.com/channels/1083088970059096114/1355534877553983529/1356388423807537362)
> Update the documentation on installing with Typst

- netlify.toml
This is in preparation for enabling draft PR preview on Netlify.
> ✋ netlify: only rebuild docs when they were modified

- docs/website-downloads.md
This PR was motivated by some questions on Discord.
> 📦 Improve docs on PDF exports for downloads

- .changeset/warm-sheep-poke.md
- packages/myst-to-typst/src/utils.ts
- packages/myst-to-typst/tests/basic.yml
> ; Semicolon escape in typst

- docs/execute-notebooks.md
- docs/settings.md
This documents the behavior that was confusing in
- https://github.com/jupyter-book/mystmd/issues/1990
> DOCS: Clarify and cross-link code cell output suppression

- .changeset/curly-beers-study.md
- docs/frontmatter.md
- packages/myst-frontmatter/src/affiliations/affiliations.yml
- packages/myst-frontmatter/src/affiliations/types.ts
- packages/myst-frontmatter/src/affiliations/validators.ts
- packages/myst-frontmatter/src/contributors/contributors.yml
- packages/myst-frontmatter/src/contributors/types.ts
- packages/myst-frontmatter/src/contributors/validators.ts
- packages/myst-frontmatter/src/utils/index.ts
- packages/myst-frontmatter/src/utils/socialLinks.ts
Adds bluesky, mastodon, x, threads, linkedin and allows these to be added to affiliations as well.
cc @thesamovar
See #1685
> 🦋 Add bluesky social links

- docs/figures.md
- docs/website-style.md
ref: https://discord.com/channels/1083088970059096114/1177359316886503464/1367582833975099562
> 📖 Document light dark elements with CSS classes

- .changeset/two-trains-invite.md
- packages/myst-cli/src/project/fromTOC.ts
- packages/myst-toc/src/toc.ts
- packages/myst-toc/src/types.ts
- packages/myst-toc/tests/examples.spec.ts
this is in relation to https://github.com/jupyter-book/mystmd/issues/814
I am far from fluent with typescript
so this is a very preliminary work, and only partial
I'm primarily curious to have your feedback and check this is going in the right direction
> 🕵️‍♀️ Expose hidden attribute in TOC nodes

- .changeset/spotty-onions-refuse.md
- package-lock.json
- packages/myst-to-typst/package.json
This is just a small PR to bump `tex-to-typst`.
Looks like there are some `husky`/`lint-staged`-related changes to `package-lock`... I think that's fine?
> 📦 Bump tex-to-typst@0.0.16

- docs/deployment-netlify.md
- docs/deployment.md
- docs/website-metadata.md
This adapts and documents some useful CORS tips that @rowanc1 posted in the following issue:
- https://github.com/the-turing-way/the-turing-way/pull/4156
> Document CORS tip

- flake.lock
- flake.nix
This PR bumps the dev flake inputs, and brings in Typst.
> ❄️ Update dev flake inputs

- .github/workflows/docs.yml
Fixes: jupyter-book/team-compass#25
> 🤖 Deploy Docs in CI

- .changeset/proud-comics-bathe.md
- packages/myst-transforms/src/html.spec.ts
- packages/myst-transforms/src/html.ts
Fixes ProjectPythia/cookbook-template#226
> 🗾 HTML Image Width

- .changeset/light-pillows-love.md
- packages/myst-cli/src/process/mdast.ts
- packages/myst-transforms/src/mathSimplifications.spec.ts
- packages/myst-transforms/src/mathSimplifications.ts
> 🧮 Improve inline math symbol replacements

- docs/contributing.md
Closes https://github.com/jupyter-book/team-compass/issues/28
> Document our lightweight development prioritization process

- .changeset/selfish-candles-hear.md
- packages/myst-frontmatter/src/licenses/licenses.ts
This PR was generated by:
1. Running `packages/myst-frontmatter/bin/fetchLicenses.mjs`.
2. Copying `licenses` to the clipboard.
3. Pasting the contents over the `licenses` object in `packages/myst-frontmatter/src/licenses/licenses.ts`
4. Running the default code formatter.
> 👩🏼‍💼 Update OSI Licenses

- .github/workflows/publish-github-release.yml
> Attach release to pre-existing tag

- .github/workflows/publish-github-release.yml
> Remove explicit target for tag

- .github/workflows/publish-github-release.yml
- .github/workflows/release.yml
> Clean up title and fix tag name in CI/CD

- docs/external-references.md
- docs/myst.yml
- packages/myst-transforms/docs/links.md
- packages/mystmd/tests/outputs/site-xrefs-config.json
- packages/mystmd/tests/outputs/site-xrefs-index.json
- packages/mystmd/tests/site-xrefs/myst.yml
This is affecting the docs only, yet it won't hurt to show a recent version.
> 📖 Swapping out python references to an up-to-date version

- .changeset/silver-zebras-hide.md
- packages/myst-spec-ext/src/types.ts
This should have been completed in #2133!
> 🐛 Typst option on inlineMath node

- .changeset/neat-knives-play.md
- packages/myst-cli/src/process/myst.ts
This is supporting some upcoming work on formatting. #1948
> 🔄 Refactor myst-parse to expose parsing options

- .changeset/poor-mangos-watch.md
- packages/myst-cli/src/build/meca/index.ts
> 🐛 Add Typst PDF to the MECA bundle

- .changeset/honest-zebras-swim.md
- packages/myst-cli/src/cli/build.ts
> 🔑 Add `--keep-host` to `build` command

- .changeset/gold-cooks-wait.md
- package-lock.json
- package.json
- packages/markdown-it-myst/src/directives.ts
- packages/markdown-it-myst/src/index.ts
- packages/markdown-it-myst/src/roles.ts
- packages/myst-cli-utils/src/exec.ts
- packages/myst-cli/package.json
- packages/myst-cli/src/transforms/images.ts
- packages/myst-common/package.json
- packages/myst-directives/package.json
- packages/myst-templates/src/download.ts
- packages/myst-to-docx/src/types.ts
- packages/myst-to-md/src/types.ts
This updates packages that are in our build process.
> 📦 Updates to build packages (typescript, esbuild, vite, nanoid)

- .changeset/neat-games-bow.md
- package-lock.json
- packages/myst-cli/package.json
- packages/myst-execute/package.json
This PR both lifts the minimum version and bumps the lockfile. The versions aren't chosen for compatibility reasons — I just think 12 months is reasonable.
@bsipocz I hope this helps.
> 📦 Update `@jupyterlab/services` lockfile pin
